#!/usr/bin/env bash
# =============================================================================
#  docker_rebuild.sh   --   AUTO-GENERATED by docker_discovery.ps1
#  Recreates the captured Docker images / volumes / networks / containers.
#  Cross-platform (Windows / Linux / macOS). Volume DATA is NOT restored.
#  Re-running is safe: existing objects are skipped; named containers are
#  replaced (docker rm -f) before being recreated.
# =============================================================================
set -o pipefail

log(){ printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m%s\033[0m\n' "$*"; }

detect_os(){
  case "$(uname -s 2>/dev/null)" in
    Linux*) OS=linux;; Darwin*) OS=mac;;
    MINGW*|MSYS*|CYGWIN*) OS=windows;; *) OS=unknown;;
  esac
}
docker_running(){ docker info >/dev/null 2>&1; }
start_docker(){
  log "Starting Docker engine ($OS) ..."
  case "$OS" in
    linux) command -v systemctl >/dev/null 2>&1 && sudo systemctl start docker 2>/dev/null || sudo service docker start 2>/dev/null;;
    mac) open -a Docker 2>/dev/null || true;;
    windows) dd="/c/Program Files/Docker/Docker/Docker Desktop.exe"; [ -f "$dd" ] && "$dd" >/dev/null 2>&1 & true;;
  esac
  i=0; while ! docker_running; do i=$((i+1)); [ "$i" -gt 90 ] && { warn "Docker not ready."; exit 1; }; sleep 2; done
}
detect_os
docker_running || start_docker

# --- networks ---------------------------------------------------------------

# --- volumes (data NOT restored) -------------------------------------------
docker volume inspect 'portainer_data' >/dev/null 2>&1 || docker volume create --driver 'local' 'portainer_data'
docker volume inspect 'postgresql-data' >/dev/null 2>&1 || docker volume create --driver 'local' 'postgresql-data'

# --- images ----------------------------------------------------------------
docker image inspect 'nginx:latest' >/dev/null 2>&1 || docker pull 'nginx:latest'
docker image inspect 'opensuse/tumbleweed:latest' >/dev/null 2>&1 || docker pull 'opensuse/tumbleweed:latest'
docker image inspect 'portainer/portainer-ee:latest' >/dev/null 2>&1 || docker pull 'portainer/portainer-ee:latest'
docker image inspect 'postgres:latest' >/dev/null 2>&1 || docker pull 'postgres:latest'

# --- containers ------------------------------------------------------------

# container: portainer
docker rm -f 'portainer' >/dev/null 2>&1 || true
docker run -d --name 'portainer' --restart 'always' -w '/' -p '8000:8000/tcp' -p '9443:9443/tcp' -e 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' --network 'bridge' 'portainer/portainer-ee:latest'

# container: my-nginx
docker rm -f 'my-nginx' >/dev/null 2>&1 || true
docker run -d --name 'my-nginx' -p '8080:80/tcp' -e 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' -e 'NGINX_VERSION=1.31.1' -e 'NJS_VERSION=0.9.9' -e 'NJS_RELEASE=1~trixie' -e 'ACME_VERSION=0.4.1' -e 'PKG_RELEASE=1~trixie' -e 'DYNPKG_RELEASE=1~trixie' --network 'bridge' 'nginx' 'nginx' '-g' 'daemon off;'

# container: postgresql-container
docker rm -f 'postgresql-container' >/dev/null 2>&1 || true
docker run -d --name 'postgresql-container' -p '5432:5432/tcp' -e 'POSTGRES_PASSWORD=<strong-password>' -e 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/18/bin' -e 'GOSU_VERSION=1.19' -e 'LANG=en_US.utf8' -e 'PG_MAJOR=18' -e 'PG_VERSION=18.4-1.pgdg13+1' -e 'PGDATA=/var/lib/postgresql/18/docker' --network 'bridge' 'postgres:latest' 'postgres'

log "Rebuild complete."
