#!/usr/bin/env bash
# =============================================================================
#  execute_all.sh
#  GENERATED by submodules/D_compile_and_generate_shell_script.ps1 -- do not edit.
#
#  Orchestrator: runs the three generated scripts in order on the current distro.
#    1. install_device_drivers.sh
#    2. install_must_have_software.sh
#    3. apply_settings.sh
#  Usage:  sudo ./execute_all.sh
# =============================================================================
# =============================================================================
#  _common.sh  --  universal runtime engine for the generated installer scripts
# -----------------------------------------------------------------------------
#  This file is INLINED into every generated script in "Execute on Linux!/" by
#  submodules/D_compile_and_generate_shell_script.ps1.  It is distro- and
#  architecture-agnostic: it detects the running distro FAMILY (apt/dnf/zypper/
#  pacman) and CPU ARCH at runtime, then dispatches installs accordingly.
#
#  Design: Flatpak-first.  GUI apps come from Flathub (identical app id on every
#  distro).  The native package manager is used only for the irreducible base
#  (installing Flatpak itself, CLI/dev tools, drivers, system bits).
# =============================================================================

# Be strict but survivable: we handle per-app failures ourselves, so do not let
# a single failing install abort the whole run.
set -o pipefail

# ----------------------------- pretty output ---------------------------------
# All human-facing chatter goes to fd 3 (stdout) so command output can be hidden.
exec 3>&1
log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*" >&3; }
info() { printf '       %s\n' "$*" >&3; }
ok()   { printf '       \033[32m%s\033[0m\n' "$*" >&3; }
warn() { printf '       \033[1;33m%s\033[0m\n' "$*" >&3; }
err()  { printf '\033[1;31m%s\033[0m\n' "$*" >&3; }

have_cmd() { command -v "$1" >/dev/null 2>&1; }

# ----------------------------- bookkeeping -----------------------------------
RESULTS="${RESULTS:-/tmp/migrate_to_linux_results.tsv}"
: > "$RESULTS" 2>/dev/null || RESULTS="$(mktemp)"
declare -a OK_LIST=() SKIP_LIST=() FAIL_LIST=() MANUAL_LIST=()
record_line() { printf '%s\t%-6s\t%s\t%s\n' "$(date '+%F %T')" "$1" "$2" "${3:-}" >> "$RESULTS"; }
mark_ok()     { OK_LIST+=("$1");     record_line OK     "$1" "${2:-}"; ok "installed: $1"; }
mark_skip()   { SKIP_LIST+=("$1");   record_line SKIP   "$1" "${2:-}"; info "skipped: $1 (${2:-already present})"; }
mark_fail()   { FAIL_LIST+=("$1");   record_line FAIL   "$1" "${2:-}"; err "failed: $1 ${2:+- $2}"; }
mark_manual() { MANUAL_LIST+=("$1"); record_line MANUAL "$1" "${2:-}"; warn "manual step required: $1 ${2:+- $2}"; }

print_summary() {
  log "Summary"
  info "OK:     ${#OK_LIST[@]}"
  info "Skip:   ${#SKIP_LIST[@]}"
  info "Manual: ${#MANUAL_LIST[@]}"
  info "Failed: ${#FAIL_LIST[@]}"
  if [ "${#FAIL_LIST[@]}" -gt 0 ]; then
    warn "Failed items:"; for i in "${FAIL_LIST[@]}"; do info "  - $i"; done
  fi
  if [ "${#MANUAL_LIST[@]}" -gt 0 ]; then
    warn "Need a manual step:"; for i in "${MANUAL_LIST[@]}"; do info "  - $i"; done
  fi
  info "Full log: $RESULTS"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root.  Try:  sudo $0"
    exit 1
  fi
}

# The non-root user we should install Flatpak apps / write desktop files for,
# even though the script itself runs under sudo.
TARGET_USER="${SUDO_USER:-$(id -un)}"
TARGET_HOME="$(getent passwd "$TARGET_USER" 2>/dev/null | cut -d: -f6)"
[ -z "$TARGET_HOME" ] && TARGET_HOME="$HOME"

# =============================================================================
#  DISTRO + ARCHITECTURE DETECTION
# =============================================================================
FAMILY=""      # debian | rhel | suse | arch
PM=""          # apt | dnf | zypper | pacman
DISTRO_ID=""
DISTRO_NAME=""

detect_distro() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    DISTRO_ID="${ID:-}"
    DISTRO_NAME="${PRETTY_NAME:-${NAME:-$ID}}"
  fi
  local hay=" ${DISTRO_ID} ${ID_LIKE:-} "
  case "$hay" in
    *" debian "*|*" ubuntu "*|*" linuxmint "*|*" pop "*|*" zorin "*|*" elementary "*) FAMILY="debian"; PM="apt" ;;
    *" rhel "*|*" fedora "*|*" centos "*|*" rocky "*|*" almalinux "*|*" ol "*) FAMILY="rhel"; PM="dnf" ;;
    *" suse "*|*" opensuse "*|*" sles "*|*" sled "*) FAMILY="suse"; PM="zypper" ;;
    *" arch "*|*" archlinux "*|*" manjaro "*|*" endeavouros "*) FAMILY="arch"; PM="pacman" ;;
    *)
      # Fall back to whichever package manager actually exists.
      if   have_cmd apt-get; then FAMILY="debian"; PM="apt"
      elif have_cmd dnf;     then FAMILY="rhel";   PM="dnf"
      elif have_cmd zypper;  then FAMILY="suse";   PM="zypper"
      elif have_cmd pacman;  then FAMILY="arch";   PM="pacman"
      else err "Unsupported distribution: could not find apt/dnf/zypper/pacman."; exit 1
      fi ;;
  esac
}

ARCH=""        # x86_64 | aarch64 | armhf | other
detect_arch() {
  local m; m="$(uname -m)"
  case "$m" in
    x86_64|amd64)        ARCH="x86_64" ;;
    aarch64|arm64)       ARCH="aarch64" ;;
    armv7l|armhf|armv6l) ARCH="armhf" ;;
    *)                   ARCH="$m" ;;
  esac
}

# arch_supported "x86_64 aarch64"  ->  true if $ARCH is listed (empty list = all)
arch_supported() {
  local list="$1"
  [ -z "$list" ] && return 0
  case " $list " in *" $ARCH "*) return 0 ;; *) return 1 ;; esac
}

# =============================================================================
#  PACKAGE-MANAGER ABSTRACTION
# =============================================================================
_PM_REFRESHED=0
pm_refresh() {
  [ "$_PM_REFRESHED" = "1" ] && return 0
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get update -y ;;
    dnf)    dnf -y makecache ;;
    zypper) zypper --non-interactive refresh ;;
    pacman) pacman -Sy --noconfirm ;;
  esac
  _PM_REFRESHED=1
}

pm_install() {
  [ "$#" -eq 0 ] && return 0
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "$@" ;;
    dnf)    dnf install -y "$@" ;;
    zypper) zypper --non-interactive install -y --no-recommends "$@" ;;
    pacman) pacman -S --noconfirm --needed "$@" ;;
  esac
}

pm_installed() {
  case "$PM" in
    apt)    dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed" ;;
    dnf)    rpm -q "$1" >/dev/null 2>&1 ;;
    zypper) rpm -q "$1" >/dev/null 2>&1 ;;
    pacman) pacman -Q "$1" >/dev/null 2>&1 ;;
  esac
}

# =============================================================================
#  FLATPAK (universal app layer)
# =============================================================================
ensure_flatpak() {
  if ! have_cmd flatpak; then
    log "Installing Flatpak (required for the universal app layer)"
    pm_refresh
    pm_install flatpak || { mark_fail "flatpak" "could not install flatpak via $PM"; return 1; }
  fi
  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo >/dev/null 2>&1 || true
  return 0
}

flatpak_installed() { flatpak info "$1" >/dev/null 2>&1; }

install_flatpak() {  # install_flatpak APPID
  local id="$1"
  flatpak_installed "$id" && return 0
  flatpak install -y --noninteractive flathub "$id"
}

# =============================================================================
#  SNAP (optional fallback)
# =============================================================================
ensure_snap() {
  have_cmd snap && return 0
  case "$PM" in
    apt)    pm_install snapd ;;
    dnf)    pm_install snapd && systemctl enable --now snapd.socket 2>/dev/null && ln -sf /var/lib/snapd/snap /snap 2>/dev/null ;;
    zypper) warn "snap on openSUSE needs the snappy repo; skipping snap fallback"; return 1 ;;
    pacman) warn "snap on Arch is via AUR; skipping snap fallback"; return 1 ;;
  esac
  have_cmd snap
}

# =============================================================================
#  DESKTOP / WEB-APP SHORTCUTS
# =============================================================================
detect_browser() {
  local b
  for b in google-chrome google-chrome-stable chromium chromium-browser microsoft-edge brave-browser firefox; do
    have_cmd "$b" && { printf '%s' "$b"; return 0; }
  done
  # Flatpak browsers
  if flatpak_installed com.google.Chrome; then printf 'flatpak run com.google.Chrome'; return 0; fi
  if flatpak_installed org.chromium.Chromium; then printf 'flatpak run org.chromium.Chromium'; return 0; fi
  if flatpak_installed com.microsoft.Edge; then printf 'flatpak run com.microsoft.Edge'; return 0; fi
  return 1
}

webapp_desktop() {  # webapp_desktop "Name" "URL"
  local name="$1" url="$2" browser appdir desktop slug
  browser="$(detect_browser)" || { mark_manual "$name" "no browser found for web-app shortcut ($url)"; return 1; }
  slug="$(printf '%s' "$name" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-')"
  appdir="$TARGET_HOME/.local/share/applications"
  mkdir -p "$appdir"
  desktop="$appdir/webapp-$slug.desktop"
  {
    printf '[Desktop Entry]\n'
    printf 'Version=1.0\nType=Application\n'
    printf 'Name=%s\n' "$name"
    printf 'Exec=%s --app=%s\n' "$browser" "$url"
    printf 'Terminal=false\nCategories=Network;WebBrowser;\n'
  } > "$desktop"
  chown "$TARGET_USER":"$TARGET_USER" "$desktop" 2>/dev/null || true
  chmod +x "$desktop" 2>/dev/null || true
  mark_ok "$name" "web-app shortcut -> $url"
}

# =============================================================================
#  DIRECT DOWNLOADS (.deb / .rpm / AppImage)
# =============================================================================
DOWNLOAD_DIR="${DOWNLOAD_DIR:-/tmp/migrate_to_linux_downloads}"
mkdir -p "$DOWNLOAD_DIR" 2>/dev/null || true

download_file() {  # download_file URL OUTPATH
  local url="$1" out="$2"
  if have_cmd curl; then curl -fL --retry 3 -o "$out" "$url"
  elif have_cmd wget; then wget -O "$out" "$url"
  else err "neither curl nor wget available"; return 1; fi
}

install_local_package() {  # install_local_package FILE
  local f="$1"
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y "$f" || { dpkg -i "$f"; apt-get -f install -y; } ;;
    dnf)    dnf install -y "$f" ;;
    zypper) zypper --non-interactive install -y --allow-unsigned-rpm "$f" ;;
    pacman) pacman -U --noconfirm "$f" ;;
  esac
}

# =============================================================================
#  install_app  --  the multi-strategy, Flatpak-first dispatcher
# -----------------------------------------------------------------------------
#  Usage (emitted by the generator):
#    install_app --name "VLC" --method flatpak --flatpak org.videolan.VLC \
#                --apt vlc --dnf vlc --zypper vlc --pacman vlc \
#                --arch "x86_64 aarch64"
#  Methods: flatpak | native | snap | webapp | docker | wine-bottles |
#           deb-url | github-deb | manual
# =============================================================================
install_app() {
  local name="" method="" flatpak="" snap_pkg="" arch_list=""
  local apt="" dnf="" zypper="" pacman=""
  local url_x86="" url_arm="" webapp_url="" docker_image="" github_repo="" note=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --name)    name="$2"; shift 2 ;;
      --method)  method="$2"; shift 2 ;;
      --flatpak) flatpak="$2"; shift 2 ;;
      --snap)    snap_pkg="$2"; shift 2 ;;
      --apt)     apt="$2"; shift 2 ;;
      --dnf)     dnf="$2"; shift 2 ;;
      --zypper)  zypper="$2"; shift 2 ;;
      --pacman)  pacman="$2"; shift 2 ;;
      --arch)    arch_list="$2"; shift 2 ;;
      --url-x86) url_x86="$2"; shift 2 ;;
      --url-arm) url_arm="$2"; shift 2 ;;
      --webapp)  webapp_url="$2"; shift 2 ;;
      --docker)  docker_image="$2"; shift 2 ;;
      --github)  github_repo="$2"; shift 2 ;;
      --note)    note="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  [ -z "$name" ] && return 0

  if ! arch_supported "$arch_list"; then
    mark_skip "$name" "not available for $ARCH"
    return 0
  fi

  log "Installing: $name"
  [ -n "$note" ] && info "$note"

  # native package name for the running family
  local native_pkg=""
  case "$PM" in
    apt) native_pkg="$apt" ;; dnf) native_pkg="$dnf" ;;
    zypper) native_pkg="$zypper" ;; pacman) native_pkg="$pacman" ;;
  esac

  case "$method" in
    flatpak)
      if [ -n "$flatpak" ] && ensure_flatpak && install_flatpak "$flatpak"; then
        mark_ok "$name" "flatpak $flatpak"; return 0
      fi
      if [ -n "$native_pkg" ]; then
        pm_refresh
        if pm_install $native_pkg; then mark_ok "$name" "native $native_pkg (flatpak fell back)"; return 0; fi
      fi
      mark_fail "$name" "flatpak ${flatpak:-?} unavailable and no native fallback"
      ;;
    native)
      if [ -z "$native_pkg" ]; then
        if [ -n "$flatpak" ] && ensure_flatpak && install_flatpak "$flatpak"; then
          mark_ok "$name" "flatpak $flatpak (no native pkg for $PM)"; return 0
        fi
        mark_manual "$name" "no $PM package name known (needs review)"; return 0
      fi
      if pm_installed "${native_pkg%% *}"; then mark_skip "$name" "already installed"; return 0; fi
      pm_refresh
      if pm_install $native_pkg; then mark_ok "$name" "native $native_pkg"; return 0; fi
      if [ -n "$flatpak" ] && ensure_flatpak && install_flatpak "$flatpak"; then
        mark_ok "$name" "flatpak $flatpak (native failed)"; return 0
      fi
      mark_fail "$name" "native $native_pkg failed"
      ;;
    snap)
      if [ -n "$snap_pkg" ] && ensure_snap && snap install $snap_pkg; then
        mark_ok "$name" "snap $snap_pkg"; return 0
      fi
      if [ -n "$flatpak" ] && ensure_flatpak && install_flatpak "$flatpak"; then
        mark_ok "$name" "flatpak $flatpak (snap fell back)"; return 0
      fi
      mark_manual "$name" "snap unavailable on this distro"
      ;;
    webapp)
      webapp_desktop "$name" "$webapp_url"
      ;;
    docker)
      if ensure_docker; then
        if docker pull "$docker_image" >/dev/null 2>&1; then
          mark_ok "$name" "docker image pulled: $docker_image (run it yourself)"
        else mark_fail "$name" "docker pull $docker_image failed"; fi
      else mark_manual "$name" "install Docker, then: docker run $docker_image"; fi
      ;;
    wine-bottles)
      if ensure_flatpak && install_flatpak com.usebottles.bottles; then
        mark_ok "$name" "via Bottles (flatpak) - configure the Windows app inside Bottles"
      else mark_manual "$name" "install Bottles (flatpak) to run this Windows app"; fi
      ;;
    deb-url|github-deb)
      local url=""; [ "$ARCH" = "aarch64" ] && url="$url_arm" || url="$url_x86"
      if [ -z "$url" ]; then mark_manual "$name" "no download URL for $ARCH"; return 0; fi
      local f="$DOWNLOAD_DIR/${name// /_}.pkg"
      if download_file "$url" "$f" && install_local_package "$f"; then
        mark_ok "$name" "downloaded package"
      else mark_fail "$name" "download/install from $url failed"; fi
      ;;
    manual|*)
      local hint="$webapp_url$url_x86$github_repo"
      mark_manual "$name" "${note:-manual install}${hint:+ ($hint)}"
      ;;
  esac
}

ensure_docker() {
  have_cmd docker && return 0
  pm_refresh
  case "$PM" in
    apt)    pm_install docker.io ;;
    dnf)    pm_install moby-engine || pm_install docker ;;
    zypper) pm_install docker ;;
    pacman) pm_install docker ;;
  esac
  have_cmd docker && systemctl enable --now docker 2>/dev/null
  have_cmd docker
}


main() {
  require_root
  detect_distro
  detect_arch
  log "Migrate to Linux  --  Run All"
  info "Distribution : ${DISTRO_NAME}"
  info "Family / pm  : ${FAMILY} / ${PM}"
  info "Architecture : ${ARCH}"

  local here; here="$(cd "$(dirname "$0")" && pwd)"
  local step
  for step in install_device_drivers.sh install_must_have_software.sh apply_settings.sh; do
    if [ -f "$here/$step" ]; then
      log "=== Running $step ==="
      bash "$here/$step" || warn "$step reported errors (continuing)"
    else
      warn "missing: $step"
    fi
  done

  # Optional Docker rebuild. docker_rebuild.sh is only present when Docker was
  # installed on the Windows source (docker_discovery created it), so the prompt
  # is only shown in that case.
  if [ -f "$here/docker_rebuild.sh" ]; then
    printf '\n'
    local ans=""
    read -r -p "Rebuild docker components? (y/n): " ans </dev/tty 2>/dev/null || ans="n"
    case "$ans" in
      [Yy]*) log "=== Running docker_rebuild.sh ==="
             bash "$here/docker_rebuild.sh" || warn "docker_rebuild.sh reported errors" ;;
      *)     info "Skipping docker rebuild." ;;
    esac
  fi

  log "All steps finished."
  info "Per-step logs are under /tmp/migrate_to_linux_results.tsv (last step wins)."
}

main "$@"
