#!/usr/bin/env bash
# =============================================================================
#  execute_all.sh
#  GENERATED by submodules/D_compile_and_generate_shell_script.ps1 -- do not edit.
#
#  Single entry point. Asks the stage questions UP FRONT (each question and its
#  options are shown), runs the chosen stages UNATTENDED in this order:
#    drivers -> config settings -> applications -> manual downloads -> docker
#  Manual downloads place each file, then 'done'/'skip'; docker rebuild is optional.
#  Usage:  sudo ./execute_all.sh
# =============================================================================
# =============================================================================
#  _common.sh  --  universal runtime engine for the generated installer scripts
# -----------------------------------------------------------------------------
#  This file is INLINED into every generated script in "Execute on Linux!/" by
#  submodules/D_compile_and_generate_shell_script.ps1.  It is distro- and
#  architecture-agnostic: it detects the running distro FAMILY (apt/dnf/zypper/
#  pacman) and CPU ARCH at runtime, then dispatches installs accordingly.
#
#  Design: Flatpak-first.  GUI apps come from Flathub (identical app id on every
#  distro).  The native package manager is used only for the irreducible base
#  (installing Flatpak itself, CLI/dev tools, drivers, system bits).
# =============================================================================

# Be strict but survivable: we handle per-app failures ourselves, so do not let
# a single failing install abort the whole run.
set -o pipefail

# ----------------------------- pretty output ---------------------------------
# All human-facing chatter goes to fd 3 (stdout) so command output can be hidden.
exec 3>&1
log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*" >&3; }
info() { printf '       %s\n' "$*" >&3; }
ok()   { printf '       \033[32m%s\033[0m\n' "$*" >&3; }
warn() { printf '       \033[1;33m%s\033[0m\n' "$*" >&3; }
err()  { printf '\033[1;31m%s\033[0m\n' "$*" >&3; }

have_cmd() { command -v "$1" >/dev/null 2>&1; }

# Filesystem-safe slug from an app name. execute_all.sh stages user-supplied
# files for "manual" apps under $MIGRATE_MANUAL_DIR/<slug>/ using the SAME slug.
slugify() { printf '%s' "$1" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-_'; }

# ----------------------------- bookkeeping -----------------------------------
RESULTS="${RESULTS:-/tmp/migrate_to_linux_results.tsv}"
# execute_all sets MIGRATE_KEEP_RESULTS so the per-stage child scripts APPEND to one
# shared log instead of truncating it, which lets execute_all print a combined
# summary of every operation at the very end. Run standalone, a script truncates.
if [ -z "${MIGRATE_KEEP_RESULTS:-}" ]; then
  : > "$RESULTS" 2>/dev/null || RESULTS="$(mktemp)"
fi
declare -a OK_LIST=() SKIP_LIST=() FAIL_LIST=() FAIL_REASON=() MANUAL_LIST=()

# LAST_ERR holds the 1-line reason from the most recent captured command failure.
LAST_ERR=""

# Run a command, show its output, and on failure capture the last output line into
# LAST_ERR (a 1-line error reason). stdin stays attached, so interactive installers
# still work. Returns the command's real exit code.
capture() {
  local rc tmp; tmp="$(mktemp 2>/dev/null || echo /tmp/mtl_cap.$$)"
  "$@" 2>&1 | tee "$tmp" >&3
  rc=${PIPESTATUS[0]}
  LAST_ERR=""
  if [ "$rc" -ne 0 ]; then
    LAST_ERR="$(grep -v '^[[:space:]]*$' "$tmp" 2>/dev/null | tail -n 1)"
    [ -z "$LAST_ERR" ] && LAST_ERR="exit code $rc"
  fi
  rm -f "$tmp" 2>/dev/null || true
  return "$rc"
}

# MODULE tags which big module (Drivers / Config settings / Applications) each result
# belongs to, so execute_all can print a per-module classified summary at the end.
MODULE="${MODULE:-General}"
record_line() { printf '%s\t%s\t%-6s\t%s\t%s\n' "$(date '+%F %T')" "${MODULE:-General}" "$1" "$2" "${3:-}" >> "$RESULTS"; }
mark_ok()     { OK_LIST+=("$1");     record_line OK     "$1" "${2:-}"; ok "installed: $1"; }
mark_skip()   { SKIP_LIST+=("$1");   record_line SKIP   "$1" "${2:-}"; info "skipped: $1 (${2:-already present})"; }
mark_fail()   { FAIL_LIST+=("$1"); FAIL_REASON+=("${2:-unknown error}"); record_line FAIL "$1" "${2:-}"; err "failed: $1 ${2:+- $2}"; }
mark_manual() { MANUAL_LIST+=("$1"); record_line MANUAL "$1" "${2:-}"; warn "manual step required: $1 ${2:+- $2}"; }

print_summary() {
  # When orchestrated by execute_all, it prints ONE combined, classified summary at
  # the very end; suppress the per-stage summary here to avoid mid-run clutter.
  [ -n "${MIGRATE_KEEP_RESULTS:-}" ] && return 0
  log "Summary"
  info "OK:     ${#OK_LIST[@]}"
  info "Skip:   ${#SKIP_LIST[@]}"
  info "Manual: ${#MANUAL_LIST[@]}"
  info "Failed: ${#FAIL_LIST[@]}"
  if [ "${#FAIL_LIST[@]}" -gt 0 ]; then
    warn "Failures (1-line reason each):"
    for i in "${!FAIL_LIST[@]}"; do err "  - ${FAIL_LIST[$i]}: ${FAIL_REASON[$i]}"; done
  fi
  if [ "${#MANUAL_LIST[@]}" -gt 0 ]; then
    warn "Need a manual step:"; for i in "${MANUAL_LIST[@]}"; do info "  - $i"; done
  fi
  info "Full log: $RESULTS"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root.  Try:  sudo $0"
    exit 1
  fi
}

# The non-root user we should install Flatpak apps / write desktop files for,
# even though the script itself runs under sudo.
TARGET_USER="${SUDO_USER:-$(id -un)}"
TARGET_HOME="$(getent passwd "$TARGET_USER" 2>/dev/null | cut -d: -f6)"
[ -z "$TARGET_HOME" ] && TARGET_HOME="$HOME"

# =============================================================================
#  DISTRO + ARCHITECTURE DETECTION
# =============================================================================
FAMILY=""      # debian | rhel | suse | arch
PM=""          # apt | dnf | zypper | pacman
DISTRO_ID=""
DISTRO_NAME=""

detect_distro() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    DISTRO_ID="${ID:-}"
    DISTRO_NAME="${PRETTY_NAME:-${NAME:-$ID}}"
  fi
  local hay=" ${DISTRO_ID} ${ID_LIKE:-} "
  case "$hay" in
    *" debian "*|*" ubuntu "*|*" linuxmint "*|*" pop "*|*" zorin "*|*" elementary "*) FAMILY="debian"; PM="apt" ;;
    *" rhel "*|*" fedora "*|*" centos "*|*" rocky "*|*" almalinux "*|*" ol "*) FAMILY="rhel"; PM="dnf" ;;
    *" suse "*|*" opensuse "*|*" sles "*|*" sled "*) FAMILY="suse"; PM="zypper" ;;
    *" arch "*|*" archlinux "*|*" manjaro "*|*" endeavouros "*) FAMILY="arch"; PM="pacman" ;;
    *)
      # Fall back to whichever package manager actually exists.
      if   have_cmd apt-get; then FAMILY="debian"; PM="apt"
      elif have_cmd dnf;     then FAMILY="rhel";   PM="dnf"
      elif have_cmd zypper;  then FAMILY="suse";   PM="zypper"
      elif have_cmd pacman;  then FAMILY="arch";   PM="pacman"
      else err "Unsupported distribution: could not find apt/dnf/zypper/pacman."; exit 1
      fi ;;
  esac
}

ARCH=""        # x86_64 | aarch64 | armhf | other
detect_arch() {
  local m; m="$(uname -m)"
  case "$m" in
    x86_64|amd64)        ARCH="x86_64" ;;
    aarch64|arm64)       ARCH="aarch64" ;;
    armv7l|armhf|armv6l) ARCH="armhf" ;;
    *)                   ARCH="$m" ;;
  esac
}

# arch_supported "x86_64 aarch64"  ->  true if $ARCH is listed (empty list = all)
arch_supported() {
  local list="$1"
  [ -z "$list" ] && return 0
  case " $list " in *" $ARCH "*) return 0 ;; *) return 1 ;; esac
}

# =============================================================================
#  PACKAGE-MANAGER ABSTRACTION
# =============================================================================
_PM_REFRESHED=0
pm_refresh() {
  [ "$_PM_REFRESHED" = "1" ] && return 0
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get update -y ;;
    dnf)    dnf -y makecache ;;
    zypper) zypper --non-interactive refresh ;;
    pacman) pacman -Sy --noconfirm ;;
  esac
  _PM_REFRESHED=1
}

pm_install() {
  [ "$#" -eq 0 ] && return 0
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "$@" ;;
    dnf)    dnf install -y "$@" ;;
    zypper) zypper --non-interactive install -y --no-recommends "$@" ;;
    pacman) pacman -S --noconfirm --needed "$@" ;;
  esac
}

pm_installed() {
  case "$PM" in
    apt)    dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed" ;;
    dnf)    rpm -q "$1" >/dev/null 2>&1 ;;
    zypper) rpm -q "$1" >/dev/null 2>&1 ;;
    pacman) pacman -Q "$1" >/dev/null 2>&1 ;;
  esac
}

# =============================================================================
#  FLATPAK (universal app layer)
# =============================================================================
ensure_flatpak() {
  if ! have_cmd flatpak; then
    log "Installing Flatpak (required for the universal app layer)"
    pm_refresh
    pm_install flatpak || { mark_fail "flatpak" "could not install flatpak via $PM"; return 1; }
  fi
  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo >/dev/null 2>&1 || true
  return 0
}

flatpak_installed() { flatpak info "$1" >/dev/null 2>&1; }

install_flatpak() {  # install_flatpak APPID
  local id="$1"
  if flatpak_installed "$id"; then
    # Already present: update it if the user asked to update existing apps.
    [ "${MIGRATE_UPDATE_EXISTING:-no}" = "yes" ] && flatpak update -y --noninteractive "$id"
    return 0
  fi
  flatpak install -y --noninteractive flathub "$id"
}

# =============================================================================
#  SNAP (optional fallback)
# =============================================================================
ensure_snap() {
  have_cmd snap && return 0
  case "$PM" in
    apt)    pm_install snapd ;;
    dnf)    pm_install snapd && systemctl enable --now snapd.socket 2>/dev/null && ln -sf /var/lib/snapd/snap /snap 2>/dev/null ;;
    zypper) warn "snap on openSUSE needs the snappy repo; skipping snap fallback"; return 1 ;;
    pacman) warn "snap on Arch is via AUR; skipping snap fallback"; return 1 ;;
  esac
  have_cmd snap
}

# =============================================================================
#  DESKTOP / WEB-APP SHORTCUTS
# =============================================================================
detect_browser() {
  local b
  for b in google-chrome google-chrome-stable chromium chromium-browser microsoft-edge brave-browser firefox; do
    have_cmd "$b" && { printf '%s' "$b"; return 0; }
  done
  # Flatpak browsers
  if flatpak_installed com.google.Chrome; then printf 'flatpak run com.google.Chrome'; return 0; fi
  if flatpak_installed org.chromium.Chromium; then printf 'flatpak run org.chromium.Chromium'; return 0; fi
  if flatpak_installed com.microsoft.Edge; then printf 'flatpak run com.microsoft.Edge'; return 0; fi
  return 1
}

webapp_desktop() {  # webapp_desktop "Name" "URL"
  local name="$1" url="$2" browser appdir desktop slug
  browser="$(detect_browser)" || { mark_manual "$name" "no browser found for web-app shortcut ($url)"; return 1; }
  slug="$(printf '%s' "$name" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-')"
  appdir="$TARGET_HOME/.local/share/applications"
  mkdir -p "$appdir"
  desktop="$appdir/webapp-$slug.desktop"
  {
    printf '[Desktop Entry]\n'
    printf 'Version=1.0\nType=Application\n'
    printf 'Name=%s\n' "$name"
    printf 'Exec=%s --app=%s\n' "$browser" "$url"
    printf 'Terminal=false\nCategories=Network;WebBrowser;\n'
  } > "$desktop"
  chown "$TARGET_USER":"$TARGET_USER" "$desktop" 2>/dev/null || true
  chmod +x "$desktop" 2>/dev/null || true
  mark_ok "$name" "web-app shortcut -> $url"
}

# =============================================================================
#  DIRECT DOWNLOADS (.deb / .rpm / AppImage)
# =============================================================================
DOWNLOAD_DIR="${DOWNLOAD_DIR:-/tmp/migrate_to_linux_downloads}"
mkdir -p "$DOWNLOAD_DIR" 2>/dev/null || true

download_file() {  # download_file URL OUTPATH
  local url="$1" out="$2"
  if have_cmd curl; then curl -fL --retry 3 -o "$out" "$url"
  elif have_cmd wget; then wget -O "$out" "$url"
  else err "neither curl nor wget available"; return 1; fi
}

install_local_package() {  # install_local_package FILE
  local f="$1"
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y "$f" || { dpkg -i "$f"; apt-get -f install -y; } ;;
    dnf)    dnf install -y "$f" ;;
    zypper) zypper --non-interactive install -y --allow-unsigned-rpm "$f" ;;
    pacman) pacman -U --noconfirm "$f" ;;
  esac
}

# Best-effort install of a package matching a specific (Windows) version. Tries the
# major-version package name and an exact version pin. Returns 0 on success, 1 if no
# matching version could be installed (caller then falls back to latest). pacman is
# rolling-release, so version pinning is not supported there.
install_native_version() {  # install_native_version PKG WINVER
  local pkg="$1" ver="$2" major
  major="$(printf '%s' "$ver" | grep -oE '[0-9]+' | head -n1)"
  [ -z "$major" ] && return 1
  case "$PM" in
    apt)    capture pm_install "${pkg}-${major}" || capture pm_install "${pkg}=${ver}" ;;
    dnf)    capture pm_install "${pkg}${major}" || capture pm_install "${pkg}-${major}" || capture pm_install "${pkg}-${ver}" ;;
    zypper) capture pm_install "${pkg}${major}" || capture pm_install "${pkg}-${ver}" ;;
    pacman) return 1 ;;
  esac
}

# =============================================================================
#  install_app  --  the multi-strategy, Flatpak-first dispatcher
# -----------------------------------------------------------------------------
#  Usage (emitted by the generator):
#    install_app --name "VLC" --method flatpak --flatpak org.videolan.VLC \
#                --apt vlc --dnf vlc --zypper vlc --pacman vlc \
#                --arch "x86_64 aarch64"
#  Methods: flatpak | native | snap | webapp | docker | wine-bottles |
#           deb-url | github-deb | manual
# =============================================================================
install_app() {
  local name="" alt="" method="" flatpak="" snap_pkg="" arch_list="" winver="" is_security=0 is_paid=0
  local apt="" dnf="" zypper="" pacman=""
  local url_x86="" url_arm="" webapp_url="" docker_image="" github_repo="" note=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --name)    name="$2"; shift 2 ;;
      --alt)     alt="$2"; shift 2 ;;
      --method)  method="$2"; shift 2 ;;
      --flatpak) flatpak="$2"; shift 2 ;;
      --snap)    snap_pkg="$2"; shift 2 ;;
      --apt)     apt="$2"; shift 2 ;;
      --dnf)     dnf="$2"; shift 2 ;;
      --zypper)  zypper="$2"; shift 2 ;;
      --pacman)  pacman="$2"; shift 2 ;;
      --arch)    arch_list="$2"; shift 2 ;;
      --winver)  winver="$2"; shift 2 ;;
      --url-x86) url_x86="$2"; shift 2 ;;
      --url-arm) url_arm="$2"; shift 2 ;;
      --webapp)  webapp_url="$2"; shift 2 ;;
      --docker)  docker_image="$2"; shift 2 ;;
      --github)  github_repo="$2"; shift 2 ;;
      --note)     note="$2"; shift 2 ;;
      --security) is_security=1; shift ;;
      --paid)     is_paid=1; shift ;;
      *) shift ;;
    esac
  done
  [ -z "$name" ] && return 0

  # Security-suite equivalents (antivirus/firewall, etc.) are only installed when the
  # user opted in; many skip them because Linux is hardened by default.
  if [ "$is_security" -eq 1 ] && [ "${MIGRATE_INSTALL_SECURITY:-no}" != "yes" ]; then
    mark_skip "$name" "security suite - not installed (opted out)"
    return 0
  fi

  # Free-only mode: this app's only alternative is paid. Ask whether to proceed.
  if [ "${MIGRATE_FREE_ONLY:-no}" = "yes" ] && [ "$is_paid" -eq 1 ]; then
    local _fans=""
    if [ -r /dev/tty ]; then
      printf '\n\n\033[1;33m==> %s%s has no free alternative.\033[0m\n' "$name" "${alt:+ ---> $alt}" >&3
      printf '  No free alternative exists for this application. Do you want to continue with the installation of the paid one? Answering with No means skipping this application (y/n): ' > /dev/tty
      read -r _fans < /dev/tty || _fans="n"
      case "$_fans" in [Yy]*) ;; *) mark_skip "$name" "paid - skipped (free-only mode)"; return 0 ;; esac
    else
      mark_skip "$name" "paid - skipped (free-only mode)"; return 0
    fi
  fi

  if ! arch_supported "$arch_list"; then
    mark_skip "$name" "not available for $ARCH"
    return 0
  fi

  if [ -n "$alt" ]; then
    printf '\n\n\033[1;34m==> Installing: %s   --->   %s\033[0m\n' "$name" "$alt" >&3
  else
    printf '\n\n\033[1;34m==> Installing: %s\033[0m\n' "$name" >&3
  fi
  [ -n "$note" ] && info "$note"

  # native package name for the running family
  local native_pkg=""
  case "$PM" in
    apt) native_pkg="$apt" ;; dnf) native_pkg="$dnf" ;;
    zypper) native_pkg="$zypper" ;; pacman) native_pkg="$pacman" ;;
  esac
  local slug; slug="$(slugify "$name")"

  # ---- single-path methods ----
  case "$method" in
    webapp)
      webapp_desktop "$name" "$webapp_url"; return 0 ;;
    docker)
      if ensure_docker && capture docker pull "$docker_image"; then
        mark_ok "$name" "docker image pulled: $docker_image (run it yourself)"
      else mark_fail "$name" "${LAST_ERR:-could not pull docker image $docker_image}"; fi
      return 0 ;;
    wine-bottles)
      if ensure_flatpak && capture install_flatpak com.usebottles.bottles; then
        mark_ok "$name" "via Bottles (flatpak) - configure the Windows app inside Bottles"
      else mark_fail "$name" "${LAST_ERR:-could not install Bottles (flatpak)}"; fi
      return 0 ;;
    manual)
      local mdir="${MIGRATE_MANUAL_DIR:-$DOWNLOAD_DIR/manual}/$slug" mf got=0
      if [ -d "$mdir" ] && [ -n "$(ls -A "$mdir" 2>/dev/null)" ]; then
        for mf in "$mdir"/*; do [ -f "$mf" ] && install_by_ext "$mf" && got=1; done
        if [ "$got" -eq 1 ]; then mark_ok "$name" "installed from staged file"
        else mark_fail "$name" "${LAST_ERR:-staged file could not be installed}"; fi
      else
        mark_manual "$name" "${note:-manual install}"
      fi
      return 0 ;;
  esac

  # Universal "already installed" short-circuit. Unless the user asked to update
  # existing apps to the LATEST version, an app that is already present is skipped
  # entirely here -- BEFORE any vendor repo setup or download happens. This applies
  # when "same version" was chosen OR when existing apps are not being updated.
  if [ "${MIGRATE_VERSION_MODE:-latest}" = "same" ] || [ "${MIGRATE_UPDATE_EXISTING:-no}" != "yes" ]; then
    if { [ -n "$native_pkg" ] && pm_installed "${native_pkg%% *}"; } \
       || { [ -n "$flatpak" ] && have_cmd flatpak && flatpak_installed "$flatpak"; } \
       || { [ -n "$snap_pkg" ] && have_cmd snap && snap list "${snap_pkg%% *}" >/dev/null 2>&1; }; then
      mark_skip "$name" "already installed"
      return 0
    fi
  fi

  # ---- multi-backend methods (req: try every available pm until one works) ----
  # The declared method goes first; then EVERY other available backend is tried as a
  # fallback (native / flatpak / snap / direct-download) before the app is failed.
  local order
  case "$method" in
    flatpak)            order="flatpak native snap deburl" ;;
    native)             order="native flatpak snap deburl" ;;
    snap)               order="snap flatpak native deburl" ;;
    deb-url|github-deb) order="deburl native flatpak snap" ;;
    *)                  order="flatpak native snap deburl" ;;
  esac

  local b url f rfn
  LAST_ERR=""   # so an empty value after the loop means "nothing was even attempted"
  for b in $order; do
    case "$b" in
      flatpak)
        [ -n "$flatpak" ] || continue
        ensure_flatpak || continue
        if capture install_flatpak "$flatpak"; then mark_ok "$name" "flatpak $flatpak"; return 0; fi ;;
      native)
        [ -n "$native_pkg" ] || continue
        # vendor's own repo first, for the latest upstream build (if defined).
        rfn="repo_setup_$(printf '%s' "$slug" | tr '-' '_')"
        if declare -F "$rfn" >/dev/null 2>&1; then
          info "configuring vendor repository for $name ..."
          "$rfn" || warn "vendor repo setup failed; falling back to the distro repo"
        fi
        pm_refresh
        # Skip if present, UNLESS the user asked to update existing apps (then
        # pm_install upgrades it to the latest available).
        if pm_installed "${native_pkg%% *}" && [ "${MIGRATE_UPDATE_EXISTING:-no}" != "yes" ]; then
          mark_skip "$name" "already installed"; return 0
        fi
        # match the Windows version when the user chose "same version".
        if [ "${MIGRATE_VERSION_MODE:-latest}" = "same" ] && [ -n "$winver" ]; then
          if install_native_version "$native_pkg" "$winver"; then mark_ok "$name" "native $native_pkg (matched Windows $winver)"; return 0; fi
          warn "could not match Windows version $winver; installing latest"
        fi
        if capture pm_install $native_pkg; then mark_ok "$name" "native $native_pkg"; return 0; fi ;;
      snap)
        [ -n "$snap_pkg" ] || continue
        ensure_snap || continue
        if capture snap install $snap_pkg; then mark_ok "$name" "snap $snap_pkg"; return 0; fi ;;
      deburl)
        [ -n "$url_x86$url_arm" ] || continue
        url="$url_x86"; [ "$ARCH" = "aarch64" ] && [ -n "$url_arm" ] && url="$url_arm"
        [ -n "$url" ] || continue
        f="$DOWNLOAD_DIR/${name// /_}.pkg"
        if capture download_file "$url" "$f" && capture install_local_package "$f"; then mark_ok "$name" "downloaded package"; return 0; fi ;;
    esac
  done

  # A real install error -> report failure. But if nothing was even attempted (no
  # package-manager route on this distro), show that and fall back to the manual
  # download-by-user scheme (place the file, then done/skip, handled by extension).
  if [ -n "$LAST_ERR" ]; then
    mark_fail "$name" "$LAST_ERR"
  else
    err "no available package manager could install it"
    manual_fallback "$name" "$alt" "$note" "$webapp_url$url_x86$github_repo"
  fi
}

# Manual download-by-user fallback for an app no package manager could install.
# Prompts the user to download + place the installer; handles it by extension; loops
# until a valid file is placed ('done') or the user skips. Marks the result.
manual_fallback() {  # manual_fallback NAME [ALT] [NOTE] [URL]
  local name="$1" alt="$2" mnote="$3" murl="$4"
  local base="${MIGRATE_MANUAL_DIR:-$DOWNLOAD_DIR/manual}"
  local slug dir ans f got
  slug="$(slugify "$name")"; dir="$base/$slug"; mkdir -p "$dir"
  [ -n "$mnote" ] && info "$mnote"
  [ -n "$murl" ] && info "More info / download: $murl"
  info "Download the installer yourself and place it (keep its original file name) in:"
  info "    $dir"
  info "Then type 'done' (handled by extension: .deb/.rpm/.sh/.run/.bin/.bundle/.AppImage/.tar.gz/.zip/...); 'skip' to skip."
  if [ ! -r /dev/tty ]; then mark_manual "$name" "no package manager route - needs manual download"; return 0; fi
  while :; do
    printf '  %s (done/skip): ' "$name" > /dev/tty
    read -r ans < /dev/tty || ans="skip"
    case "$ans" in
      [Ss]|[Ss][Kk][Ii][Pp]) mark_skip "$name" "user skipped"; return 0 ;;
      [Dd]|[Dd][Oo][Nn][Ee])
        if [ -z "$(ls -A "$dir" 2>/dev/null)" ]; then
          printf '\033[1;31m  No file found in %s -- place the file there, then type done (or skip).\033[0m\n' "$dir" > /dev/tty; continue
        fi
        got=0; LAST_ERR=""
        for f in "$dir"/*; do [ -f "$f" ] || continue; install_by_ext "$f" && got=1; done
        if [ "$got" -eq 1 ]; then mark_ok "$name" "installed from $dir"; return 0
        else printf '\033[1;31m  %s -- fix the file in %s, then type done (or skip).\033[0m\n' "${LAST_ERR:-could not handle the file}" "$dir" > /dev/tty; fi
        ;;
      *) printf '\033[1;31m  Please type "done" or "skip".\033[0m\n' > /dev/tty ;;
    esac
  done
}

# Install the Nth-best alternative of an app only if the user asked for at least
# N alternatives (MIGRATE_ALT_LIMIT, default 1). Usage:  app_alt RANK install_app ...
app_alt() {
  local rank="$1"; shift
  local limit="${MIGRATE_ALT_LIMIT:-1}"
  case "$limit" in ''|*[!0-9]*) limit=1 ;; esac
  if [ "$rank" -le "$limit" ]; then "$@"; fi
  return 0
}

# Handle a user-downloaded installer FILE according to its extension. Returns 0 on
# success, 1 on failure (LAST_ERR holds a 1-line reason). Used by the manual phase.
install_by_ext() {  # install_by_ext FILE
  local f="$1"
  case "$f" in
    *.deb|*.rpm|*.pkg.tar.zst|*.pkg.tar.xz|*.pkg.tar)
      capture install_local_package "$f" ;;
    *.sh)
      chmod +x "$f" 2>/dev/null; capture bash "$f" ;;
    *.run|*.bin|*.bundle)
      chmod +x "$f" 2>/dev/null; capture "$f" ;;
    *.appimage|*.AppImage)
      chmod +x "$f" 2>/dev/null
      mkdir -p /opt/migrate_appimages
      if cp -f "$f" /opt/migrate_appimages/ 2>/dev/null; then return 0
      else LAST_ERR="could not place AppImage in /opt/migrate_appimages"; return 1; fi ;;
    *.tar.gz|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar)
      mkdir -p "${f%/*}/extracted"
      capture tar -xf "$f" -C "${f%/*}/extracted" ;;
    *.zip)
      if ! have_cmd unzip; then LAST_ERR="unzip is not installed"; return 1; fi
      mkdir -p "${f%/*}/extracted"
      capture unzip -o "$f" -d "${f%/*}/extracted" ;;
    *)
      LAST_ERR="unsupported file type: .${f##*.}"; return 1 ;;
  esac
}

ensure_docker() {
  have_cmd docker && return 0
  pm_refresh
  case "$PM" in
    apt)    pm_install docker.io ;;
    dnf)    pm_install moby-engine || pm_install docker ;;
    zypper) pm_install docker ;;
    pacman) pm_install docker ;;
  esac
  have_cmd docker && systemctl enable --now docker 2>/dev/null
  have_cmd docker
}


# Manual-download apps with no automatic installer (format: "Windows app|hint").
# Handled at the very END so they never block the unattended stages.
MANUAL_APPS=(
  "Anaconda3|Anaconda (Linux)|Download the Anaconda installer .sh and run it|https://www.anaconda.com/download|0"
  "ChemDraw / ChemOffice|MarvinSketch (MarvinSuite)|MarvinSuite from chemaxon.com|https://chemaxon.com/products/marvin/download|0"
  "Foxit PDF Reader / Editor|Foxit PDF Reader (Linux)|Foxit Reader for Linux (.run installer)|https://www.foxit.com/pdf-reader/|0"
  "Gurobi|Gurobi (Linux)|Gurobi Optimizer (academic/commercial) from gurobi.com|https://www.gurobi.com/downloads/gurobi-software/|1"
  "Mathcad / PTC Mathcad Prime|SMath Studio|SMath Studio (free) from smath.com|https://en.smath.com/view/SMathStudio/summary|0"
  "Microsoft Project|ProjectLibre|ProjectLibre (.deb/.rpm) from projectlibre.com|https://www.projectlibre.com/product/projectlibre-open-source/|0"
  "PaperCut Print Deploy Client|PaperCut Print Deploy (Linux)|PaperCut Print Deploy client from your print server's portal|https://www.papercut.com/products/ng/print-deploy/|1"
  "RealVNC Viewer|RealVNC Viewer (Linux)|RealVNC Viewer (.deb/.rpm)|https://www.realvnc.com/en/connect/download/viewer/|0"
  "RStudio|RStudio (Linux)|RStudio Desktop (.deb/.rpm) from posit.co|https://posit.co/download/rstudio-desktop/|0"
  "Rufus|Ventoy|Ventoy from ventoy.net; GUI alt: 'popsicle'|https://www.ventoy.net/en/download.html|0"
  "SpotPlayer|SpotPlayer (Linux)|SpotPlayer (Sib) Linux build from sibm[a].ir|https://www.sibmaster.ir/|0"
  "VMware Workstation|VMware Workstation Pro (Linux)|VMware Workstation Pro .bundle (free for personal use)|https://www.vmware.com/products/workstation-pro.html|0"
  "WindTerm|WindTerm (Linux)|WindTerm from GitHub releases|https://github.com/kingToolbox/WindTerm/releases|0"
)

here=""

# Yes/No question. The question text AND (y/n) are always printed to the terminal.
ask() {  # ask "Question text" [default y|n]   -> 0 = yes, 1 = no
  local q="$1" def="${2:-y}" ans
  if [ ! -r /dev/tty ]; then case "$def" in [Yy]*) return 0 ;; *) return 1 ;; esac; fi
  while :; do
    printf '  %s (y/n): ' "$q" > /dev/tty
    if ! read -r ans < /dev/tty; then case "$def" in [Yy]*) return 0 ;; *) return 1 ;; esac; fi
    case "$ans" in
      [Yy]|[Yy][Ee][Ss]) return 0 ;;
      [Nn]|[Nn][Oo])     return 1 ;;
      *) printf '\033[1;31m  Please answer y or n.\033[0m\n' > /dev/tty ;;
    esac
  done
}

# Numeric question. Prints the question text, reads a whole number (>= 0).
# Echoes the chosen number on stdout.
ask_number() {  # ask_number "Question text" [default]
  local q="$1" def="${2:-1}" ans
  if [ ! -r /dev/tty ]; then printf '%s' "$def"; return 0; fi
  while :; do
    printf '  %s ' "$q" > /dev/tty
    if ! read -r ans < /dev/tty; then printf '%s' "$def"; return 0; fi
    [ -z "$ans" ] && ans="$def"
    case "$ans" in
      *[!0-9]*) printf '\033[1;31m  Please enter a whole number.\033[0m\n' > /dev/tty ;;
      *)        printf '%s' "$ans"; return 0 ;;
    esac
  done
}

# Two-choice (a/b) question. Shows the question and both labelled options, reads a/b,
# and echoes "same" for a or "latest" for b (default latest when no terminal).
ask_ab() {  # ask_ab "Question" "Option a label" "Option b label"
  local q="$1" la="$2" lb="$3" ans
  if [ ! -r /dev/tty ]; then printf 'latest'; return 0; fi
  printf '\n  %s\n' "$q"  > /dev/tty
  printf '    a. %s\n' "$la" > /dev/tty
  printf '    b. %s\n' "$lb" > /dev/tty
  while :; do
    printf '  Choose (a/b): ' > /dev/tty
    if ! read -r ans < /dev/tty; then printf 'latest'; return 0; fi
    case "$ans" in
      [Aa]) printf 'same';   return 0 ;;
      [Bb]) printf 'latest'; return 0 ;;
      *)    printf '\033[1;31m  Please answer a or b.\033[0m\n' > /dev/tty ;;
    esac
  done
}

# Display a saved config file as question/answer lines.
show_config() {  # show_config CONFIG_FILE
  local cfg="$1" k v label
  printf '\n'; log "Reading from the config file $cfg:"
  while IFS='=' read -r k v; do
    case "$k" in \#*|'') continue ;; esac
    v="${v%%#*}"; v="$(printf '%s' "$v" | tr -d '[:space:]')"
    case "$k" in
      INSTALL_DRIVERS)   label="Install device drivers?" ;;
      INSTALL_APPS)      label="Install must-have software?" ;;
      BEST_ALTERNATIVES) label="How many best alternatives of an application to install?" ;;
      VERSION_MODE)      label="Version of exact equivalents (same/latest)?" ;;
      UPDATE_EXISTING)   label="Update apps already installed on Linux?" ;;
      INSTALL_SECURITY)  label="Install security-suite equivalents?" ;;
      FREE_ONLY)         label="Only install free applications (skip paid)?" ;;
      APPLY_SETTINGS)    label="Apply Windows settings?" ;;
      REBUILD_DOCKER)    label="Rebuild docker components?" ;;
      *) continue ;;
    esac
    info "$label  $v"
  done < "$cfg"
}

# Apply a saved config: set do_* (caller's vars via dynamic scope) + MIGRATE_* env.
load_config() {  # load_config CONFIG_FILE
  local cfg="$1" k v
  while IFS='=' read -r k v; do
    case "$k" in \#*|'') continue ;; esac
    v="${v%%#*}"; v="$(printf '%s' "$v" | tr -d '[:space:]')"
    case "$k" in
      INSTALL_DRIVERS)   [ "$v" = y ] && do_drivers=1  || do_drivers=0 ;;
      INSTALL_APPS)      [ "$v" = y ] && do_apps=1     || do_apps=0 ;;
      BEST_ALTERNATIVES) MIGRATE_ALT_LIMIT="$v" ;;
      VERSION_MODE)      MIGRATE_VERSION_MODE="$v" ;;
      UPDATE_EXISTING)   [ "$v" = y ] && MIGRATE_UPDATE_EXISTING=yes  || MIGRATE_UPDATE_EXISTING=no ;;
      INSTALL_SECURITY)  [ "$v" = y ] && MIGRATE_INSTALL_SECURITY=yes || MIGRATE_INSTALL_SECURITY=no ;;
      FREE_ONLY)         [ "$v" = y ] && MIGRATE_FREE_ONLY=yes        || MIGRATE_FREE_ONLY=no ;;
      APPLY_SETTINGS)    [ "$v" = y ] && do_settings=1 || do_settings=0 ;;
      REBUILD_DOCKER)    [ "$v" = y ] && do_docker=1   || do_docker=0 ;;
    esac
  done < "$cfg"
  : "${MIGRATE_ALT_LIMIT:=1}"; : "${MIGRATE_VERSION_MODE:=latest}"
  : "${MIGRATE_UPDATE_EXISTING:=no}"; : "${MIGRATE_INSTALL_SECURITY:=no}"; : "${MIGRATE_FREE_ONLY:=no}"
  export MIGRATE_ALT_LIMIT MIGRATE_VERSION_MODE MIGRATE_UPDATE_EXISTING MIGRATE_INSTALL_SECURITY MIGRATE_FREE_ONLY
  # docker rebuild only if a snapshot actually shipped with the installer
  [ -f "$here/submodules/docker_rebuild.sh" ] || do_docker=0
}

run_stage() {  # run_stage script.sh  (helper scripts live in submodules/)
  local step="$1"
  if [ -f "$here/submodules/$step" ]; then
    log "=== Running $step ==="
    bash "$here/submodules/$step" || warn "$step reported errors (continuing)"
  else
    warn "missing: submodules/$step"
  fi
}

# Open a URL in the desktop user's default browser (best-effort, non-blocking).
open_url() {
  local u="$1"; [ -n "$u" ] || return 0
  local uid; uid="$(id -u "$TARGET_USER" 2>/dev/null)"
  if have_cmd xdg-open; then
    sudo -u "$TARGET_USER" DISPLAY="${DISPLAY:-:0}" \
      DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${uid}/bus" \
      xdg-open "$u" >/dev/null 2>&1 &
  elif have_cmd gio; then
    sudo -u "$TARGET_USER" DISPLAY="${DISPLAY:-:0}" gio open "$u" >/dev/null 2>&1 &
  fi
}

# Manual downloads, handled LAST. For each app: show what to download and where to
# put it, then ask (done/skip). On 'done', verify the file is present and install
# it; if it is missing/unusable, show a red error and ask again until the file is
# correctly placed or the user types 'skip'.
install_manual_apps() {
  [ "${#MANUAL_APPS[@]}" -eq 0 ] && return 0
  MODULE="Applications"   # manual downloads are part of the Applications module
  local base="${MIGRATE_MANUAL_DIR:-$DOWNLOAD_DIR/manual}"
  printf '\n'; log "Manual downloads (apps with no automatic installer) -- done last"
  local entry name alt note url paid slug dir ans f got
  for entry in "${MANUAL_APPS[@]}"; do
    IFS='|' read -r name alt note url paid <<< "$entry"
    slug="$(slugify "$name")"; dir="$base/$slug"; mkdir -p "$dir"
    printf '\n\n'
    if [ -n "$alt" ]; then
      printf '\033[1;34m==> Manual install: %s   --->   %s\033[0m\n' "$name" "$alt" >&3
    else
      printf '\033[1;34m==> Manual install: %s\033[0m\n' "$name" >&3
    fi
    info "This app's installer cannot be downloaded automatically by the Migration Toolkit (it usually requires accepting a licence / signing in, or has no stable direct download link)."
    # Free-only mode: this manual app's only alternative is paid. Ask before continuing.
    if [ "${MIGRATE_FREE_ONLY:-no}" = "yes" ] && [ "${paid:-0}" = "1" ]; then
      if [ -r /dev/tty ]; then
        printf '  No free alternative exists for this application. Do you want to continue with the installation of the paid one? Answering with No means skipping this application (y/n): ' > /dev/tty
        read -r ans < /dev/tty || ans="n"
        case "$ans" in [Yy]*) ;; *) mark_skip "$name" "paid - skipped (free-only mode)"; continue ;; esac
      else
        mark_skip "$name" "paid - skipped (free-only mode)"; continue
      fi
    fi
    [ -n "$note" ] && info "$note"
    if [ -n "$url" ]; then
      info "Download page: $url"
      info "(opening it in your default browser ...)"
      open_url "$url"
    fi
    info "Download the installer and place it (keep its original file name) in:"
    info "    $dir"
    info "Then type 'done'. The file is handled by its extension (.deb/.rpm/.sh/"
    info ".run/.bin/.bundle/.AppImage/.tar.gz/.zip/...); 'skip' to skip this app."
    if [ ! -r /dev/tty ]; then mark_skip "$name" "no tty for manual prompt"; continue; fi
    while :; do
      printf '  %s (done/skip): ' "$name" > /dev/tty
      read -r ans < /dev/tty || ans="skip"
      case "$ans" in
        [Ss]|[Ss][Kk][Ii][Pp])
          mark_skip "$name" "user skipped"; break ;;
        [Dd]|[Dd][Oo][Nn][Ee])
          if [ -z "$(ls -A "$dir" 2>/dev/null)" ]; then
            printf '\033[1;31m  No file found in %s -- place the file there, then type done (or skip).\033[0m\n' "$dir" > /dev/tty
            continue
          fi
          got=0; LAST_ERR=""
          for f in "$dir"/*; do
            [ -f "$f" ] || continue
            if install_by_ext "$f"; then got=1; fi
          done
          if [ "$got" -eq 1 ]; then
            mark_ok "$name" "installed from $dir"; break
          else
            printf '\033[1;31m  %s -- fix the file in %s, then type done (or skip).\033[0m\n' "${LAST_ERR:-could not handle the file}" "$dir" > /dev/tty
          fi
          ;;
        *)
          printf '\033[1;31m  Please type "done" or "skip".\033[0m\n' > /dev/tty ;;
      esac
    done
  done
}

# Print the summary for ONE module from the shared log (fields: date,module,status,name,detail).
print_module_summary() {  # print_module_summary "Module name"
  local f="${RESULTS:-/tmp/migrate_to_linux_results.tsv}" m="$1"
  awk -F'\t' -v m="$m" '$2==m{found=1} END{exit !found}' "$f" || return 0
  local nok nskip nman nfail
  nok=$(awk   -F'\t' -v m="$m" '$2==m{g=$3;gsub(/ /,"",g); if(g=="OK")c++}     END{print c+0}' "$f")
  nskip=$(awk -F'\t' -v m="$m" '$2==m{g=$3;gsub(/ /,"",g); if(g=="SKIP")c++}   END{print c+0}' "$f")
  nman=$(awk  -F'\t' -v m="$m" '$2==m{g=$3;gsub(/ /,"",g); if(g=="MANUAL")c++} END{print c+0}' "$f")
  nfail=$(awk -F'\t' -v m="$m" '$2==m{g=$3;gsub(/ /,"",g); if(g=="FAIL")c++}   END{print c+0}' "$f")
  printf '\n'
  # purple, extra-indented section title
  printf '        \033[1;35m===== %s summary =====\033[0m\n' "$m" >&3
  ok   "          Succeeded : $nok"
  info "          Skipped   : $nskip"
  warn "          Manual    : $nman"
  err  "          Failed    : $nfail"
  if [ "$nfail" -gt 0 ]; then
    err "          Failures (1-line reason each):"
    awk -F'\t' -v m="$m" '{g=$3;gsub(/ /,"",g)} $2==m && g=="FAIL"{printf "            - %s: %s\n",$4,$5}' "$f" >&3
  fi
  if [ "$nman" -gt 0 ]; then
    warn "          Manual steps still needed:"
    awk -F'\t' -v m="$m" '{g=$3;gsub(/ /,"",g)} $2==m && g=="MANUAL"{printf "            - %s: %s\n",$4,$5}' "$f" >&3
  fi
  if [ "$nskip" -gt 0 ]; then
    # Group skipped items by their reason: "Skipped: <reason>" with its items beneath.
    local r
    while IFS= read -r r; do
      [ -z "$r" ] && continue
      info "          Skipped: $r"
      awk -F'\t' -v m="$m" -v rr="$r" '{g=$3;gsub(/ /,"",g); d=$5; if(d=="")d="already present"} $2==m && g=="SKIP" && d==rr{printf "            - %s\n",$4}' "$f" >&3
    done < <(awk -F'\t' -v m="$m" '{g=$3;gsub(/ /,"",g); d=$5; if(d=="")d="already present"} $2==m && g=="SKIP"{print d}' "$f" | sort -u)
  fi
}

# Final summary: comes after everything else, classified per big module in the order
# they ran (Drivers -> Config settings -> Applications).
print_combined_summary() {
  local f="${RESULTS:-/tmp/migrate_to_linux_results.tsv}"
  printf '\n\n'
  log "==================== FINAL SUMMARY ===================="
  if [ ! -s "$f" ]; then info "No operations were recorded."; return 0; fi
  print_module_summary "Drivers"
  print_module_summary "Config settings"
  print_module_summary "Applications"
  printf '\n'
  info "Full log: $f"
}

main() {
  clear 2>/dev/null || printf '\033[2J\033[3J\033[H'
  require_root
  detect_distro
  detect_arch
  here="$(cd "$(dirname "$0")" && pwd)"

  # Share ONE results log across all stages so the final summary covers everything.
  export RESULTS="${RESULTS:-/tmp/migrate_to_linux_results.tsv}"
  : > "$RESULTS" 2>/dev/null || true
  export MIGRATE_KEEP_RESULTS=1

  log "Migrate to Linux  --  Run All"
  info "Distribution : ${DISTRO_NAME}"
  info "Family / pm  : ${FAMILY} / ${PM}"
  info "Architecture : ${ARCH}"

  # ---- Configuration: from the saved config file, or by asking each question ----
  local do_drivers=0 do_apps=0 do_settings=0 do_docker=0
  local cfg="$here/migrate.config" use_cfg=0
  if [ -f "$cfg" ]; then
    show_config "$cfg"
    printf '\n'
    if [ -r /dev/tty ]; then
      ask "Do you want to continue with these configurations (Choose N to answer them again)?" y && use_cfg=1
    else
      use_cfg=1
    fi
  fi

  if [ "$use_cfg" -eq 1 ]; then
    load_config "$cfg"
    info "Using the saved configuration above."
  else
    log "Setup questions (answer each one; the install then runs unattended):"
    ask "(1/9) Install device drivers?"     y && do_drivers=1
    ask "(2/9) Install must-have software?" y && do_apps=1
    if [ "$do_apps" -eq 1 ]; then
      MIGRATE_ALT_LIMIT="$(ask_number "(3/9) How many (if applicable) best alternatives of an application do you want to install?" 1)"
      export MIGRATE_ALT_LIMIT
      MIGRATE_VERSION_MODE="$(ask_ab "(4/9) Want to install same version of exact equivalents from Windows to Linux or the latest version?" "Same version" "Latest version")"
      export MIGRATE_VERSION_MODE
      if ask "(5/9) Update apps that are already installed on Linux?" n; then MIGRATE_UPDATE_EXISTING=yes; else MIGRATE_UPDATE_EXISTING=no; fi
      export MIGRATE_UPDATE_EXISTING
      if ask "(6/9) Install security-suite equivalents (antivirus, extra firewall, etc.)? Linux is hardened by default, so many users skip these." n; then MIGRATE_INSTALL_SECURITY=yes; else MIGRATE_INSTALL_SECURITY=no; fi
      export MIGRATE_INSTALL_SECURITY
      if ask "(7/9) Do you want to only install free applications and skip paid alternatives?" n; then MIGRATE_FREE_ONLY=yes; else MIGRATE_FREE_ONLY=no; fi
      export MIGRATE_FREE_ONLY
    fi
    ask "(8/9) Apply Windows settings?"     y && do_settings=1
    if [ -f "$here/submodules/docker_rebuild.sh" ]; then
      ask "(9/9) Rebuild docker components (If you have installed docker on Windows - images, volumes, containers, networks, etc.)?" y && do_docker=1
    fi
  fi

  # ---- Run the selected stages, unattended.  Order: drivers -> settings -> apps ----
  [ "$do_drivers"  -eq 1 ] && run_stage install_device_drivers.sh
  [ "$do_settings" -eq 1 ] && run_stage apply_settings.sh
  [ "$do_apps"     -eq 1 ] && run_stage install_must_have_software.sh

  # ---- Manual downloads (part of the apps stage) ----
  [ "$do_apps" -eq 1 ] && install_manual_apps

  # ---- Docker rebuild last (needs Docker, which the apps stage installs) ----
  if [ "$do_docker" -eq 1 ]; then
    log "=== Running docker_rebuild.sh ==="
    bash "$here/submodules/docker_rebuild.sh" || warn "docker_rebuild.sh reported errors"
  fi

  print_combined_summary

  printf '\n'; log "All steps finished."
}

main "$@"
