<#
.SYNOPSIS
    Snapshots the LOCAL Docker setup (images, volumes, networks, containers and how
    containers are wired to them) and writes a single, cross-platform
    "docker_rebuild.ps1" that recreates the same topology later on any machine
    (Windows / Linux / macOS, anywhere PowerShell + Docker are available).

.DESCRIPTION
    PowerShell port of docker_discovery.sh.  Volume DATA is intentionally NOT
    captured (per requirement) - only the volumes themselves are recreated (empty).
    Bind-mount host paths are recreated as-referenced; ensure they exist on the
    target.  If the Docker engine is not running, this script starts it first.

.PARAMETER Out
    Output file to write.  Default: docker_rebuild.ps1 in the current directory.

.EXAMPLE
    ./docker_discovery.ps1
    ./docker_discovery.ps1 -Out C:\backup\docker_rebuild.ps1
#>
[CmdletBinding()]
param([string] $Out = "docker_rebuild.ps1")

$ErrorActionPreference = 'Continue'

function Log  { param($m) Write-Host "==> $m" -ForegroundColor Blue }
function Info { param($m) Write-Host "       $m" }
function Warn { param($m) Write-Host $m -ForegroundColor Yellow }
function Err  { param($m) Write-Host $m -ForegroundColor Red }

# ----------------------------------------------------------------------------
# OS detection + "ensure docker is running"
# ----------------------------------------------------------------------------
function Get-OSKind {
    if ($PSVersionTable.PSVersion.Major -lt 6) { return 'windows' }   # Windows PowerShell 5.1
    if ($IsWindows) { return 'windows' }
    if ($IsMacOS)   { return 'mac' }
    if ($IsLinux)   { return 'linux' }
    return 'windows'
}

function Test-DockerUp {
    docker info *> $null
    return ($LASTEXITCODE -eq 0)
}

function Start-DockerEngine {
    param([string] $OS)
    Log "Docker engine is not running -- attempting to start it ($OS) ..."
    switch ($OS) {
        'windows' {
            $dd = Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe'
            if (Test-Path $dd) { Start-Process -FilePath $dd | Out-Null }
            else { Start-Service com.docker.service -ErrorAction SilentlyContinue }
        }
        'mac'   { & open -a Docker 2>$null }
        'linux' {
            if (Get-Command systemctl -ErrorAction SilentlyContinue) { & sudo systemctl start docker 2>$null }
            elseif (Get-Command service -ErrorAction SilentlyContinue) { & sudo service docker start 2>$null }
        }
    }
    $i = 0
    Write-Host "       waiting for Docker" -NoNewline
    while (-not (Test-DockerUp)) {
        Start-Sleep -Seconds 2; $i++; Write-Host "." -NoNewline
        if ($i -gt 90) { Write-Host ""; Err "Docker did not become ready in time."; exit 1 }
    }
    Write-Host " ready"
}

# Single-quote a value safely for the emitted PowerShell script.
function Quote { param([string] $s) "'" + (($s -replace "'", "''")) + "'" }

# ----------------------------------------------------------------------------
# Pre-flight
# ----------------------------------------------------------------------------
$os = Get-OSKind
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Err "Docker CLI not found on PATH. Install Docker first."; exit 1
}
if (-not (Test-DockerUp)) { Start-DockerEngine -OS $os }

Log "Discovering Docker objects ..."
$lines = New-Object System.Collections.Generic.List[string]
function Emit { param([string] $line = '') $lines.Add($line) }

# ----------------------------------------------------------------------------
# Header + the same bootstrap (so the rebuild script also auto-starts Docker)
# ----------------------------------------------------------------------------
$header = @'
#!/usr/bin/env pwsh
# =============================================================================
#  docker_rebuild.ps1   --   AUTO-GENERATED by docker_discovery.ps1
#  Recreates the captured Docker images / volumes / networks / containers.
#  Cross-platform (Windows / Linux / macOS via PowerShell). Volume DATA is NOT
#  restored. Re-running is safe: existing objects are skipped; named containers
#  are replaced (docker rm -f) before being recreated.
# =============================================================================
$ErrorActionPreference = 'Continue'
function Log { param($m) Write-Host "==> $m" -ForegroundColor Blue }

function Get-OSKind {
    if ($PSVersionTable.PSVersion.Major -lt 6) { return 'windows' }
    if ($IsWindows) { return 'windows' }; if ($IsMacOS) { return 'mac' }
    if ($IsLinux) { return 'linux' }; return 'windows'
}
function Test-DockerUp { docker info *> $null; return ($LASTEXITCODE -eq 0) }
function Start-DockerEngine {
    param($OS)
    Log "Starting Docker engine ($OS) ..."
    switch ($OS) {
        'windows' {
            $dd = Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe'
            if (Test-Path $dd) { Start-Process -FilePath $dd | Out-Null }
            else { Start-Service com.docker.service -ErrorAction SilentlyContinue }
        }
        'mac'   { & open -a Docker 2>$null }
        'linux' {
            if (Get-Command systemctl -ErrorAction SilentlyContinue) { & sudo systemctl start docker 2>$null }
            elseif (Get-Command service -ErrorAction SilentlyContinue) { & sudo service docker start 2>$null }
        }
    }
    $i = 0; while (-not (Test-DockerUp)) { Start-Sleep 2; $i++; if ($i -gt 90) { throw "Docker not ready." } }
}
$os = Get-OSKind
if (-not (Test-DockerUp)) { Start-DockerEngine -OS $os }
'@
foreach ($h in ($header -split "`r?`n")) { Emit $h }

# ----------------------------------------------------------------------------
# 1. NETWORKS (custom only; bridge/host/none are built-in)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- networks ---------------------------------------------------------------'
foreach ($net in (docker network ls --format '{{.Name}}')) {
    if ([string]::IsNullOrWhiteSpace($net)) { continue }
    if ($net -in @('bridge', 'host', 'none')) { continue }
    $driver   = (docker network inspect -f '{{.Driver}}' $net 2>$null)
    $internal = (docker network inspect -f '{{.Internal}}' $net 2>$null)
    $subnet   = (docker network inspect -f '{{range .IPAM.Config}}{{.Subnet}} {{end}}' $net 2>$null)
    $gateway  = (docker network inspect -f '{{range .IPAM.Config}}{{.Gateway}} {{end}}' $net 2>$null)
    $cmd = "docker network create"
    if ($driver) { $cmd += " --driver $(Quote $driver)" }
    foreach ($s in ("$subnet"  -split '\s+')) { if ($s) { $cmd += " --subnet $(Quote $s)" } }
    foreach ($g in ("$gateway" -split '\s+')) { if ($g) { $cmd += " --gateway $(Quote $g)" } }
    if ("$internal" -eq 'true') { $cmd += " --internal" }
    $cmd += " $(Quote $net)"
    Emit "docker network inspect $(Quote $net) *> `$null; if (`$LASTEXITCODE -ne 0) { $cmd }"
}

# ----------------------------------------------------------------------------
# 2. VOLUMES (named only; skip anonymous 64-hex volumes)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- volumes (data NOT restored) -------------------------------------------'
foreach ($vol in (docker volume ls --format '{{.Name}}')) {
    if ([string]::IsNullOrWhiteSpace($vol)) { continue }
    if ($vol -match '^[0-9a-f]{64}$') { continue }
    $driver = (docker volume inspect -f '{{.Driver}}' $vol 2>$null)
    $cmd = "docker volume create"
    if ($driver) { $cmd += " --driver $(Quote $driver)" }
    $cmd += " $(Quote $vol)"
    Emit "docker volume inspect $(Quote $vol) *> `$null; if (`$LASTEXITCODE -ne 0) { $cmd }"
}

# ----------------------------------------------------------------------------
# 3. IMAGES (pull tagged images; locally-built/<none> can't be pulled)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- images ----------------------------------------------------------------'
foreach ($img in (docker images --format '{{.Repository}}:{{.Tag}}' | Sort-Object -Unique)) {
    if ([string]::IsNullOrWhiteSpace($img)) { continue }
    if ($img -like '*<none>*') { continue }
    Emit "docker image inspect $(Quote $img) *> `$null; if (`$LASTEXITCODE -ne 0) { docker pull $(Quote $img) }"
}

# ----------------------------------------------------------------------------
# 4. CONTAINERS (recreate run config; best-effort)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- containers ------------------------------------------------------------'
foreach ($cid in (docker ps -aq)) {
    if ([string]::IsNullOrWhiteSpace($cid)) { continue }
    $name    = (docker inspect -f '{{.Name}}' $cid 2>$null) -replace '^/', ''
    $image   = (docker inspect -f '{{.Config.Image}}' $cid 2>$null)
    $restart = (docker inspect -f '{{.HostConfig.RestartPolicy.Name}}' $cid 2>$null)
    $workdir = (docker inspect -f '{{.Config.WorkingDir}}' $cid 2>$null)
    $cuser   = (docker inspect -f '{{.Config.User}}' $cid 2>$null)
    $ports   = (docker inspect -f '{{range $p, $b := .HostConfig.PortBindings}}{{range $b}}{{if .HostIp}}{{.HostIp}}:{{end}}{{.HostPort}}:{{$p}} {{end}}{{end}}' $cid 2>$null)
    $mounts  = (docker inspect -f '{{range .Mounts}}{{if eq .Type "volume"}}{{.Name}}::{{.Destination}}{{else}}{{.Source}}::{{.Destination}}{{end}}{{if .RW}}{{else}}:ro{{end}} {{end}}' $cid 2>$null)
    $nets    = (docker inspect -f '{{range $n, $c := .NetworkSettings.Networks}}{{$n}} {{end}}' $cid 2>$null)

    $run = "docker run -d"
    if ($name)    { $run += " --name $(Quote $name)" }
    if ($restart -and $restart -ne 'no') { $run += " --restart $(Quote $restart)" }
    if ($workdir) { $run += " -w $(Quote $workdir)" }
    if ($cuser)   { $run += " -u $(Quote $cuser)" }

    foreach ($p in ("$ports" -split '\s+')) { if ($p) { $run += " -p $(Quote $p)" } }

    foreach ($m in ("$mounts" -split '\s+')) {
        if (-not $m) { continue }
        $parts = $m -split '::', 2
        if ($parts.Count -eq 2) { $run += " -v $(Quote ($parts[0] + ':' + $parts[1]))" }
    }

    foreach ($e in (docker inspect -f '{{range .Config.Env}}{{println .}}{{end}}' $cid 2>$null)) {
        if ($e) { $run += " -e $(Quote $e)" }
    }

    $netList = @("$nets" -split '\s+' | Where-Object { $_ })
    $primary = if ($netList.Count -gt 0) { $netList[0] } else { '' }
    $extra   = if ($netList.Count -gt 1) { $netList[1..($netList.Count - 1)] } else { @() }
    if ($primary) { $run += " --network $(Quote $primary)" }

    $run += " $(Quote $image)"

    $cmdParts = @(docker inspect -f '{{range .Config.Cmd}}{{println .}}{{end}}' $cid 2>$null | Where-Object { $_ })
    foreach ($c in $cmdParts) { $run += " $(Quote $c)" }

    Emit ''
    Emit "# container: $name"
    Emit "docker rm -f $(Quote $name) *> `$null"
    Emit $run
    foreach ($n in $extra) { if ($n) { Emit "docker network connect $(Quote $n) $(Quote $name)" } }
}

Emit ''
Emit 'Log "Rebuild complete."'

# ----------------------------------------------------------------------------
# Write the rebuild script (LF newlines, UTF-8 no BOM)
# ----------------------------------------------------------------------------
if (-not [System.IO.Path]::IsPathRooted($Out)) { $Out = Join-Path (Get-Location).Path $Out }
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($Out, (($lines -join "`n") + "`n"), $enc)

Log "Wrote $Out"
Info "Review it, then run:  pwsh $Out   (or: ./$([System.IO.Path]::GetFileName($Out)))"
Warn "Caveats: volume DATA, healthchecks, devices, capabilities, ulimits, sysctls,"
Warn "         and compose context are not captured (best-effort topology rebuild)."
