#!/usr/bin/env pwsh
# =============================================================================
#  docker_rebuild.ps1   --   AUTO-GENERATED by docker_discovery.ps1
#  Recreates the captured Docker images / volumes / networks / containers.
#  Cross-platform (Windows / Linux / macOS via PowerShell). Volume DATA is NOT
#  restored. Re-running is safe: existing objects are skipped; named containers
#  are replaced (docker rm -f) before being recreated.
# =============================================================================
$ErrorActionPreference = 'Continue'
function Log { param($m) Write-Host "==> $m" -ForegroundColor Blue }

function Get-OSKind {
    if ($PSVersionTable.PSVersion.Major -lt 6) { return 'windows' }
    if ($IsWindows) { return 'windows' }; if ($IsMacOS) { return 'mac' }
    if ($IsLinux) { return 'linux' }; return 'windows'
}
function Test-DockerUp { docker info *> $null; return ($LASTEXITCODE -eq 0) }
function Start-DockerEngine {
    param($OS)
    Log "Starting Docker engine ($OS) ..."
    switch ($OS) {
        'windows' {
            $dd = Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe'
            if (Test-Path $dd) { Start-Process -FilePath $dd | Out-Null }
            else { Start-Service com.docker.service -ErrorAction SilentlyContinue }
        }
        'mac'   { & open -a Docker 2>$null }
        'linux' {
            if (Get-Command systemctl -ErrorAction SilentlyContinue) { & sudo systemctl start docker 2>$null }
            elseif (Get-Command service -ErrorAction SilentlyContinue) { & sudo service docker start 2>$null }
        }
    }
    $i = 0; while (-not (Test-DockerUp)) { Start-Sleep 2; $i++; if ($i -gt 90) { throw "Docker not ready." } }
}
$os = Get-OSKind
if (-not (Test-DockerUp)) { Start-DockerEngine -OS $os }

# --- networks ---------------------------------------------------------------

# --- volumes (data NOT restored) -------------------------------------------
docker volume inspect 'portainer_data' *> $null; if ($LASTEXITCODE -ne 0) { docker volume create --driver 'local' 'portainer_data' }
docker volume inspect 'postgresql-data' *> $null; if ($LASTEXITCODE -ne 0) { docker volume create --driver 'local' 'postgresql-data' }

# --- images ----------------------------------------------------------------
docker image inspect 'nginx:latest' *> $null; if ($LASTEXITCODE -ne 0) { docker pull 'nginx:latest' }
docker image inspect 'portainer/portainer-ee:latest' *> $null; if ($LASTEXITCODE -ne 0) { docker pull 'portainer/portainer-ee:latest' }
docker image inspect 'postgres:latest' *> $null; if ($LASTEXITCODE -ne 0) { docker pull 'postgres:latest' }

# --- containers ------------------------------------------------------------

# container: portainer
docker rm -f 'portainer' *> $null
docker run -d --name 'portainer' --restart 'always' -w '/' -p '8000:8000/tcp' -p '9443:9443/tcp' -v '/var/run/docker.sock:/var/run/docker.sock' -v 'portainer_data:/data' -e 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' --network 'bridge' 'portainer/portainer-ee:latest'

# container: my-nginx
docker rm -f 'my-nginx' *> $null
docker run -d --name 'my-nginx' -p '8080:80/tcp' -v '/path/to/site:/usr/share/nginx/html:ro' -e 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' -e 'NGINX_VERSION=1.31.1' -e 'NJS_VERSION=0.9.9' -e 'NJS_RELEASE=1~trixie' -e 'ACME_VERSION=0.4.1' -e 'PKG_RELEASE=1~trixie' -e 'DYNPKG_RELEASE=1~trixie' --network 'bridge' 'nginx' 'nginx' '-g' 'daemon off;'

# container: postgresql-container
docker rm -f 'postgresql-container' *> $null
docker run -d --name 'postgresql-container' -p '5432:5432/tcp' -v '1763c67a9cdb4ff180ba73a7153b4ebb059c80139a4966ed44d25cf6d53de341:/var/lib/postgresql' -v 'postgresql-data:/var/lib/postgresql/data' -e 'POSTGRES_PASSWORD=<strong-password>' -e 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/18/bin' -e 'GOSU_VERSION=1.19' -e 'LANG=en_US.utf8' -e 'PG_MAJOR=18' -e 'PG_VERSION=18.4-1.pgdg13+1' -e 'PGDATA=/var/lib/postgresql/18/docker' --network 'bridge' 'postgres:latest' 'postgres'

Log "Rebuild complete."
