#!/usr/bin/env bash
# =============================================================================
#  docker_discovery.sh
# -----------------------------------------------------------------------------
#  Snapshots the LOCAL Docker setup -- images, volumes, networks and containers,
#  including how containers are wired to them -- and writes a single, cross-
#  platform "docker_rebuild.sh" that recreates the same topology later on any
#  machine (Windows / Linux / macOS).
#
#  NOTE: volume DATA is intentionally NOT captured (per requirement). Only the
#  volumes themselves are recreated (empty). Bind-mount host paths are recreated
#  as-referenced; ensure they exist on the target.
#
#  If the Docker engine is not running, this script starts it first.
#
#  Usage:   ./docker_discovery.sh [output_file]      # default: docker_rebuild.sh
# =============================================================================
set -o pipefail

OUT="${1:-docker_rebuild.sh}"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*" >&2; }
info() { printf '       %s\n' "$*" >&2; }
warn() { printf '\033[1;33m%s\033[0m\n' "$*" >&2; }
err()  { printf '\033[1;31m%s\033[0m\n' "$*" >&2; }

# ----------------------------------------------------------------------------
# OS detection + "ensure docker is running" (shared with the generated script)
# ----------------------------------------------------------------------------
detect_os() {
  case "$(uname -s 2>/dev/null)" in
    Linux*)               OS=linux ;;
    Darwin*)              OS=mac ;;
    MINGW*|MSYS*|CYGWIN*) OS=windows ;;
    *)                    OS="${OS:-unknown}" ;;
  esac
}

docker_running() { docker info >/dev/null 2>&1; }

start_docker() {
  log "Docker engine is not running -- attempting to start it ($OS) ..."
  case "$OS" in
    linux)
      if command -v systemctl >/dev/null 2>&1; then sudo systemctl start docker 2>/dev/null
      elif command -v service >/dev/null 2>&1; then sudo service docker start 2>/dev/null
      fi ;;
    mac)
      open -a Docker 2>/dev/null || true ;;
    windows)
      local dd="/c/Program Files/Docker/Docker/Docker Desktop.exe"
      if [ -f "$dd" ]; then "$dd" >/dev/null 2>&1 &
      else net start com.docker.service >/dev/null 2>&1 || true; fi ;;
    *)
      err "Unknown OS -- start Docker manually, then re-run."; return 1 ;;
  esac
  local i=0
  printf '       waiting for Docker' >&2
  while ! docker_running; do
    i=$((i + 1)); printf '.' >&2
    if [ "$i" -gt 90 ]; then printf '\n' >&2; err "Docker did not become ready in time."; return 1; fi
    sleep 2
  done
  printf ' ready\n' >&2
}

# single-quote a value safely for the emitted bash script
shq() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

emit() { printf '%s\n' "$*" >> "$OUT"; }

# ----------------------------------------------------------------------------
# Pre-flight
# ----------------------------------------------------------------------------
detect_os
if ! command -v docker >/dev/null 2>&1; then
  err "Docker CLI not found on PATH. Install Docker first."
  exit 1
fi
docker_running || start_docker || { err "Could not start Docker."; exit 1; }

log "Discovering Docker objects ..."
: > "$OUT"

# ----------------------------------------------------------------------------
# Header + the same bootstrap (so the rebuild script also auto-starts Docker)
# ----------------------------------------------------------------------------
cat > "$OUT" <<'HEADER'
#!/usr/bin/env bash
# =============================================================================
#  docker_rebuild.sh   --   AUTO-GENERATED by docker_discovery.sh
#  Recreates the captured Docker images / volumes / networks / containers.
#  Cross-platform (Windows / Linux / macOS). Volume DATA is NOT restored.
#  Re-running is safe: existing objects are skipped; named containers are
#  replaced (docker rm -f) before being recreated.
# =============================================================================
set -o pipefail

log(){ printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m%s\033[0m\n' "$*"; }

detect_os(){
  case "$(uname -s 2>/dev/null)" in
    Linux*) OS=linux;; Darwin*) OS=mac;;
    MINGW*|MSYS*|CYGWIN*) OS=windows;; *) OS=unknown;;
  esac
}
docker_running(){ docker info >/dev/null 2>&1; }
start_docker(){
  log "Starting Docker engine ($OS) ..."
  case "$OS" in
    linux) command -v systemctl >/dev/null 2>&1 && sudo systemctl start docker 2>/dev/null || sudo service docker start 2>/dev/null;;
    mac) open -a Docker 2>/dev/null || true;;
    windows) dd="/c/Program Files/Docker/Docker/Docker Desktop.exe"; [ -f "$dd" ] && "$dd" >/dev/null 2>&1 & true;;
  esac
  i=0; while ! docker_running; do i=$((i+1)); [ "$i" -gt 90 ] && { warn "Docker not ready."; exit 1; }; sleep 2; done
}
detect_os
docker_running || start_docker

HEADER

# ----------------------------------------------------------------------------
# 1. NETWORKS (custom only; bridge/host/none are built-in)
# ----------------------------------------------------------------------------
emit '# --- networks ---------------------------------------------------------------'
while IFS= read -r net; do
  [ -z "$net" ] && continue
  case "$net" in bridge|host|none) continue ;; esac
  driver=$(docker network inspect -f '{{.Driver}}' "$net" 2>/dev/null)
  internal=$(docker network inspect -f '{{.Internal}}' "$net" 2>/dev/null)
  subnet=$(docker network inspect -f '{{range .IPAM.Config}}{{.Subnet}} {{end}}' "$net" 2>/dev/null)
  gateway=$(docker network inspect -f '{{range .IPAM.Config}}{{.Gateway}} {{end}}' "$net" 2>/dev/null)
  cmd="docker network create"
  [ -n "$driver" ] && cmd="$cmd --driver $(shq "$driver")"
  for s in $subnet;  do [ -n "$s" ] && cmd="$cmd --subnet $(shq "$s")"; done
  for g in $gateway; do [ -n "$g" ] && cmd="$cmd --gateway $(shq "$g")"; done
  [ "$internal" = "true" ] && cmd="$cmd --internal"
  cmd="$cmd $(shq "$net")"
  emit "docker network inspect $(shq "$net") >/dev/null 2>&1 || $cmd"
done < <(docker network ls --format '{{.Name}}')

# ----------------------------------------------------------------------------
# 2. VOLUMES (named only; skip anonymous 64-hex volumes)
# ----------------------------------------------------------------------------
emit ''
emit '# --- volumes (data NOT restored) -------------------------------------------'
while IFS= read -r vol; do
  [ -z "$vol" ] && continue
  case "$vol" in *[!0-9a-f]*) : ;; *) [ ${#vol} -eq 64 ] && continue ;; esac
  driver=$(docker volume inspect -f '{{.Driver}}' "$vol" 2>/dev/null)
  cmd="docker volume create"
  [ -n "$driver" ] && cmd="$cmd --driver $(shq "$driver")"
  cmd="$cmd $(shq "$vol")"
  emit "docker volume inspect $(shq "$vol") >/dev/null 2>&1 || $cmd"
done < <(docker volume ls --format '{{.Name}}')

# ----------------------------------------------------------------------------
# 3. IMAGES (pull tagged images; locally-built/<none> can't be pulled)
# ----------------------------------------------------------------------------
emit ''
emit '# --- images ----------------------------------------------------------------'
while IFS= read -r img; do
  [ -z "$img" ] && continue
  case "$img" in *'<none>'*) continue ;; esac
  emit "docker image inspect $(shq "$img") >/dev/null 2>&1 || docker pull $(shq "$img")"
done < <(docker images --format '{{.Repository}}:{{.Tag}}' | sort -u)

# ----------------------------------------------------------------------------
# 4. CONTAINERS (recreate run config; best-effort)
# ----------------------------------------------------------------------------
emit ''
emit '# --- containers ------------------------------------------------------------'
while IFS= read -r cid; do
  [ -z "$cid" ] && continue
  name=$(docker inspect -f '{{.Name}}' "$cid" 2>/dev/null | sed 's#^/##')
  image=$(docker inspect -f '{{.Config.Image}}' "$cid" 2>/dev/null)
  restart=$(docker inspect -f '{{.HostConfig.RestartPolicy.Name}}' "$cid" 2>/dev/null)
  workdir=$(docker inspect -f '{{.Config.WorkingDir}}' "$cid" 2>/dev/null)
  cuser=$(docker inspect -f '{{.Config.User}}' "$cid" 2>/dev/null)
  ports=$(docker inspect -f '{{range $p, $b := .HostConfig.PortBindings}}{{range $b}}{{if .HostIp}}{{.HostIp}}:{{end}}{{.HostPort}}:{{$p}} {{end}}{{end}}' "$cid" 2>/dev/null)
  mounts=$(docker inspect -f '{{range .Mounts}}{{if eq .Type "volume"}}{{.Name}}::{{.Destination}}{{else}}{{.Source}}::{{.Destination}}{{end}}{{if .RW}}{{else}}:ro{{end}} {{end}}' "$cid" 2>/dev/null)
  nets=$(docker inspect -f '{{range $n, $c := .NetworkSettings.Networks}}{{$n}} {{end}}' "$cid" 2>/dev/null)

  run="docker run -d"
  [ -n "$name" ]    && run="$run --name $(shq "$name")"
  if [ -n "$restart" ] && [ "$restart" != "no" ] && [ "$restart" != "" ]; then run="$run --restart $(shq "$restart")"; fi
  [ -n "$workdir" ] && run="$run -w $(shq "$workdir")"
  [ -n "$cuser" ]   && run="$run -u $(shq "$cuser")"

  for p in $ports; do [ -n "$p" ] && run="$run -p $(shq "$p")"; done

  for m in $mounts; do
    [ -z "$m" ] && continue
    src="${m%%::*}"; rest="${m#*::}"
    run="$run -v $(shq "${src}:${rest}")"
  done

  # environment (single-quoted per value; skip empties)
  while IFS= read -r e; do
    [ -z "$e" ] && continue
    run="$run -e $(shq "$e")"
  done < <(docker inspect -f '{{range .Config.Env}}{{println .}}{{end}}' "$cid" 2>/dev/null)

  # primary network = first attached; extras connected after creation
  primary=""; extra=""
  for n in $nets; do
    if [ -z "$primary" ]; then primary="$n"; else extra="$extra $n"; fi
  done
  [ -n "$primary" ] && run="$run --network $(shq "$primary")"

  run="$run $(shq "$image")"

  # command (override only if explicitly set)
  cmdline=""
  while IFS= read -r c; do
    [ -z "$c" ] && continue
    cmdline="$cmdline $(shq "$c")"
  done < <(docker inspect -f '{{range .Config.Cmd}}{{println .}}{{end}}' "$cid" 2>/dev/null)
  [ -n "$cmdline" ] && run="$run$cmdline"

  emit ""
  emit "# container: ${name}"
  emit "docker rm -f $(shq "$name") >/dev/null 2>&1 || true"
  emit "$run"
  for n in $extra; do
    [ -n "$n" ] && emit "docker network connect $(shq "$n") $(shq "$name")"
  done
done < <(docker ps -aq)

emit ''
emit 'log "Rebuild complete."'

log "Wrote $OUT"
info "Review it, then run:  bash $OUT"
warn "Caveats: volume DATA, healthchecks, devices, capabilities, ulimits, sysctls,"
warn "         and compose context are not captured (best-effort topology rebuild)."
