<#
.SYNOPSIS
    Snapshots the LOCAL Docker setup (images, volumes, networks, containers and how
    containers are wired to them) and writes a single, cross-platform bash
    "docker_rebuild.sh" that recreates the same topology later on the Linux target.

.DESCRIPTION
    PowerShell port of docker_discovery.sh, meant to run on the WINDOWS source. It
    inspects Docker via the docker CLI and EMITS A BASH script (docker_rebuild.sh)
    so the Linux-side execute_all.sh can trigger it. The rebuild script is written
    to BOTH:
        submodules/docker_rebuild.sh
        Execute on Linux!/docker_rebuild.sh   (shipped to the Linux machine)

    Volume DATA is intentionally NOT captured (per requirement) - only the volumes
    themselves are recreated (empty). If the Docker engine is not running, this
    script starts it first (needed to inspect the objects).

.EXAMPLE
    ./docker_discovery.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Continue'

function Log  { param($m) Write-Host "==> $m" -ForegroundColor Blue }
function Info { param($m) Write-Host "       $m" }
function Warn { param($m) Write-Host $m -ForegroundColor Yellow }
function Err  { param($m) Write-Host $m -ForegroundColor Red }

# ----------------------------------------------------------------------------
# OS detection + "ensure docker is running" (for the inspection side)
# ----------------------------------------------------------------------------
function Get-OSKind {
    if ($PSVersionTable.PSVersion.Major -lt 6) { return 'windows' }
    if ($IsWindows) { return 'windows' }
    if ($IsMacOS)   { return 'mac' }
    if ($IsLinux)   { return 'linux' }
    return 'windows'
}
function Test-DockerUp { docker info *> $null; return ($LASTEXITCODE -eq 0) }
function Start-DockerEngine {
    param([string] $OS)
    Log "Docker engine is not running -- attempting to start it ($OS) ..."
    switch ($OS) {
        'windows' {
            $dd = Join-Path $env:ProgramFiles 'Docker\Docker\Docker Desktop.exe'
            if (Test-Path $dd) { Start-Process -FilePath $dd | Out-Null }
            else { Start-Service com.docker.service -ErrorAction SilentlyContinue }
        }
        'mac'   { & open -a Docker 2>$null }
        'linux' {
            if (Get-Command systemctl -ErrorAction SilentlyContinue) { & sudo systemctl start docker 2>$null }
            elseif (Get-Command service -ErrorAction SilentlyContinue) { & sudo service docker start 2>$null }
        }
    }
    $i = 0; Write-Host "       waiting for Docker" -NoNewline
    while (-not (Test-DockerUp)) {
        Start-Sleep -Seconds 2; $i++; Write-Host "." -NoNewline
        if ($i -gt 90) { Write-Host ""; Err "Docker did not become ready in time."; exit 1 }
    }
    Write-Host " ready"
}

# bash single-quote-escape a value for the EMITTED bash script
function Bq { param([string] $s) "'" + ($s -replace "'", "'\''") + "'" }

# ----------------------------------------------------------------------------
# Pre-flight
# ----------------------------------------------------------------------------
$os = Get-OSKind
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Err "Docker CLI not found on PATH. Nothing to snapshot."; exit 1
}
if (-not (Test-DockerUp)) { Start-DockerEngine -OS $os }

Log "Discovering Docker objects ..."
$sh = New-Object System.Collections.Generic.List[string]
function Emit { param([string] $line = '') $sh.Add($line) }

# ----------------------------------------------------------------------------
# Header + bootstrap (the rebuild script also auto-starts Docker). Pure bash.
# ----------------------------------------------------------------------------
$header = @'
#!/usr/bin/env bash
# =============================================================================
#  docker_rebuild.sh   --   AUTO-GENERATED by docker_discovery.ps1
#  Recreates the captured Docker images / volumes / networks / containers.
#  Cross-platform (Windows / Linux / macOS). Volume DATA is NOT restored.
#  Re-running is safe: existing objects are skipped; named containers are
#  replaced (docker rm -f) before being recreated.
# =============================================================================
set -o pipefail

log(){ printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m%s\033[0m\n' "$*"; }

detect_os(){
  case "$(uname -s 2>/dev/null)" in
    Linux*) OS=linux;; Darwin*) OS=mac;;
    MINGW*|MSYS*|CYGWIN*) OS=windows;; *) OS=unknown;;
  esac
}
docker_running(){ docker info >/dev/null 2>&1; }
start_docker(){
  log "Starting Docker engine ($OS) ..."
  case "$OS" in
    linux) command -v systemctl >/dev/null 2>&1 && sudo systemctl start docker 2>/dev/null || sudo service docker start 2>/dev/null;;
    mac) open -a Docker 2>/dev/null || true;;
    windows) dd="/c/Program Files/Docker/Docker/Docker Desktop.exe"; [ -f "$dd" ] && "$dd" >/dev/null 2>&1 & true;;
  esac
  i=0; while ! docker_running; do i=$((i+1)); [ "$i" -gt 90 ] && { warn "Docker not ready."; exit 1; }; sleep 2; done
}
detect_os
docker_running || start_docker
'@
foreach ($h in ($header -split "`r?`n")) { Emit $h }

# ----------------------------------------------------------------------------
# 1. NETWORKS (custom only; bridge/host/none are built-in)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- networks ---------------------------------------------------------------'
foreach ($net in (docker network ls --format '{{.Name}}')) {
    if ([string]::IsNullOrWhiteSpace($net)) { continue }
    if ($net -in @('bridge', 'host', 'none')) { continue }
    $driver   = (docker network inspect -f '{{.Driver}}' $net 2>$null)
    $internal = (docker network inspect -f '{{.Internal}}' $net 2>$null)
    $subnet   = (docker network inspect -f '{{range .IPAM.Config}}{{.Subnet}} {{end}}' $net 2>$null)
    $gateway  = (docker network inspect -f '{{range .IPAM.Config}}{{.Gateway}} {{end}}' $net 2>$null)
    $cmd = "docker network create"
    if ($driver) { $cmd += " --driver $(Bq $driver)" }
    foreach ($s in ("$subnet"  -split '\s+')) { if ($s) { $cmd += " --subnet $(Bq $s)" } }
    foreach ($g in ("$gateway" -split '\s+')) { if ($g) { $cmd += " --gateway $(Bq $g)" } }
    if ("$internal" -eq 'true') { $cmd += " --internal" }
    $cmd += " $(Bq $net)"
    Emit "docker network inspect $(Bq $net) >/dev/null 2>&1 || $cmd"
}

# ----------------------------------------------------------------------------
# 2. VOLUMES (named only; skip anonymous 64-hex volumes)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- volumes (data NOT restored) -------------------------------------------'
foreach ($vol in (docker volume ls --format '{{.Name}}')) {
    if ([string]::IsNullOrWhiteSpace($vol)) { continue }
    if ($vol -match '^[0-9a-f]{64}$') { continue }
    $driver = (docker volume inspect -f '{{.Driver}}' $vol 2>$null)
    $cmd = "docker volume create"
    if ($driver) { $cmd += " --driver $(Bq $driver)" }
    $cmd += " $(Bq $vol)"
    Emit "docker volume inspect $(Bq $vol) >/dev/null 2>&1 || $cmd"
}

# ----------------------------------------------------------------------------
# 3. IMAGES (pull tagged images; locally-built/<none> can't be pulled)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- images ----------------------------------------------------------------'
foreach ($img in (docker images --format '{{.Repository}}:{{.Tag}}' | Sort-Object -Unique)) {
    if ([string]::IsNullOrWhiteSpace($img)) { continue }
    if ($img -like '*<none>*') { continue }
    Emit "docker image inspect $(Bq $img) >/dev/null 2>&1 || docker pull $(Bq $img)"
}

# ----------------------------------------------------------------------------
# 4. CONTAINERS (recreate run config; best-effort)
# ----------------------------------------------------------------------------
Emit ''
Emit '# --- containers ------------------------------------------------------------'
foreach ($cid in (docker ps -aq)) {
    if ([string]::IsNullOrWhiteSpace($cid)) { continue }
    $name    = (docker inspect -f '{{.Name}}' $cid 2>$null) -replace '^/', ''
    $image   = (docker inspect -f '{{.Config.Image}}' $cid 2>$null)
    $restart = (docker inspect -f '{{.HostConfig.RestartPolicy.Name}}' $cid 2>$null)
    $workdir = (docker inspect -f '{{.Config.WorkingDir}}' $cid 2>$null)
    $cuser   = (docker inspect -f '{{.Config.User}}' $cid 2>$null)
    $ports   = (docker inspect -f '{{range $p, $b := .HostConfig.PortBindings}}{{range $b}}{{if .HostIp}}{{.HostIp}}:{{end}}{{.HostPort}}:{{$p}} {{end}}{{end}}' $cid 2>$null)
    $mounts  = (docker inspect -f '{{range .Mounts}}{{if eq .Type "volume"}}{{.Name}}::{{.Destination}}{{else}}{{.Source}}::{{.Destination}}{{end}}{{if .RW}}{{else}}:ro{{end}} {{end}}' $cid 2>$null)
    $nets    = (docker inspect -f '{{range $n, $c := .NetworkSettings.Networks}}{{$n}} {{end}}' $cid 2>$null)

    $run = "docker run -d"
    if ($name)    { $run += " --name $(Bq $name)" }
    if ($restart -and $restart -ne 'no') { $run += " --restart $(Bq $restart)" }
    if ($workdir) { $run += " -w $(Bq $workdir)" }
    if ($cuser)   { $run += " -u $(Bq $cuser)" }

    foreach ($p in ("$ports" -split '\s+')) { if ($p) { $run += " -p $(Bq $p)" } }

    foreach ($m in ("$mounts" -split '\s+')) {
        if (-not $m) { continue }
        $parts = $m -split '::', 2
        if ($parts.Count -eq 2) { $run += " -v $(Bq ($parts[0] + ':' + $parts[1]))" }
    }

    foreach ($e in (docker inspect -f '{{range .Config.Env}}{{println .}}{{end}}' $cid 2>$null)) {
        if ($e) { $run += " -e $(Bq $e)" }
    }

    $netList = @("$nets" -split '\s+' | Where-Object { $_ })
    $primary = if ($netList.Count -gt 0) { $netList[0] } else { '' }
    $extra   = if ($netList.Count -gt 1) { $netList[1..($netList.Count - 1)] } else { @() }
    if ($primary) { $run += " --network $(Bq $primary)" }

    $run += " $(Bq $image)"

    $cmdParts = @(docker inspect -f '{{range .Config.Cmd}}{{println .}}{{end}}' $cid 2>$null | Where-Object { $_ })
    foreach ($c in $cmdParts) { $run += " $(Bq $c)" }

    Emit ''
    Emit "# container: $name"
    Emit "docker rm -f $(Bq $name) >/dev/null 2>&1 || true"
    Emit $run
    foreach ($n in $extra) { if ($n) { Emit "docker network connect $(Bq $n) $(Bq $name)" } }
}

Emit ''
Emit 'log "Rebuild complete."'

# ----------------------------------------------------------------------------
# Write docker_rebuild.sh (LF, UTF-8 no BOM) to BOTH locations
# ----------------------------------------------------------------------------
$content = (($sh -join "`n") + "`n")
$enc = New-Object System.Text.UTF8Encoding($false)

$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
$projRoot  = Split-Path -Parent $scriptDir
# The shipped copy lives in the installer's submodules subfolder (execute_all.sh runs
# helper scripts from there); a copy is also kept next to this script.
$installerSub = Join-Path (Join-Path $projRoot 'Execute on Linux!') 'submodules'
if (-not (Test-Path $installerSub)) { New-Item -ItemType Directory -Path $installerSub -Force | Out-Null }

$targets = @(
    (Join-Path $scriptDir 'docker_rebuild.sh'),
    (Join-Path $installerSub 'docker_rebuild.sh')
)
foreach ($t in $targets) {
    [System.IO.File]::WriteAllText($t, $content, $enc)
    Log "Wrote $t"
}
Warn "Caveats: volume DATA, healthchecks, devices, capabilities, ulimits, sysctls,"
Warn "         and compose context are not captured (best-effort topology rebuild)."
