#!/usr/bin/env bash
# =============================================================================
#  install_must_have_software.sh
#  GENERATED by submodules/D_compile_and_generate_shell_script.ps1 -- do not edit.
#
#  Universal installer: detects the Linux distribution family (apt/dnf/zypper/
#  pacman) and CPU architecture at runtime, then installs each app Flatpak-first
#  with a native-package fallback.  Runs unchanged on every supported distro.
# =============================================================================
# =============================================================================
#  _common.sh  --  universal runtime engine for the generated installer scripts
# -----------------------------------------------------------------------------
#  This file is INLINED into every generated script in "Execute on Linux!/" by
#  submodules/D_compile_and_generate_shell_script.ps1.  It is distro- and
#  architecture-agnostic: it detects the running distro FAMILY (apt/dnf/zypper/
#  pacman) and CPU ARCH at runtime, then dispatches installs accordingly.
#
#  Design: Flatpak-first.  GUI apps come from Flathub (identical app id on every
#  distro).  The native package manager is used only for the irreducible base
#  (installing Flatpak itself, CLI/dev tools, drivers, system bits).
# =============================================================================

# Be strict but survivable: we handle per-app failures ourselves, so do not let
# a single failing install abort the whole run.
set -o pipefail

# ----------------------------- pretty output ---------------------------------
# All human-facing chatter goes to fd 3 (stdout) so command output can be hidden.
exec 3>&1
log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*" >&3; }
info() { printf '       %s\n' "$*" >&3; }
ok()   { printf '       \033[32m%s\033[0m\n' "$*" >&3; }
warn() { printf '       \033[1;33m%s\033[0m\n' "$*" >&3; }
err()  { printf '\033[1;31m%s\033[0m\n' "$*" >&3; }

have_cmd() { command -v "$1" >/dev/null 2>&1; }

# Filesystem-safe slug from an app name. execute_all.sh stages user-supplied
# files for "manual" apps under $MIGRATE_MANUAL_DIR/<slug>/ using the SAME slug.
slugify() { printf '%s' "$1" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-_'; }

# ----------------------------- bookkeeping -----------------------------------
RESULTS="${RESULTS:-/tmp/migrate_to_linux_results.tsv}"
# execute_all sets MIGRATE_KEEP_RESULTS so the per-stage child scripts APPEND to one
# shared log instead of truncating it, which lets execute_all print a combined
# summary of every operation at the very end. Run standalone, a script truncates.
if [ -z "${MIGRATE_KEEP_RESULTS:-}" ]; then
  : > "$RESULTS" 2>/dev/null || RESULTS="$(mktemp)"
fi
# Containers launched by the docker install method are recorded here (one TSV row per
# container: winapp \t image \t container \t how-to) so the end-of-run summary can print
# a "Launched containers" section. Shares the same cross-stage model as RESULTS.
DOCKER_LAUNCHED="${DOCKER_LAUNCHED:-/tmp/migrate_to_linux_launched.tsv}"
if [ -z "${MIGRATE_KEEP_RESULTS:-}" ]; then
  : > "$DOCKER_LAUNCHED" 2>/dev/null || DOCKER_LAUNCHED="$(mktemp)"
fi
declare -a OK_LIST=() SKIP_LIST=() FAIL_LIST=() FAIL_REASON=() MANUAL_LIST=()

# LAST_ERR holds the 1-line reason from the most recent captured command failure.
LAST_ERR=""

# Run a command, show its output, and on failure capture the last output line into
# LAST_ERR (a 1-line error reason). stdin stays attached, so interactive installers
# still work. Returns the command's real exit code.
capture() {
  local rc tmp; tmp="$(mktemp 2>/dev/null || echo /tmp/mtl_cap.$$)"
  "$@" 2>&1 | tee "$tmp" >&3
  rc=${PIPESTATUS[0]}
  LAST_ERR=""
  if [ "$rc" -ne 0 ]; then
    LAST_ERR="$(grep -v '^[[:space:]]*$' "$tmp" 2>/dev/null | tail -n 1)"
    [ -z "$LAST_ERR" ] && LAST_ERR="exit code $rc"
  fi
  rm -f "$tmp" 2>/dev/null || true
  return "$rc"
}

# MODULE tags which big module (Drivers / Config settings / Applications) each result
# belongs to, so execute_all can print a per-module classified summary at the end.
MODULE="${MODULE:-General}"
record_line() { printf '%s\t%s\t%-6s\t%s\t%s\n' "$(date '+%F %T')" "${MODULE:-General}" "$1" "$2" "${3:-}" >> "$RESULTS"; }
mark_ok()     { OK_LIST+=("$1");     record_line OK     "$1" "${2:-}"; ok "installed: $1"; }
mark_skip()   { SKIP_LIST+=("$1");   record_line SKIP   "$1" "${2:-}"; info "skipped: $1 (${2:-already present})"; }
mark_fail()   { FAIL_LIST+=("$1"); FAIL_REASON+=("${2:-unknown error}"); record_line FAIL "$1" "${2:-}"; err "failed: $1 ${2:+- $2}"; }
mark_manual() { MANUAL_LIST+=("$1"); record_line MANUAL "$1" "${2:-}"; warn "manual step required: $1 ${2:+- $2}"; }

print_summary() {
  # When orchestrated by execute_all, it prints ONE combined, classified summary at
  # the very end; suppress the per-stage summary here to avoid mid-run clutter.
  [ -n "${MIGRATE_KEEP_RESULTS:-}" ] && return 0
  log "Summary"
  info "OK:     ${#OK_LIST[@]}"
  info "Skip:   ${#SKIP_LIST[@]}"
  info "Manual: ${#MANUAL_LIST[@]}"
  info "Failed: ${#FAIL_LIST[@]}"
  if [ "${#FAIL_LIST[@]}" -gt 0 ]; then
    warn "Failures (1-line reason each):"
    for i in "${!FAIL_LIST[@]}"; do err "  - ${FAIL_LIST[$i]}: ${FAIL_REASON[$i]}"; done
  fi
  if [ "${#MANUAL_LIST[@]}" -gt 0 ]; then
    warn "Need a manual step:"; for i in "${MANUAL_LIST[@]}"; do info "  - $i"; done
  fi
  print_launched_containers
  info "Full log: $RESULTS"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root.  Try:  sudo $0"
    exit 1
  fi
}

# The non-root user we should install Flatpak apps / write desktop files for,
# even though the script itself runs under sudo.
TARGET_USER="${SUDO_USER:-$(id -un)}"
TARGET_HOME="$(getent passwd "$TARGET_USER" 2>/dev/null | cut -d: -f6)"
[ -z "$TARGET_HOME" ] && TARGET_HOME="$HOME"

# =============================================================================
#  DISTRO + ARCHITECTURE DETECTION
# =============================================================================
FAMILY=""      # debian | rhel | suse | arch
PM=""          # apt | dnf | zypper | pacman
DISTRO_ID=""
DISTRO_NAME=""

detect_distro() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    DISTRO_ID="${ID:-}"
    DISTRO_NAME="${PRETTY_NAME:-${NAME:-$ID}}"
  fi
  local hay=" ${DISTRO_ID} ${ID_LIKE:-} "
  case "$hay" in
    *" debian "*|*" ubuntu "*|*" linuxmint "*|*" pop "*|*" zorin "*|*" elementary "*) FAMILY="debian"; PM="apt" ;;
    *" rhel "*|*" fedora "*|*" centos "*|*" rocky "*|*" almalinux "*|*" ol "*) FAMILY="rhel"; PM="dnf" ;;
    *" suse "*|*" opensuse "*|*" sles "*|*" sled "*) FAMILY="suse"; PM="zypper" ;;
    *" arch "*|*" archlinux "*|*" manjaro "*|*" endeavouros "*) FAMILY="arch"; PM="pacman" ;;
    *)
      # Fall back to whichever package manager actually exists.
      if   have_cmd apt-get; then FAMILY="debian"; PM="apt"
      elif have_cmd dnf;     then FAMILY="rhel";   PM="dnf"
      elif have_cmd zypper;  then FAMILY="suse";   PM="zypper"
      elif have_cmd pacman;  then FAMILY="arch";   PM="pacman"
      else err "Unsupported distribution: could not find apt/dnf/zypper/pacman."; exit 1
      fi ;;
  esac
}

ARCH=""        # x86_64 | aarch64 | armhf | other
detect_arch() {
  local m; m="$(uname -m)"
  case "$m" in
    x86_64|amd64)        ARCH="x86_64" ;;
    aarch64|arm64)       ARCH="aarch64" ;;
    armv7l|armhf|armv6l) ARCH="armhf" ;;
    *)                   ARCH="$m" ;;
  esac
}

# arch_supported "x86_64 aarch64"  ->  true if $ARCH is listed (empty list = all)
arch_supported() {
  local list="$1"
  [ -z "$list" ] && return 0
  case " $list " in *" $ARCH "*) return 0 ;; *) return 1 ;; esac
}

# =============================================================================
#  PACKAGE-MANAGER ABSTRACTION
# =============================================================================
_PM_REFRESHED=0
pm_refresh() {
  [ "$_PM_REFRESHED" = "1" ] && return 0
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get update -y ;;
    dnf)    dnf -y makecache ;;
    zypper) zypper --non-interactive refresh ;;
    pacman) pacman -Sy --noconfirm ;;
  esac
  _PM_REFRESHED=1
}

pm_install() {
  [ "$#" -eq 0 ] && return 0
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "$@" ;;
    dnf)    dnf install -y "$@" ;;
    zypper) zypper --non-interactive install -y --no-recommends "$@" ;;
    pacman) pacman -S --noconfirm --needed "$@" ;;
  esac
}

pm_installed() {
  case "$PM" in
    apt)    dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed" ;;
    dnf)    rpm -q "$1" >/dev/null 2>&1 ;;
    zypper) rpm -q "$1" >/dev/null 2>&1 ;;
    pacman) pacman -Q "$1" >/dev/null 2>&1 ;;
  esac
}

# =============================================================================
#  FLATPAK (universal app layer)
# =============================================================================
ensure_flatpak() {
  if ! have_cmd flatpak; then
    log "Installing Flatpak (required for the universal app layer)"
    pm_refresh
    pm_install flatpak || { mark_fail "flatpak" "could not install flatpak via $PM"; return 1; }
  fi
  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo >/dev/null 2>&1 || true
  return 0
}

flatpak_installed() { flatpak info "$1" >/dev/null 2>&1; }

install_flatpak() {  # install_flatpak APPID
  local id="$1"
  if flatpak_installed "$id"; then
    # Already present: update it if the user asked to update existing apps.
    [ "${MIGRATE_UPDATE_EXISTING:-no}" = "yes" ] && flatpak update -y --noninteractive "$id"
    return 0
  fi
  flatpak install -y --noninteractive flathub "$id"
}

# =============================================================================
#  SNAP (optional fallback)
# =============================================================================
ensure_snap() {
  have_cmd snap && return 0
  case "$PM" in
    apt)    pm_install snapd ;;
    dnf)    pm_install snapd && systemctl enable --now snapd.socket 2>/dev/null && ln -sf /var/lib/snapd/snap /snap 2>/dev/null ;;
    zypper) warn "snap on openSUSE needs the snappy repo; skipping snap fallback"; return 1 ;;
    pacman) warn "snap on Arch is via AUR; skipping snap fallback"; return 1 ;;
  esac
  have_cmd snap
}

# =============================================================================
#  DESKTOP / WEB-APP SHORTCUTS
# =============================================================================
detect_browser() {
  local b
  for b in google-chrome google-chrome-stable chromium chromium-browser microsoft-edge brave-browser firefox; do
    have_cmd "$b" && { printf '%s' "$b"; return 0; }
  done
  # Flatpak browsers
  if flatpak_installed com.google.Chrome; then printf 'flatpak run com.google.Chrome'; return 0; fi
  if flatpak_installed org.chromium.Chromium; then printf 'flatpak run org.chromium.Chromium'; return 0; fi
  if flatpak_installed com.microsoft.Edge; then printf 'flatpak run com.microsoft.Edge'; return 0; fi
  return 1
}

webapp_desktop() {  # webapp_desktop "Name" "URL"
  local name="$1" url="$2" browser appdir desktop slug
  browser="$(detect_browser)" || { mark_manual "$name" "no browser found for web-app shortcut ($url)"; return 1; }
  slug="$(printf '%s' "$name" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-')"
  appdir="$TARGET_HOME/.local/share/applications"
  mkdir -p "$appdir"
  desktop="$appdir/webapp-$slug.desktop"
  {
    printf '[Desktop Entry]\n'
    printf 'Version=1.0\nType=Application\n'
    printf 'Name=%s\n' "$name"
    printf 'Exec=%s --app=%s\n' "$browser" "$url"
    printf 'Terminal=false\nCategories=Network;WebBrowser;\n'
  } > "$desktop"
  chown "$TARGET_USER":"$TARGET_USER" "$desktop" 2>/dev/null || true
  chmod +x "$desktop" 2>/dev/null || true
  mark_ok "$name" "web-app shortcut -> $url"
}

# =============================================================================
#  DIRECT DOWNLOADS (.deb / .rpm / AppImage)
# =============================================================================
DOWNLOAD_DIR="${DOWNLOAD_DIR:-/tmp/migrate_to_linux_downloads}"
mkdir -p "$DOWNLOAD_DIR" 2>/dev/null || true

download_file() {  # download_file URL OUTPATH
  local url="$1" out="$2"
  if have_cmd curl; then curl -fL --retry 3 -o "$out" "$url"
  elif have_cmd wget; then wget -O "$out" "$url"
  else err "neither curl nor wget available"; return 1; fi
}

install_local_package() {  # install_local_package FILE
  local f="$1"
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y "$f" || { dpkg -i "$f"; apt-get -f install -y; } ;;
    dnf)    dnf install -y "$f" ;;
    zypper) zypper --non-interactive install -y --allow-unsigned-rpm "$f" ;;
    pacman) pacman -U --noconfirm "$f" ;;
  esac
}

# Best-effort install of a package matching a specific (Windows) version. Tries the
# major-version package name and an exact version pin. Returns 0 on success, 1 if no
# matching version could be installed (caller then falls back to latest). pacman is
# rolling-release, so version pinning is not supported there.
install_native_version() {  # install_native_version PKG WINVER
  local pkg="$1" ver="$2" major
  major="$(printf '%s' "$ver" | grep -oE '[0-9]+' | head -n1)"
  [ -z "$major" ] && return 1
  case "$PM" in
    apt)    capture pm_install "${pkg}-${major}" || capture pm_install "${pkg}=${ver}" ;;
    dnf)    capture pm_install "${pkg}${major}" || capture pm_install "${pkg}-${major}" || capture pm_install "${pkg}-${ver}" ;;
    zypper) capture pm_install "${pkg}${major}" || capture pm_install "${pkg}-${ver}" ;;
    pacman) return 1 ;;
  esac
}

# =============================================================================
#  install_app  --  the multi-strategy, Flatpak-first dispatcher
# -----------------------------------------------------------------------------
#  Usage (emitted by the generator):
#    install_app --name "VLC" --method flatpak --flatpak org.videolan.VLC \
#                --apt vlc --dnf vlc --zypper vlc --pacman vlc \
#                --arch "x86_64 aarch64"
#  Methods: flatpak | native | snap | webapp | docker | wine-bottles |
#           deb-url | github-deb | manual
# =============================================================================
install_app() {
  local name="" alt="" method="" flatpak="" snap_pkg="" arch_list="" winver="" is_security=0 is_paid=0
  local apt="" dnf="" zypper="" pacman=""
  local url_x86="" url_arm="" url_deb="" url_rpm="" webapp_url="" docker_image="" github_repo="" note=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --name)    name="$2"; shift 2 ;;
      --alt)     alt="$2"; shift 2 ;;
      --method)  method="$2"; shift 2 ;;
      --flatpak) flatpak="$2"; shift 2 ;;
      --snap)    snap_pkg="$2"; shift 2 ;;
      --apt)     apt="$2"; shift 2 ;;
      --dnf)     dnf="$2"; shift 2 ;;
      --zypper)  zypper="$2"; shift 2 ;;
      --pacman)  pacman="$2"; shift 2 ;;
      --arch)    arch_list="$2"; shift 2 ;;
      --winver)  winver="$2"; shift 2 ;;
      --url-x86) url_x86="$2"; shift 2 ;;
      --url-arm) url_arm="$2"; shift 2 ;;
      --url-deb) url_deb="$2"; shift 2 ;;
      --url-rpm) url_rpm="$2"; shift 2 ;;
      --webapp)  webapp_url="$2"; shift 2 ;;
      --docker)  docker_image="$2"; shift 2 ;;
      --github)  github_repo="$2"; shift 2 ;;
      --note)     note="$2"; shift 2 ;;
      --security) is_security=1; shift ;;
      --paid)     is_paid=1; shift ;;
      *) shift ;;
    esac
  done
  [ -z "$name" ] && return 0

  # Security-suite equivalents (antivirus/firewall, etc.) are only installed when the
  # user opted in; many skip them because Linux is hardened by default.
  if [ "$is_security" -eq 1 ] && [ "${MIGRATE_INSTALL_SECURITY:-no}" != "yes" ]; then
    mark_skip "$name" "security suite - not installed (opted out)"
    return 0
  fi

  # Free-only mode: this app's only alternative is paid. Ask whether to proceed.
  if [ "${MIGRATE_FREE_ONLY:-no}" = "yes" ] && [ "$is_paid" -eq 1 ]; then
    local _fans=""
    if [ -r /dev/tty ]; then
      printf '\n\n\033[1;33m==> %s%s has no free alternative.\033[0m\n' "$name" "${alt:+ ---> $alt}" >&3
      printf '  No free alternative exists for this application. Do you want to continue with the installation of the paid one? Answering with No means skipping this application (y/n): ' > /dev/tty
      read -r _fans < /dev/tty || _fans="n"
      case "$_fans" in [Yy]*) ;; *) mark_skip "$name" "paid - skipped (free-only mode)"; return 0 ;; esac
    else
      mark_skip "$name" "paid - skipped (free-only mode)"; return 0
    fi
  fi

  if ! arch_supported "$arch_list"; then
    mark_skip "$name" "not available for $ARCH"
    return 0
  fi

  if [ -n "$alt" ]; then
    printf '\n\n\033[1;34m==> Installing: %s   --->   %s\033[0m\n' "$name" "$alt" >&3
  else
    printf '\n\n\033[1;34m==> Installing: %s\033[0m\n' "$name" >&3
  fi
  [ -n "$note" ] && info "$note"

  # native package name for the running family
  local native_pkg=""
  case "$PM" in
    apt) native_pkg="$apt" ;; dnf) native_pkg="$dnf" ;;
    zypper) native_pkg="$zypper" ;; pacman) native_pkg="$pacman" ;;
  esac
  local slug; slug="$(slugify "$name")"

  # ---- single-path methods ----
  case "$method" in
    webapp)
      webapp_desktop "$name" "$webapp_url"; return 0 ;;
    docker)
      docker_launch_app "$name" "$docker_image" "$note"; return 0 ;;
    wine-bottles)
      if ensure_flatpak && capture install_flatpak com.usebottles.bottles; then
        mark_ok "$name" "via Bottles (flatpak) - configure the Windows app inside Bottles"
      else mark_fail "$name" "${LAST_ERR:-could not install Bottles (flatpak)}"; fi
      return 0 ;;
    manual)
      local mdir="${MIGRATE_MANUAL_DIR:-$DOWNLOAD_DIR/manual}/$slug" mf got=0
      if [ -d "$mdir" ] && [ -n "$(ls -A "$mdir" 2>/dev/null)" ]; then
        for mf in "$mdir"/*; do [ -f "$mf" ] && install_by_ext "$mf" && got=1; done
        if [ "$got" -eq 1 ]; then mark_ok "$name" "installed from staged file"
        else mark_fail "$name" "${LAST_ERR:-staged file could not be installed}"; fi
      else
        mark_manual "$name" "${note:-manual install}"
      fi
      return 0 ;;
  esac

  # Universal "already installed" short-circuit. Unless the user asked to update
  # existing apps to the LATEST version, an app that is already present is skipped
  # entirely here -- BEFORE any vendor repo setup or download happens. This applies
  # when "same version" was chosen OR when existing apps are not being updated.
  if [ "${MIGRATE_VERSION_MODE:-latest}" = "same" ] || [ "${MIGRATE_UPDATE_EXISTING:-no}" != "yes" ]; then
    if { [ -n "$native_pkg" ] && pm_installed "${native_pkg%% *}"; } \
       || { [ -n "$flatpak" ] && have_cmd flatpak && flatpak_installed "$flatpak"; } \
       || { [ -n "$snap_pkg" ] && have_cmd snap && snap list "${snap_pkg%% *}" >/dev/null 2>&1; }; then
      mark_skip "$name" "already installed"
      return 0
    fi
  fi

  # ---- multi-backend methods (req: try every available pm until one works) ----
  # The declared method goes first; then EVERY other available backend is tried as a
  # fallback (native / flatpak / snap / direct-download) before the app is failed.
  local order
  case "$method" in
    flatpak)            order="flatpak native snap deburl" ;;
    native)             order="native flatpak snap deburl" ;;
    snap)               order="snap flatpak native deburl" ;;
    deb-url|github-deb) order="deburl native flatpak snap" ;;
    *)                  order="flatpak native snap deburl" ;;
  esac

  local b url f rfn
  LAST_ERR=""   # so an empty value after the loop means "nothing was even attempted"
  for b in $order; do
    case "$b" in
      flatpak)
        [ -n "$flatpak" ] || continue
        ensure_flatpak || continue
        if capture install_flatpak "$flatpak"; then mark_ok "$name" "flatpak $flatpak"; return 0; fi ;;
      native)
        [ -n "$native_pkg" ] || continue
        # vendor's own repo first, for the latest upstream build (if defined).
        rfn="repo_setup_$(printf '%s' "$slug" | tr '-' '_')"
        if declare -F "$rfn" >/dev/null 2>&1; then
          info "configuring vendor repository for $name ..."
          "$rfn" || warn "vendor repo setup failed; falling back to the distro repo"
        fi
        pm_refresh
        # Skip if present, UNLESS the user asked to update existing apps (then
        # pm_install upgrades it to the latest available).
        if pm_installed "${native_pkg%% *}" && [ "${MIGRATE_UPDATE_EXISTING:-no}" != "yes" ]; then
          mark_skip "$name" "already installed"; return 0
        fi
        # match the Windows version when the user chose "same version".
        if [ "${MIGRATE_VERSION_MODE:-latest}" = "same" ] && [ -n "$winver" ]; then
          if install_native_version "$native_pkg" "$winver"; then mark_ok "$name" "native $native_pkg (matched Windows $winver)"; return 0; fi
          warn "could not match Windows version $winver; installing latest"
        fi
        if capture pm_install $native_pkg; then mark_ok "$name" "native $native_pkg"; return 0; fi ;;
      snap)
        [ -n "$snap_pkg" ] || continue
        ensure_snap || continue
        if capture snap install $snap_pkg; then mark_ok "$name" "snap $snap_pkg"; return 0; fi ;;
      deburl)
        [ -n "$url_x86$url_arm$url_deb$url_rpm" ] || continue
        # Prefer the package format matching the distro family (.deb on apt, .rpm on
        # dnf/zypper); fall back to the arch-keyed URLs when no format-specific one fits.
        url=""
        case "$PM" in apt) url="$url_deb" ;; dnf|zypper) url="$url_rpm" ;; esac
        [ -n "$url" ] || { url="$url_x86"; [ "$ARCH" = "aarch64" ] && [ -n "$url_arm" ] && url="$url_arm"; }
        [ -n "$url" ] || continue
        f="$DOWNLOAD_DIR/${name// /_}.pkg"
        if capture download_file "$url" "$f" && capture install_local_package "$f"; then mark_ok "$name" "downloaded package"; return 0; fi ;;
    esac
  done

  # A real install error -> report failure. But if nothing was even attempted (no
  # package-manager route on this distro), show that and fall back to the manual
  # download-by-user scheme (place the file, then done/skip, handled by extension).
  if [ -n "$LAST_ERR" ]; then
    mark_fail "$name" "$LAST_ERR"
  else
    err "no available package manager could install it"
    manual_fallback "$name" "$alt" "$note" "$webapp_url$url_x86$github_repo"
  fi
}

# Manual download-by-user fallback for an app no package manager could install.
# Prompts the user to download + place the installer; handles it by extension; loops
# until a valid file is placed ('done') or the user skips. Marks the result.
manual_fallback() {  # manual_fallback NAME [ALT] [NOTE] [URL]
  local name="$1" alt="$2" mnote="$3" murl="$4"
  local base="${MIGRATE_MANUAL_DIR:-$DOWNLOAD_DIR/manual}"
  local slug dir ans f got
  slug="$(slugify "$name")"; dir="$base/$slug"; mkdir -p "$dir"
  [ -n "$mnote" ] && info "$mnote"
  [ -n "$murl" ] && info "More info / download: $murl"
  info "Download the installer yourself and place it (keep its original file name) in:"
  info "    $dir"
  info "Then type 'done' (handled by extension: .deb/.rpm/.sh/.run/.bin/.bundle/.AppImage/.tar.gz/.zip/...); 'skip' to skip."
  if [ ! -r /dev/tty ]; then mark_manual "$name" "no package manager route - needs manual download"; return 0; fi
  while :; do
    printf '  %s (done/skip): ' "$name" > /dev/tty
    read -r ans < /dev/tty || ans="skip"
    case "$ans" in
      [Ss]|[Ss][Kk][Ii][Pp]) mark_skip "$name" "user skipped"; return 0 ;;
      [Dd]|[Dd][Oo][Nn][Ee])
        if [ -z "$(ls -A "$dir" 2>/dev/null)" ]; then
          printf '\033[1;31m  No file found in %s -- place the file there, then type done (or skip).\033[0m\n' "$dir" > /dev/tty; continue
        fi
        got=0; LAST_ERR=""
        for f in "$dir"/*; do [ -f "$f" ] || continue; install_by_ext "$f" && got=1; done
        if [ "$got" -eq 1 ]; then mark_ok "$name" "installed from $dir"; return 0
        else printf '\033[1;31m  %s -- fix the file in %s, then type done (or skip).\033[0m\n' "${LAST_ERR:-could not handle the file}" "$dir" > /dev/tty; fi
        ;;
      *) printf '\033[1;31m  Please type "done" or "skip".\033[0m\n' > /dev/tty ;;
    esac
  done
}

# Install the Nth-best alternative of an app only if the user asked for at least
# N alternatives (MIGRATE_ALT_LIMIT, default 1). Usage:  app_alt RANK install_app ...
app_alt() {
  local rank="$1"; shift
  local limit="${MIGRATE_ALT_LIMIT:-1}"
  case "$limit" in ''|*[!0-9]*) limit=1 ;; esac
  if [ "$rank" -le "$limit" ]; then "$@"; fi
  return 0
}

# Handle a user-downloaded installer FILE according to its extension. Returns 0 on
# success, 1 on failure (LAST_ERR holds a 1-line reason). Used by the manual phase.
install_by_ext() {  # install_by_ext FILE
  local f="$1"
  case "$f" in
    *.deb|*.rpm|*.pkg.tar.zst|*.pkg.tar.xz|*.pkg.tar)
      capture install_local_package "$f" ;;
    *.sh)
      chmod +x "$f" 2>/dev/null; capture bash "$f" ;;
    *.run|*.bin|*.bundle)
      chmod +x "$f" 2>/dev/null; capture "$f" ;;
    *.appimage|*.AppImage)
      chmod +x "$f" 2>/dev/null
      mkdir -p /opt/migrate_appimages
      if cp -f "$f" /opt/migrate_appimages/ 2>/dev/null; then return 0
      else LAST_ERR="could not place AppImage in /opt/migrate_appimages"; return 1; fi ;;
    *.tar.gz|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar)
      mkdir -p "${f%/*}/extracted"
      capture tar -xf "$f" -C "${f%/*}/extracted" ;;
    *.zip)
      if ! have_cmd unzip; then LAST_ERR="unzip is not installed"; return 1; fi
      mkdir -p "${f%/*}/extracted"
      capture unzip -o "$f" -d "${f%/*}/extracted" ;;
    *)
      LAST_ERR="unsupported file type: .${f##*.}"; return 1 ;;
  esac
}

ensure_docker() {
  have_cmd docker && return 0
  pm_refresh
  case "$PM" in
    apt)    pm_install docker.io ;;
    dnf)    pm_install moby-engine || pm_install docker ;;
    zypper) pm_install docker ;;
    pacman) pm_install docker ;;
  esac
  have_cmd docker && systemctl enable --now docker 2>/dev/null
  have_cmd docker
}

# =============================================================================
#  DOCKER CONTAINER LAUNCHING  (apps whose Linux equivalent IS a container)
# -----------------------------------------------------------------------------
#  For each app with install.method=docker we pull the image, attach it to ONE
#  shared bridge network, and start a container with sensible defaults. Host
#  ports are taken from the image's EXPOSED ports and bumped by 1 on conflict.
#  If a container for the same image already exists, we just (re)start it instead
#  of creating a duplicate. These are NOT the images migrated from Windows Docker
#  (those are handled separately by docker_rebuild.sh).
# =============================================================================
DOCKER_NET="${DOCKER_NET:-migrate-bridge}"

ensure_docker_net() {
  docker network inspect "$DOCKER_NET" >/dev/null 2>&1 && return 0
  capture docker network create --driver bridge "$DOCKER_NET" >/dev/null 2>&1 || \
    docker network create --driver bridge "$DOCKER_NET" >/dev/null 2>&1
}

# Track host ports assigned during this run; combined with live listener checks.
_MIGRATE_PORTS_TAKEN=""
_port_in_use() {  # _port_in_use PORT
  local p="$1"
  case " $_MIGRATE_PORTS_TAKEN " in *" $p "*) return 0 ;; esac
  if have_cmd ss; then
    ss -ltnH 2>/dev/null | awk '{print $4}' | sed 's/.*[:.]//' | grep -qx "$p" && return 0
  elif have_cmd netstat; then
    netstat -ltn 2>/dev/null | awk 'NR>2{print $4}' | sed 's/.*[:.]//' | grep -qx "$p" && return 0
  fi
  return 1
}
_pick_port() {  # _pick_port DESIRED -> free host port (incrementing on conflict)
  local p="$1"
  [ -z "$p" ] && { printf ''; return 0; }
  while _port_in_use "$p"; do p=$((p + 1)); done
  _MIGRATE_PORTS_TAKEN="$_MIGRATE_PORTS_TAKEN $p"
  printf '%s' "$p"
}

# Human-readable "how to use" line derived from the container's published ports.
_docker_howto() {  # _docker_howto CONTAINER NOTE
  local c="$1" note="$2" hp howto
  hp="$(docker port "$c" 2>/dev/null | sed -n 's/.*:\([0-9]\{1,\}\)$/\1/p' | head -n1)"
  if [ -n "$hp" ]; then howto="open http://localhost:${hp} in your browser"
  else howto="attach with: docker exec -it ${c} sh"; fi
  howto="${howto}; start/stop with: docker start ${c} / docker stop ${c}"
  [ -n "$note" ] && howto="${howto} (${note})"
  printf '%s' "$howto"
}

# Record a launched container ONCE (one line per container, deduped by name).
_record_launched() {  # _record_launched WINAPP IMAGE CONTAINER NOTE
  local winapp="$1" image="$2" c="$3" note="$4"
  if [ -f "$DOCKER_LAUNCHED" ] && cut -f3 "$DOCKER_LAUNCHED" 2>/dev/null | grep -qx "$c"; then return 0; fi
  printf '%s\t%s\t%s\t%s\n' "$winapp" "$image" "$c" "$(_docker_howto "$c" "$note")" >> "$DOCKER_LAUNCHED"
}

docker_launch_app() {  # docker_launch_app WINAPP IMAGE NOTE
  local winapp="$1" image="$2" note="$3"
  [ -z "$image" ] && { mark_fail "$winapp" "no docker image specified"; return 0; }
  if ! ensure_docker; then mark_fail "$winapp" "docker is not available"; return 0; fi
  docker info >/dev/null 2>&1 || systemctl start docker 2>/dev/null || true

  # Stable container name derived from the image (so the SAME image always maps to
  # the SAME container -> reuse instead of duplicate).
  local base cname
  base="${image##*/}"; base="${base%%:*}"
  cname="migrate-$(slugify "$base")"

  # Already created (this run or a previous one)? Just start it if stopped; never
  # create a second container for the same image.
  if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "$cname"; then
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "$cname"; then
      info "container already running: $cname"
    else
      capture docker start "$cname" >/dev/null 2>&1 || docker start "$cname" >/dev/null 2>&1 || true
    fi
    _record_launched "$winapp" "$image" "$cname" "$note"
    mark_ok "$winapp" "using existing container: $cname"
    return 0
  fi

  if ! capture docker pull "$image"; then mark_fail "$winapp" "${LAST_ERR:-could not pull docker image $image}"; return 0; fi
  ensure_docker_net

  # Map each EXPOSED container port to a free host port (incrementing on conflict).
  local pflags="" ep cport hport
  for ep in $(docker image inspect --format '{{range $p,$_ := .Config.ExposedPorts}}{{$p}} {{end}}' "$image" 2>/dev/null); do
    cport="${ep%%/*}"
    [ -z "$cport" ] && continue
    hport="$(_pick_port "$cport")"
    [ -n "$hport" ] && pflags="$pflags -p ${hport}:${cport}"
  done

  # shellcheck disable=SC2086
  if capture docker run -d --name "$cname" --network "$DOCKER_NET" --restart unless-stopped $pflags "$image"; then
    _record_launched "$winapp" "$image" "$cname" "$note"
    mark_ok "$winapp" "container launched: $cname"
  else
    mark_fail "$winapp" "${LAST_ERR:-could not start container for $image}"
  fi
}

# Purple "Launched containers" section (one line per container). Printed at the end
# of a run by execute_all (orchestrated) or print_summary (standalone stage).
print_launched_containers() {
  local f="${DOCKER_LAUNCHED:-/tmp/migrate_to_linux_launched.tsv}"
  [ -s "$f" ] || return 0
  printf '\n' >&3
  printf '        \033[1;35m===== Launched containers =====\033[0m\n' >&3
  local winapp image cname howto
  while IFS="$(printf '\t')" read -r winapp image cname howto; do
    [ -z "$cname" ] && continue
    info "          ${winapp}  --> image:'${image}' | container: '${cname}' | How to use: ${howto}"
  done < "$f"
}


main() {
  require_root
  detect_distro
  detect_arch
  MODULE="Applications"
  log "Migrate to Linux  --  Must-Have Software"
  info "Distribution : ${DISTRO_NAME}"
  info "Family / pm  : ${FAMILY} / ${PM}"
  info "Architecture : ${ARCH}"
  pm_refresh
  ensure_flatpak || warn "Flatpak unavailable -- Flatpak-only apps will be skipped."

  # ---------------------------------------------------------------------------
  # Application install list (generated from B_applications.json + the
  # Additional_Manual_Linux_Software_Requirments.csv).
  # ---------------------------------------------------------------------------
  repo_setup_docker_desktop() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      . /etc/os-release
      docker_base=debian
      case " ${ID:-} ${ID_LIKE:-} " in *ubuntu*) docker_base=ubuntu ;; esac
      docker_suite="${UBUNTU_CODENAME:-${VERSION_CODENAME:-stable}}"
      curl -fsSL "https://download.docker.com/linux/${docker_base}/gpg" | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${docker_base} ${docker_suite} stable" > /etc/apt/sources.list.d/docker.list
      ;;
    dnf)
      dnf -y install dnf-plugins-core
      dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      ;;
  esac
}
repo_setup_docker_engine() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      . /etc/os-release
      docker_base=debian
      case " ${ID:-} ${ID_LIKE:-} " in *ubuntu*) docker_base=ubuntu ;; esac
      docker_suite="${UBUNTU_CODENAME:-${VERSION_CODENAME:-stable}}"
      curl -fsSL "https://download.docker.com/linux/${docker_base}/gpg" | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${docker_base} ${docker_suite} stable" > /etc/apt/sources.list.d/docker.list
      ;;
    dnf)
      dnf -y install dnf-plugins-core
      dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      ;;
  esac
}
repo_setup_google_chrome() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --batch --yes --dearmor -o /etc/apt/keyrings/google-chrome.gpg
      echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      ;;
    dnf)
      printf '%s\n' '[google-chrome]' 'name=google-chrome' 'baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64' 'enabled=1' 'gpgcheck=1' 'gpgkey=https://dl.google.com/linux/linux_signing_key.pub' > /etc/yum.repos.d/google-chrome.repo
      ;;
  esac
}
repo_setup_microsoft_edge() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --batch --yes --dearmor -o /etc/apt/keyrings/microsoft.gpg
      echo "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list
      ;;
    dnf)
      rpm --import https://packages.microsoft.com/keys/microsoft.asc
      printf '%s\n' '[microsoft-edge]' 'name=microsoft-edge' 'baseurl=https://packages.microsoft.com/yumrepos/edge' 'enabled=1' 'gpgcheck=1' 'gpgkey=https://packages.microsoft.com/keys/microsoft.asc' > /etc/yum.repos.d/microsoft-edge.repo
      ;;
  esac
}
repo_setup_nodejs() {
  case "$PM" in
    apt)
      curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      ;;
    dnf)
      curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
      ;;
  esac
}
repo_setup_postgresql() {
  case "$PM" in
    apt)
      install -d /usr/share/postgresql-common/pgdg
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
      . /etc/os-release
      echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main" > /etc/apt/sources.list.d/pgdg.list
      ;;
    dnf)
      dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      ;;
  esac
}
repo_setup_visual_studio_code() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --batch --yes --dearmor -o /etc/apt/keyrings/microsoft.gpg
      echo "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
      ;;
    dnf)
      rpm --import https://packages.microsoft.com/keys/microsoft.asc
      printf '%s\n' '[code]' 'name=Visual Studio Code' 'baseurl=https://packages.microsoft.com/yumrepos/vscode' 'enabled=1' 'gpgcheck=1' 'gpgkey=https://packages.microsoft.com/keys/microsoft.asc' > /etc/yum.repos.d/vscode.repo
      ;;
  esac
}
  app_alt 1 install_app --name "ABBYY FineReader PDF" --alt "Tesseract OCR + gImageReader" --method flatpak --flatpak "io.github.manisandro.gImageReader" --apt "gimagereader" --dnf "gimagereader"
  app_alt 1 install_app --name "Acronis Cyber Protect / True Image" --alt "Clonezilla" --method native --apt "clonezilla" --note "Clonezilla; also a bootable ISO from clonezilla.org"
  app_alt 1 install_app --name "Adobe Acrobat Pro" --alt "Stirling PDF" --method deb-url --url-deb "https://files.stirlingpdf.com/linux-installer.deb" --url-rpm "https://files.stirlingpdf.com/linux-installer.rpm" --note "Native Stirling-PDF install (.deb on apt families, .rpm on dnf/zypper); runs as a local service, web UI on http://localhost:8080 once started."
  app_alt 1 install_app --name "Adobe Audition" --alt "Audacity" --method flatpak --flatpak "org.audacityteam.Audacity" --apt "audacity" --dnf "audacity" --zypper "audacity" --pacman "audacity"
  app_alt 1 install_app --name "Adobe Digital Editions 4.5" --alt "calibre" --method flatpak --flatpak "com.calibre_ebook.calibre" --apt "calibre" --dnf "calibre" --zypper "calibre" --pacman "calibre"
  app_alt 2 install_app --name "Adobe Digital Editions 4.5" --alt "Thorium Reader" --method flatpak --note "needs manifest enrichment - see https://www.edrlab.org/software/thorium-reader/"
  app_alt 1 install_app --name "Adobe Dreamweaver" --alt "Visual Studio Code" --method flatpak --flatpak "com.visualstudio.code"
  app_alt 1 install_app --name "Adobe InDesign" --alt "Scribus" --method flatpak --flatpak "net.scribus.Scribus" --apt "scribus" --dnf "scribus" --zypper "scribus" --pacman "scribus"
  app_alt 1 install_app --name "Adobe Lightroom / Lightroom Classic" --alt "darktable" --method flatpak --flatpak "org.darktable.Darktable" --apt "darktable" --dnf "darktable" --zypper "darktable" --pacman "darktable"
  app_alt 1 install_app --name "Advanced IP Scanner" --alt "Angry IP Scanner" --method manual --url-x86 "https://github.com/angryip/ipscan/releases" --note "Angry IP Scanner .deb/.rpm (needs Java)"
  app_alt 1 install_app --name "Advanced Port Scanner" --alt "RustScan + nmap" --method native --apt "nmap" --dnf "nmap" --zypper "nmap" --pacman "nmap" --note "GUI: also install zenmap"
  app_alt 1 install_app --name "AIDA64 / CPU-Z / GPU-Z / HWiNFO" --alt "CPU-X" --method flatpak --flatpak "io.github.thetumultuousunicornofdarkness.CPU-X" --dnf "cpu-x" --pacman "cpu-x"
  app_alt 1 install_app --name "Alarms & Clock" --alt "GNOME Clocks" --method flatpak --flatpak "org.gnome.clocks" --apt "gnome-clocks" --dnf "gnome-clocks" --pacman "gnome-clocks"
  app_alt 1 install_app --name "Anki Launcher" --alt "Anki (Linux)" --winver "25.09" --method flatpak --flatpak "net.ankiweb.Anki"
  app_alt 1 install_app --name "Any Video Converter (AVC)" --alt "HandBrake" --method flatpak --flatpak "fr.handbrake.ghb" --apt "handbrake" --dnf "HandBrake" --pacman "handbrake"
  app_alt 1 install_app --name "AnyDesk" --alt "AnyDesk (Linux)" --method flatpak --flatpak "com.anydesk.Anydesk"
  app_alt 1 install_app --name "Autodesk 3ds Max" --alt "Blender" --method flatpak --flatpak "org.blender.Blender" --apt "blender" --dnf "blender" --zypper "blender" --pacman "blender"
  app_alt 1 install_app --name "Autodesk Fusion 360" --alt "FreeCAD" --method flatpak --flatpak "org.freecad.FreeCAD" --apt "freecad" --dnf "freecad" --zypper "freecad" --pacman "freecad"
  app_alt 1 install_app --name "Babylon" --alt "GoldenDict" --method native --apt "goldendict" --dnf "goldendict" --zypper "goldendict" --pacman "goldendict"
  app_alt 1 install_app --name "Bandicam" --alt "OBS Studio" --method flatpak --flatpak "com.obsproject.Studio" --apt "obs-studio" --dnf "obs-studio" --pacman "obs-studio"
  app_alt 1 install_app --name "Bitvise SSH Client" --alt "OpenSSH" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  app_alt 1 install_app --name "calibre" --alt "calibre (Linux)" --winver "9.5.0" --method flatpak --flatpak "com.calibre_ebook.calibre" --apt "calibre" --dnf "calibre" --zypper "calibre" --pacman "calibre"
  app_alt 1 install_app --name "Camtasia" --alt "OBS Studio + Kdenlive" --method flatpak --flatpak "com.obsproject.Studio" --apt "obs-studio" --note "also install Kdenlive (org.kde.kdenlive) for editing"
  app_alt 1 install_app --name "CCleaner" --alt "BleachBit" --method flatpak --flatpak "org.bleachbit.BleachBit" --apt "bleachbit" --dnf "bleachbit" --zypper "bleachbit" --pacman "bleachbit"
  app_alt 1 install_app --name "CMake" --alt "CMake (Linux)" --winver "4.3.0" --method native --apt "cmake" --dnf "cmake" --zypper "cmake" --pacman "cmake"
  app_alt 1 install_app --name "CorelDRAW Graphics Suite" --alt "Inkscape" --method flatpak --flatpak "org.inkscape.Inkscape" --apt "inkscape" --dnf "inkscape" --zypper "inkscape" --pacman "inkscape"
  app_alt 1 install_app --name "DBeaver Ultimate" --alt "DBeaver (Linux)" --method flatpak --flatpak "io.dbeaver.DBeaverCommunity"
  app_alt 1 install_app --name "Discord" --alt "Discord (Linux)" --method flatpak --flatpak "com.discordapp.Discord"
  app_alt 1 install_app --name "Docker Desktop" --alt "Docker Engine (native)" --winver "4.70.0" --method native --apt "docker-ce docker-ce-cli containerd.io docker-compose-plugin" --dnf "docker-ce docker-ce-cli containerd.io docker-compose-plugin" --zypper "docker" --pacman "docker" --note "systemctl enable --now docker; add your user to the docker group"
  app_alt 1 install_app --name "Docker Engine" --alt "Docker Engine (native, no VM)" --method native --apt "docker-ce docker-ce-cli containerd.io docker-compose-plugin" --dnf "docker-ce docker-ce-cli containerd.io docker-compose-plugin" --zypper "docker" --pacman "docker" --note "systemctl enable --now docker; add your user to the docker group"
  app_alt 1 install_app --name "Dropbox" --alt "Dropbox (Linux)" --method flatpak --flatpak "com.dropbox.Client"
  app_alt 1 install_app --name "DVDFab" --alt "MakeMKV" --method flatpak --flatpak "com.makemkv.MakeMKV"
  app_alt 1 install_app --name "EaseUS Data Recovery Wizard" --alt "TestDisk + PhotoRec" --method native --apt "testdisk" --dnf "testdisk" --zypper "testdisk" --pacman "testdisk" --note "includes PhotoRec"
  app_alt 1 install_app --name "EaseUS Partition Master" --alt "GParted" --method native --apt "gparted" --dnf "gparted" --zypper "gparted" --pacman "gparted"
  app_alt 1 install_app --name "EaseUS Todo Backup" --alt "Timeshift" --method native --apt "timeshift" --dnf "timeshift" --pacman "timeshift"
  app_alt 2 install_app --name "EaseUS Todo Backup" --alt "DÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â©jÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â  Dup (GNOME Backups)" --method native --note "needs manifest enrichment - see https://wiki.gnome.org/Apps/DejaDup"
  app_alt 1 install_app --name "EndNote" --alt "Zotero" --method flatpak --flatpak "org.zotero.Zotero"
  app_alt 1 install_app --name "FlashBack Pro" --alt "OBS Studio + Kdenlive" --method flatpak --flatpak "com.obsproject.Studio" --apt "obs-studio"
  app_alt 1 install_app --name "Git" --alt "Git (Linux)" --winver "2.54.0" --method native --apt "git" --dnf "git" --zypper "git" --pacman "git"
  app_alt 1 install_app --name "GitHub Desktop" --alt "GitKraken" --method flatpak --flatpak "com.axosoft.GitKraken"
  app_alt 1 install_app --name "Glary Utilities" --alt "Stacer" --method flatpak --flatpak "com.github.oguzhaninan.Stacer" --apt "stacer"
  app_alt 1 install_app --name "GnuWin32: Grep" --alt "GNU grep (native)" --method native --apt "grep" --dnf "grep" --zypper "grep" --pacman "grep"
  app_alt 1 install_app --name "Google Chrome" --alt "Google Chrome (Linux)" --method native --flatpak "com.google.Chrome" --apt "google-chrome-stable" --dnf "google-chrome-stable"
  app_alt 1 install_app --name "Google Drive" --alt "Insync" --method manual --url-x86 "https://www.insynchq.com/downloads" --note "Insync (.deb/.rpm) from insynchq.com; FOSS alt: rclone / google-drive-ocamlfuse" --paid
  app_alt 1 install_app --name "Grammarly for Windows" --alt "LanguageTool" --method manual --note "LanguageTool: run via Docker (erikvl87/languagetool) or use the browser extension"
  app_alt 1 install_app --name "Hotspot Shield" --alt "Hotspot Shield (Linux)" --method manual --note "No official Linux client; use Proton VPN or OpenVPN instead"
  app_alt 1 install_app --name "IBM SPSS Statistics" --alt "PSPP" --method native --apt "pspp" --dnf "pspp"
  app_alt 1 install_app --name "Internet Download Manager (IDM)" --alt "uGet" --method native --apt "uget" --dnf "uget" --pacman "uget" --note "also install aria2 for multi-connection downloads"
  app_alt 1 install_app --name "IObit Advanced SystemCare" --alt "BleachBit" --method flatpak --flatpak "org.bleachbit.BleachBit" --apt "bleachbit"
  app_alt 1 install_app --name "IObit Malware Fighter" --alt "ClamAV / ClamTk" --method native --apt "clamtk" --dnf "clamtk" --pacman "clamtk" --security
  app_alt 1 install_app --name "IObit Uninstaller" --alt "Synaptic Package Manager" --method native --apt "synaptic" --note "Synaptic is APT-only; use your distro's software center elsewhere"
  app_alt 1 install_app --name "Java 8" --alt "OpenJDK (Eclipse Temurin)" --winver "8.0.4910.10" --method native --apt "default-jdk" --dnf "java-latest-openjdk" --zypper "java-openjdk" --pacman "jdk-openjdk"
  app_alt 1 install_app --name "KMPlayer" --alt "VLC Media Player" --method flatpak --flatpak "org.videolan.VLC" --apt "vlc" --dnf "vlc" --zypper "vlc" --pacman "vlc"
  app_alt 1 install_app --name "LanguageTool (Grammarly Alternative)" --alt "LanguageTool Desktop" --method manual --note "LanguageTool Desktop: run via Docker (erikvl87/languagetool) or browser extension"
  app_alt 1 install_app --name "Lenovo Professional Wireless Rechargeable Combo" --alt "Solaar" --method flatpak --flatpak "io.github.pwr_solaar.solaar" --apt "solaar" --dnf "solaar" --pacman "solaar"
  app_alt 1 install_app --name "Lightshot" --alt "Flameshot" --method flatpak --flatpak "org.flameshot.Flameshot" --apt "flameshot" --dnf "flameshot" --zypper "flameshot" --pacman "flameshot"
  app_alt 1 install_app --name "Longman Dictionary of Contemporary English 5th Edition" --alt "GoldenDict / GoldenDict-ng" --method native --apt "goldendict" --dnf "goldendict" --zypper "goldendict" --pacman "goldendict"
  app_alt 1 install_app --name "Malwarebytes" --alt "ClamAV + ClamTk" --method native --apt "clamtk" --dnf "clamtk" --pacman "clamtk" --security
  app_alt 1 install_app --name "Microsoft .NET SDK" --alt ".NET SDK (Linux)" --winver "40.11.22621" --method snap --snap "dotnet-sdk --classic" --note "or use your distro's dotnet-sdk / Microsoft repo"
  app_alt 1 install_app --name "Microsoft 365 / Office" --alt "LibreOffice" --method flatpak --flatpak "org.libreoffice.LibreOffice" --apt "libreoffice" --dnf "libreoffice" --zypper "libreoffice" --pacman "libreoffice"
  app_alt 1 install_app --name "Microsoft Access" --alt "LibreOffice Base" --method flatpak --flatpak "org.libreoffice.LibreOffice" --apt "libreoffice-base" --dnf "libreoffice-base"
  app_alt 1 install_app --name "Microsoft Edge" --alt "Microsoft Edge (Linux)" --method native --flatpak "com.microsoft.Edge" --apt "microsoft-edge-stable" --dnf "microsoft-edge-stable"
  app_alt 1 install_app --name "Microsoft OneDrive" --alt "onedrive (abraunegg)" --method native --apt "onedrive" --dnf "onedrive" --pacman "onedrive"
  app_alt 1 install_app --name "Microsoft Publisher" --alt "Scribus" --method flatpak --flatpak "net.scribus.Scribus" --apt "scribus"
  app_alt 1 install_app --name "Microsoft Visio" --alt "draw.io / Diagrams.net" --method flatpak --flatpak "com.jgraph.drawio.desktop"
  app_alt 1 install_app --name "Microsoft Whiteboard" --alt "Excalidraw" --method webapp --webapp "https://excalidraw.com"
  app_alt 1 install_app --name "MiKTeX" --alt "TeX Live" --method native --apt "texlive" --dnf "texlive-scheme-basic" --zypper "texlive" --pacman "texlive-core" --note "install the -full variants for everything"
  app_alt 1 install_app --name "MobaXterm" --alt "Built-in terminal + OpenSSH" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  app_alt 1 install_app --name "Movavi Screen Recorder" --alt "OBS Studio" --method flatpak --flatpak "com.obsproject.Studio" --apt "obs-studio"
  app_alt 1 install_app --name "Movavi Video Converter" --alt "HandBrake" --method flatpak --flatpak "fr.handbrake.ghb" --apt "handbrake"
  app_alt 1 install_app --name "Movavi Video Editor" --alt "Kdenlive" --method flatpak --flatpak "org.kde.kdenlive" --apt "kdenlive" --dnf "kdenlive" --pacman "kdenlive"
  app_alt 1 install_app --name "Mozilla Firefox" --alt "Firefox (Linux)" --winver "152.0" --method flatpak --flatpak "org.mozilla.firefox" --apt "firefox" --dnf "firefox" --zypper "MozillaFirefox" --pacman "firefox"
  app_alt 1 install_app --name "MS Teams" --alt "Teams PWA (Edge/Chrome)" --method webapp --webapp "https://teams.microsoft.com"
  app_alt 1 install_app --name "MSI Afterburner" --alt "GOverlay + MangoHud" --method flatpak --flatpak "io.github.benjamimgois.goverlay" --apt "goverlay" --note "MangoHud overlay/limiter"
  app_alt 1 install_app --name "Nearby Share / Quick Share" --alt "LocalSend" --method flatpak --flatpak "org.localsend.localsend_app"
  app_alt 1 install_app --name "Nero Burning ROM / Nero Platinum" --alt "K3b" --method flatpak --flatpak "org.kde.k3b" --apt "k3b" --dnf "k3b" --pacman "k3b"
  app_alt 1 install_app --name "ninja" --alt "ninja-build (Linux)" --winver "1.13.2" --method native --apt "ninja-build" --dnf "ninja-build" --zypper "ninja" --pacman "ninja"
  app_alt 1 install_app --name "Nitro PDF Pro" --alt "Stirling PDF" --method deb-url --url-deb "https://files.stirlingpdf.com/linux-installer.deb" --url-rpm "https://files.stirlingpdf.com/linux-installer.rpm" --note "Native Stirling-PDF install (.deb on apt families, .rpm on dnf/zypper); runs as a local service, web UI on http://localhost:8080 once started."
  app_alt 1 install_app --name "Node.js" --alt "Node.js (Linux)" --winver "24.15.0" --method native --apt "nodejs" --dnf "nodejs" --zypper "nodejs npm" --pacman "nodejs npm"
  app_alt 1 install_app --name "Notepad++" --alt "Notepadqq" --method native --apt "notepadqq" --note "alt: install 'code' or a GNOME/KDE editor"
  app_alt 1 install_app --name "oCam Screen Recorder" --alt "OBS Studio" --method flatpak --flatpak "com.obsproject.Studio" --apt "obs-studio"
  app_alt 1 install_app --name "oCam version 550.0" --alt "OBS Studio" --method flatpak --flatpak "com.obsproject.Studio" --apt "obs-studio"
  app_alt 1 install_app --name "OpenSSH" --alt "OpenSSH (native)" --winver "8.9.1.0" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  app_alt 1 install_app --name "OpenSSL" --alt "OpenSSL (native)" --winver "3.3.0" --method native --apt "openssl" --dnf "openssl" --zypper "openssl" --pacman "openssl"
  app_alt 1 install_app --name "OpenVPN Connect" --alt "OpenVPN Connect (Linux)" --method native --apt "openvpn" --dnf "openvpn" --zypper "openvpn" --pacman "openvpn" --note "GUI: network-manager-openvpn"
  app_alt 1 install_app --name "Origin / OriginPro" --alt "LabPlot" --method flatpak --flatpak "org.kde.labplot2"
  app_alt 1 install_app --name "Outlook For Windows" --alt "Thunderbird" --method flatpak --flatpak "org.mozilla.Thunderbird" --apt "thunderbird" --dnf "thunderbird" --zypper "MozillaThunderbird" --pacman "thunderbird"
  app_alt 1 install_app --name "Paint" --alt "Pinta" --method flatpak --flatpak "com.github.PintaProject.Pinta" --apt "pinta" --dnf "pinta"
  app_alt 1 install_app --name "Pandoc" --alt "Pandoc (Linux)" --winver "3.9" --method native --apt "pandoc" --dnf "pandoc" --zypper "pandoc" --pacman "pandoc"
  app_alt 1 install_app --name "Parsec" --alt "Parsec (Linux)" --method flatpak --flatpak "com.parsecgaming.parsec" --arch "x86_64"
  app_alt 1 install_app --name "pgAdmin 4" --alt "pgAdmin 4 (Linux)" --method manual --url-x86 "https://www.pgadmin.org/download/" --note "pgAdmin 4 from the official apt/dnf repo"
  app_alt 1 install_app --name "pgNow" --alt "pgAdmin 4" --method manual --url-x86 "https://www.pgadmin.org/download/" --note "pgAdmin 4 from the official apt/dnf repo"
  app_alt 1 install_app --name "Photos" --alt "Shotwell" --method flatpak --flatpak "org.gnome.Shotwell" --apt "shotwell" --dnf "shotwell" --pacman "shotwell"
  app_alt 1 install_app --name "PostgreSQL" --alt "PostgreSQL (PGDG repo)" --method native --apt "postgresql" --dnf "postgresql-server" --zypper "postgresql-server" --pacman "postgresql"
  app_alt 1 install_app --name "PowerShell" --alt "PowerShell (Linux)" --winver "7.6.3.0" --method snap --snap "powershell --classic" --note "or use the Microsoft package repo"
  app_alt 1 install_app --name "PowerToys" --alt "Frog (Text Extractor replacement)" --method flatpak --flatpak "com.github.tenderowl.frog"
  app_alt 1 install_app --name "Proton VPN (Hotspot Shield / Psiphon Alternative)" --alt "Proton VPN (Linux)" --method manual --note "No official Linux client; use Proton VPN or OpenVPN instead"
  app_alt 1 install_app --name "Proxifier" --alt "proxychains-ng" --method native --apt "proxychains4" --dnf "proxychains-ng" --zypper "proxychains-ng" --pacman "proxychains-ng"
  app_alt 1 install_app --name "Psiphon Conduit" --alt "Proton VPN" --method manual --url-x86 "https://protonvpn.com/support/official-linux-client/" --note "Proton VPN app via the official apt/dnf repo"
  app_alt 1 install_app --name "PuTTY" --alt "OpenSSH (native)" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh" --note "GUI alt: install 'putty'"
  app_alt 1 install_app --name "Python" --alt "python3 (system)" --winver "3.14.5150.0" --method native --apt "python3 python3-pip" --dnf "python3 python3-pip" --zypper "python3 python3-pip" --pacman "python python-pip"
  app_alt 1 install_app --name "R for Windows" --alt "R (Linux)" --winver "4.5.2" --method native --apt "r-base" --dnf "R" --zypper "R-base" --pacman "r"
  app_alt 1 install_app --name "Recuva" --alt "TestDisk + PhotoRec" --method native --apt "testdisk" --dnf "testdisk" --zypper "testdisk" --pacman "testdisk" --note "includes PhotoRec"
  app_alt 1 install_app --name "Snagit" --alt "Flameshot + Ksnip" --method flatpak --flatpak "org.flameshot.Flameshot" --apt "flameshot" --note "also 'ksnip' for annotation"
  app_alt 1 install_app --name "Snoopy" --alt "OpenSSH + terminal" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  app_alt 1 install_app --name "Sound Recorder" --alt "GNOME Sound Recorder" --method flatpak --flatpak "org.gnome.SoundRecorder" --apt "gnome-sound-recorder"
  app_alt 1 install_app --name "SpeedFan" --alt "CoolerControl / Coolero" --method manual --url-x86 "https://gitlab.com/coolercontrol/coolercontrol/-/releases" --note "CoolerControl from gitlab releases; or lm-sensors + fancontrol"
  app_alt 1 install_app --name "SQL Server Management Studio (SSMS)" --alt "DBeaver" --method flatpak --flatpak "io.dbeaver.DBeaverCommunity"
  app_alt 1 install_app --name "Sticky Notes" --alt "GNOME Sticky Notes (sticky)" --method flatpak --flatpak "com.vixalien.sticky" --apt "gnote"
  app_alt 1 install_app --name "Strawberry Perl" --alt "Perl (native)" --winver "5.42.1" --method native --apt "perl" --dnf "perl" --zypper "perl" --pacman "perl"
  app_alt 1 install_app --name "Telegram Desktop" --alt "Telegram Desktop (Linux)" --method flatpak --flatpak "org.telegram.desktop" --apt "telegram-desktop" --dnf "telegram-desktop" --pacman "telegram-desktop"
  app_alt 1 install_app --name "Terminator" --alt "Terminator (Linux)" --method native --apt "terminator" --dnf "terminator" --zypper "terminator" --pacman "terminator"
  app_alt 1 install_app --name "Typora" --alt "MarkText" --method flatpak --flatpak "com.github.marktext.marktext"
  app_alt 1 install_app --name "Ubuntu (WSL)" --alt "Native Linux" --method manual --note "Not applicable - you are already running Linux"
  app_alt 1 install_app --name "VirtualBox" --alt "VirtualBox (Linux)" --method native --apt "virtualbox" --dnf "VirtualBox" --zypper "virtualbox" --pacman "virtualbox" --note "needs matching kernel modules (dkms)"
  app_alt 1 install_app --name "Visual Studio Build Tools / Community" --alt ".NET SDK + VS Code" --method flatpak --flatpak "com.visualstudio.code" --note "also install the build toolchain (build-essential / @development-tools) and dotnet-sdk"
  app_alt 1 install_app --name "Visual Studio Code" --alt "Visual Studio Code (Linux)" --winver "1.125.0" --method native --flatpak "com.visualstudio.code" --apt "code" --dnf "code"
  app_alt 1 install_app --name "Weather" --alt "GNOME Weather" --method flatpak --flatpak "org.gnome.Weather" --apt "gnome-weather" --dnf "gnome-weather" --pacman "gnome-weather"
  app_alt 1 install_app --name "WhatsApp Desktop" --alt "WhatsApp Web (PWA)" --method webapp --webapp "https://web.whatsapp.com"
  app_alt 1 install_app --name "WinDirStat" --alt "QDirStat" --method native --apt "qdirstat" --dnf "qdirstat" --pacman "qdirstat"
  app_alt 1 install_app --name "Windows Calculator" --alt "GNOME Calculator" --method flatpak --flatpak "org.gnome.Calculator" --apt "gnome-calculator" --dnf "gnome-calculator" --pacman "gnome-calculator"
  app_alt 1 install_app --name "Windows Camera" --alt "Cheese" --method flatpak --flatpak "org.gnome.Cheese" --apt "cheese" --dnf "cheese" --pacman "cheese"
  app_alt 1 install_app --name "Windows Fax and Scan" --alt "Simple Scan (Document Scanner)" --method flatpak --flatpak "org.gnome.SimpleScan" --apt "simple-scan" --dnf "simple-scan" --pacman "simple-scan"
  app_alt 1 install_app --name "Windows Movie Maker" --alt "OpenShot" --method flatpak --flatpak "org.openshot.OpenShot" --apt "openshot-qt" --dnf "openshot" --pacman "openshot"
  app_alt 1 install_app --name "Windows Notepad" --alt "GNOME Text Editor / gedit" --method flatpak --flatpak "org.gnome.TextEditor" --apt "gnome-text-editor" --dnf "gnome-text-editor"
  app_alt 1 install_app --name "Windows Store" --alt "GNOME Software / KDE Discover" --method native --apt "gnome-software" --dnf "gnome-software" --pacman "gnome-software" --note "KDE: plasma-discover"
  app_alt 1 install_app --name "Windows Terminal" --alt "GNOME Console / GNOME Terminal" --method native --apt "gnome-terminal" --dnf "gnome-terminal" --pacman "gnome-terminal" --note "or 'kgx' (GNOME Console)"
  app_alt 1 install_app --name "Wine (Windows Compatibility Layer)" --alt "Wine (winehq-stable)" --method native --apt "wine" --dnf "wine" --zypper "wine" --pacman "wine" --arch "x86_64" --note "enable i386/multilib for 32-bit support"
  app_alt 1 install_app --name "WinRAR" --alt "p7zip / 7-Zip" --method native --apt "p7zip-full" --dnf "p7zip p7zip-plugins" --zypper "p7zip" --pacman "p7zip" --note "also install 'unrar' for RAR archives"
  app_alt 1 install_app --name "wkhtmltox" --alt "wkhtmltopdf (Linux)" --method native --apt "wkhtmltopdf" --dnf "wkhtmltopdf" --pacman "wkhtmltopdf"
  app_alt 1 install_app --name "ZBrush" --alt "Blender (Sculpt Mode)" --method flatpak --flatpak "org.blender.Blender" --apt "blender" --note "Blender Sculpt Mode"
  app_alt 1 install_app --name "Zoom Workplace" --alt "Zoom Workplace (Linux)" --method flatpak --flatpak "us.zoom.Zoom"
  app_alt 1 install_app --name "Zune Music / Windows Media Player" --alt "Rhythmbox" --method flatpak --flatpak "org.gnome.Rhythmbox" --apt "rhythmbox" --dnf "rhythmbox" --pacman "rhythmbox"
  app_alt 1 install_app --name "ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚ÂµTorrent" --alt "qBittorrent" --method flatpak --flatpak "org.qbittorrent.qBittorrent" --apt "qbittorrent" --dnf "qbittorrent" --zypper "qbittorrent" --pacman "qbittorrent"
  app_alt 1 install_app --name "NordVPN" --alt "NordVPN for Linux" --method manual --note "Install via NordVPN's official script: sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)  -- or add their apt/dnf repo. Requires a NordVPN subscription to log in." --paid
  app_alt 1 install_app --name "Miniconda3" --alt "Miniconda (Linux)" --method manual --url-x86 "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" --url-arm "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh" --note "Download the Miniconda installer for your architecture and run: bash Miniconda3-latest-Linux-*.sh"
  install_app --name "Telegram" --alt "telegram-desktop (APT/Flatpak)" --method manual --url-x86 "https://telegram.org/dl/desktop/linux" --note "telegram-desktop (APT/Flatpak) | telegram.org"
  install_app --name "PaperCut" --alt "PaperCut Print Deploy Native Linux client" --method manual --url-x86 "https://<server>:9174" --note "PaperCut Print Deploy Native Linux client | Your PaperCut server (https://<server>:9174)"
  install_app --name "Visual Studio Community 2026" --alt "VS Code (APT repo) + JetBrains Rider (optional)" --method manual --url-x86 "https://code.visualstudio.com/download" --note "VS Code (APT repo) + JetBrains Rider (optional) | code.visualstudio.com; jetbrains.com/rider"
  install_app --name "Visual Studio Build Tools 2026" --alt "dotnet-sdk (APT repo) + MSBuild via Mono + gcc/clang + make/CMake" --method manual --url-x86 "https://packages.microsoft.com/" --note "dotnet-sdk (APT repo) + MSBuild via Mono + gcc/clang + make/CMake | packages.microsoft.com"
  install_app --name "Adobe Digital Editions" --alt "Thorium Reader (Flatpak) + calibre (APT) + Foliate (APT)" --method manual --url-x86 "https://www.edrlab.org/software/thorium-reader/" --note "Thorium Reader (Flatpak) + calibre (APT) + Foliate (APT) | edrlab.org; calibre-ebook.com; johnfactotum.github.io/foliate"
  install_app --name "Pinta" --alt "Pinta (Flatpak)" --method manual --url-x86 "https://flathub.org/apps/com.github.PintaProject.Pinta" --note "Pinta (Flatpak) | flathub.org: com.github.PintaProject.Pinta"
  install_app --name "LanguageTool" --alt "LanguageTool .zip from languagetool.org" --method manual --url-x86 "https://languagetool.org/download/" --note "LanguageTool .zip from languagetool.org | languagetool.org"
  install_app --name "Proton VPN" --alt "proton-vpn-gnome-desktop (APT repo)" --method manual --url-x86 "https://protonvpn.com/support/official-linux-vpn/" --note "proton-vpn-gnome-desktop (APT repo) | repo.protonvpn.com"
  install_app --name "Wine" --alt "winehq-stable (APT repo) + wine32 + i386 architecture" --method manual --url-x86 "https://wiki.winehq.org/Download" --note "winehq-stable (APT repo) + wine32 + i386 architecture | dl.winehq.org"
  install_app --name "Multipass" --alt "multipass (APT SnapStore replacement)" --method manual --url-x86 "https://canonical.com/multipass/install" --note "multipass (APT SnapStore replacement) | canonical.com/multipass"
  install_app --name "Microsoft OneNote" --alt "Obsidian (Flatpak/.deb) + Joplin (Flatpak) + Xournal++ (APT) + OneNote WebApp .desktop shortcut" --method manual --url-x86 "https://obsidian.md/download" --note "Obsidian (Flatpak/.deb) + Joplin (Flatpak) + Xournal++ (APT) + OneNote WebApp .desktop shortcut | obsidian.md; joplinapp.org; xournalpp.github.io; onenote.com"

  print_summary
}

main "$@"
