#!/usr/bin/env bash
# =============================================================================
#  install_must_have_software.sh
#  GENERATED by submodules/D_compile_and_generate_shell_script.ps1 -- do not edit.
#
#  Universal installer: detects the Linux distribution family (apt/dnf/zypper/
#  pacman) and CPU architecture at runtime, then installs each app Flatpak-first
#  with a native-package fallback.  Runs unchanged on every supported distro.
# =============================================================================
# =============================================================================
#  _common.sh  --  universal runtime engine for the generated installer scripts
# -----------------------------------------------------------------------------
#  This file is INLINED into every generated script in "Execute on Linux!/" by
#  submodules/D_compile_and_generate_shell_script.ps1.  It is distro- and
#  architecture-agnostic: it detects the running distro FAMILY (apt/dnf/zypper/
#  pacman) and CPU ARCH at runtime, then dispatches installs accordingly.
#
#  Design: Flatpak-first.  GUI apps come from Flathub (identical app id on every
#  distro).  The native package manager is used only for the irreducible base
#  (installing Flatpak itself, CLI/dev tools, drivers, system bits).
# =============================================================================

# Be strict but survivable: we handle per-app failures ourselves, so do not let
# a single failing install abort the whole run.
set -o pipefail

# ----------------------------- pretty output ---------------------------------
# All human-facing chatter goes to fd 3 (stdout) so command output can be hidden.
exec 3>&1
log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*" >&3; }
info() { printf '       %s\n' "$*" >&3; }
ok()   { printf '       \033[32m%s\033[0m\n' "$*" >&3; }
warn() { printf '       \033[1;33m%s\033[0m\n' "$*" >&3; }
err()  { printf '\033[1;31m%s\033[0m\n' "$*" >&3; }
# Purple/magenta line -- used for the interactive wine (Windows emulator) first-launch
# appearance-tuning prompts so they stand out from ordinary install chatter.
purple() { printf '\033[1;35m%s\033[0m\n' "$*" >&3; }

# Project banner -- printed ONCE at the very start of a run, mirroring the PowerShell
# Show-MegaTitle that run_project.ps1 shows on the Windows side. Green.
mega_title() {
  local g=$'\033[1;32m' r=$'\033[0m'
  printf '%s\n' '' >&3
  printf '%s  ###########################################################%s\n' "$g" "$r" >&3
  printf '%s  ##                                                       ##%s\n' "$g" "$r" >&3
  printf '%s  ##            M I G R A T E   T O   L I N U X             ##%s\n' "$g" "$r" >&3
  printf '%s  ##        Windows  ->  Linux   Migration  Toolkit         ##%s\n' "$g" "$r" >&3
  printf '%s  ##                                                       ##%s\n' "$g" "$r" >&3
  printf '%s  ###########################################################%s\n' "$g" "$r" >&3
  printf '%s\n' '' >&3
}

# Sensitive data exported on Windows (WiFi passwords, SSH private keys, Contacts,
# wallpaper) is OpenSSL-encrypted with ONE shared password. Ask for it ONCE, up front,
# and cache it in MIGRATE_XFER_PWD so each consumer (apply_wifi, unpack_stage) reuses the
# same answer instead of prompting again mid-run. Idempotent; the flag and the answer are
# exported so child stages launched by execute_all inherit them and never re-ask.
XFER_PWD_ASKED="${XFER_PWD_ASKED:-0}"
ask_xfer_password() {
  [ "$XFER_PWD_ASKED" = "1" ] && return 0
  XFER_PWD_ASKED=1; export XFER_PWD_ASKED
  if [ -r /dev/tty ]; then
    printf '  Enter the password used on Windows to encrypt your sensitive data (WiFi passwords, SSH keys, Contacts, wallpaper). Leave empty to skip restoring it: ' > /dev/tty
    read -r MIGRATE_XFER_PWD < /dev/tty || MIGRATE_XFER_PWD=""
  fi
  export MIGRATE_XFER_PWD
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

# Filesystem-safe slug from an app name. execute_all.sh stages user-supplied
# files for "manual" apps under $MIGRATE_MANUAL_DIR/<slug>/ using the SAME slug.
slugify() { printf '%s' "$1" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-_'; }

# The non-root user we should install Flatpak apps / write desktop files for,
# even though the script itself runs under sudo. logname is the original login
# name of the session and is more reliable than $SUDO_USER (which is empty when
# the script is not entered through sudo, and can be stale across su/sudo chains).
TARGET_USER="$(logname 2>/dev/null || true)"
{ [ -z "$TARGET_USER" ] || [ "$TARGET_USER" = "root" ]; } && TARGET_USER="${SUDO_USER:-$(id -un)}"
TARGET_HOME="$(getent passwd "$TARGET_USER" 2>/dev/null | cut -d: -f6)"
[ -z "$TARGET_HOME" ] && TARGET_HOME="$HOME"

# ----------------------------- bookkeeping -----------------------------------
# The results log is created on the logname user's Desktop (and owned by them) so it is
# easy to find after the run; it falls back to a temp file if that is not writable.
RESULTS="${RESULTS:-$TARGET_HOME/Desktop/migrate_to_linux_results.tsv}"
# execute_all sets MIGRATE_KEEP_RESULTS so the per-stage child scripts APPEND to one
# shared log instead of truncating it, which lets execute_all print a combined
# summary of every operation at the very end. Run standalone, a script truncates.
if [ -z "${MIGRATE_KEEP_RESULTS:-}" ]; then
  mkdir -p "$(dirname "$RESULTS")" 2>/dev/null || true
  if : > "$RESULTS" 2>/dev/null; then
    chown "$TARGET_USER":"$TARGET_USER" "$RESULTS" 2>/dev/null || true
  else
    RESULTS="$(mktemp)"
  fi
fi
# Containers launched by the docker install method are recorded here (one TSV row per
# container: winapp \t image \t container \t how-to) so the end-of-run summary can print
# a "Launched containers" section. Shares the same cross-stage model as RESULTS.
DOCKER_LAUNCHED="${DOCKER_LAUNCHED:-/tmp/migrate_to_linux_launched.tsv}"
if [ -z "${MIGRATE_KEEP_RESULTS:-}" ]; then
  : > "$DOCKER_LAUNCHED" 2>/dev/null || DOCKER_LAUNCHED="$(mktemp)"
fi
# Install ledger: one TSV row per successful install (method <tab> identifier). Used to
# generate an uninstall script at the end of the run. Shares the cross-stage model above.
LEDGER="${LEDGER:-/tmp/migrate_to_linux_ledger.tsv}"
if [ -z "${MIGRATE_KEEP_RESULTS:-}" ]; then
  : > "$LEDGER" 2>/dev/null || LEDGER="$(mktemp)"
fi
declare -a OK_LIST=() SKIP_LIST=() FAIL_LIST=() FAIL_REASON=() MANUAL_LIST=() PLAN_LIST=() UNVERIFIED_LIST=()

# Report-only mode: when MIGRATE_DRY_RUN=yes the engine prints the plan and makes no changes.
is_dry_run() { [ "${MIGRATE_DRY_RUN:-no}" = "yes" ]; }

# LAST_ERR holds the 1-line reason from the most recent captured command failure.
LAST_ERR=""

# Run a command, show its output, and on failure capture the last output line into
# LAST_ERR (a 1-line error reason). stdin stays attached, so interactive installers
# still work. Returns the command's real exit code.
capture() {
  if is_dry_run; then printf '       \033[2m[dry-run] would run: %s\033[0m\n' "$*" >&3; LAST_ERR=""; return 0; fi
  local rc tmp; tmp="$(mktemp 2>/dev/null || echo /tmp/mtl_cap.$$)"
  "$@" 2>&1 | tee "$tmp" >&3
  rc=${PIPESTATUS[0]}
  LAST_ERR=""
  if [ "$rc" -ne 0 ]; then
    LAST_ERR="$(grep -v '^[[:space:]]*$' "$tmp" 2>/dev/null | tail -n 1)"
    [ -z "$LAST_ERR" ] && LAST_ERR="exit code $rc"
  fi
  rm -f "$tmp" 2>/dev/null || true
  return "$rc"
}

# MODULE tags which big module (Drivers / Config settings / Applications) each result
# belongs to, so execute_all can print a per-module classified summary at the end.
MODULE="${MODULE:-General}"
record_line() { printf '%s\t%s\t%-6s\t%s\t%s\t%s\t%s\n' "$(date '+%F %T')" "${MODULE:-General}" "$1" "$2" "${3:-}" "${4:-}" "${5:-}" >> "$RESULTS"; }
# One-line "how to open this app" hint, derived from how it was installed. Used by the
# end-of-run summary to tell the user how to launch each app that now exists.
launch_hint_from_detail() {  # launch_hint_from_detail NAME DETAIL
  local nm="$1" d="$2" id
  case "$d" in
    flatpak\ *) id="${d#flatpak }"; id="${id%% *}"; printf 'Search "%s" in the start menu, or run "flatpak run %s" in a terminal' "$nm" "$id" ;;
    native\ *)  id="${d#native }";  id="${id%% *}"; printf 'Search "%s" in the start menu, or run "%s" in a terminal' "$nm" "$id" ;;
    snap\ *)    id="${d#snap }";    id="${id%% *}"; printf 'Search "%s" in the start menu, or run "%s" in a terminal' "$nm" "$id" ;;
    web-app*)            printf 'Search "%s" in the start menu (web-app shortcut)' "$nm" ;;
    *wine*)              printf 'Search "%s" in the start menu (wine - Windows emulator launcher)' "$nm" ;;
    *docker*|*ontainer*) printf '"%s" runs as a Docker container - open its web UI or manage it with docker' "$nm" ;;
    *)                   printf 'Search "%s" in the start menu, or run "%s" in a terminal' "$nm" "$nm" ;;
  esac
}
# Return STRING with any "already <state>" status phrase (already installed / configured /
# present / set / enabled / exists / running / ...) shown in green; the optional 2nd arg is
# the colour to RESUME with after the phrase, so the rest of the line keeps its original
# colour (default: reset). On-screen use only -- the raw phrase is what is written to the log.
hl_already() {  # hl_already STRING [RESUME_COLOUR]
  local g=$'\033[32m' rst=$'\033[0m' back
  back="${2:-$rst}"
  printf '%s' "$1" | sed -E "s/already [A-Za-z]+/${g}&${back}/g"
}

# mark_ok WIN_NAME [DETAIL] [ALT_NAME] [LAUNCH_OVERRIDE]. The summary shows the app as
# "<alt> (<win>): <launch hint>"; the hint is the manifest launch override if given,
# else derived from how it was installed using the ALTERNATIVE name (what to search for).
mark_ok()     { OK_LIST+=("$1"); local _alt="${3:-}" _h=""; if [ "${MODULE:-}" = "Applications" ]; then if [ -n "${4:-}" ]; then _h="$4"; else _h="$(launch_hint_from_detail "${_alt:-$1}" "${2:-}")"; fi; fi; record_line OK "$1" "${2:-}" "$_h" "$_alt"; ok "installed: ${_alt:-$1}${2:+  ->  $2}"; }
mark_skip()   { SKIP_LIST+=("$1");   record_line SKIP   "$1" "${2:-}" "${3:-}" "${4:-}"; info "skipped: $1 ($(hl_already "${2:-already present}"))"; }
mark_fail()   { FAIL_LIST+=("$1"); FAIL_REASON+=("${2:-unknown error}"); record_line FAIL "$1" "${2:-}"; err "failed: $1 ${2:+- $2}"; }
mark_manual() { MANUAL_LIST+=("$1"); record_line MANUAL "$1" "${2:-}"; warn "manual step required: $1 ${2:+- $2}"; }
mark_plan()      { PLAN_LIST+=("$1");       record_line PLAN  "$1" "${2:-}"; info "[dry-run] would install: $1 ${2:+- $2}"; }
mark_unverified(){ UNVERIFIED_LIST+=("$1"); record_line UNVER "$1" "${2:-}"; warn "installed but UNVERIFIED: $1 ${2:+- $2}"; }

# Record a successful install in the ledger (method <tab> id) so an uninstall script can
# be generated later. No-op in dry-run.
ledger_add() { is_dry_run && return 0; printf '%s\t%s\n' "$1" "${2:-}" >> "$LEDGER" 2>/dev/null || true; }

# Verify an install is actually present after the package manager reported success.
verify_present() {  # verify_present METHOD ID  -> 0 if present
  case "$1" in
    flatpak) have_cmd flatpak && flatpak_installed "$2" ;;
    native)  pm_installed "${2%% *}" ;;
    snap)    have_cmd snap && snap list "${2%% *}" >/dev/null 2>&1 ;;
    *)       return 0 ;;   # file/wine/webapp/docker: nothing to verify -> assume ok
  esac
}

# Record a successful install: verify it is really present, ledger it for uninstall, and
# mark OK -- or mark it UNVERIFIED if the post-install check cannot confirm it.
finish_install() {  # finish_install NAME ALT METHOD ID DETAIL [LAUNCH]
  local name="$1" alt="$2" method="$3" id="$4" detail="$5" launch="${6:-}"
  if verify_present "$method" "$id"; then
    ledger_add "$method" "$id"; mark_ok "$name" "$detail" "$alt" "$launch"
  else
    mark_unverified "${alt:-$name}" "$detail (could not confirm it is installed)"
  fi
}

# Write an uninstall script for everything this run installed. Package-manager installs
# are reversible; file/wine installs get a manual note. No-op in dry-run / empty ledger.
write_uninstall_script() {
  is_dry_run && return 0
  [ -s "$LEDGER" ] || return 0
  local out="${MIGRATE_UNINSTALL_SCRIPT:-$TARGET_HOME/uninstall_migrated_apps.sh}" rm_native="" m id
  case "$PM" in
    apt)    rm_native="apt-get remove -y" ;;
    dnf)    rm_native="dnf remove -y" ;;
    zypper) rm_native="zypper --non-interactive remove" ;;
    pacman) rm_native="pacman -Rns --noconfirm" ;;
  esac
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Auto-generated by the Migration Toolkit -- removes what the install run added.\n'
    printf '# Review it, then run as root:  sudo bash %s\n\n' "$out"
    printf 'set -o pipefail\n\n'
    sort -u "$LEDGER" 2>/dev/null | while IFS="$(printf '\t')" read -r m id; do
      [ -n "$id" ] || continue
      case "$m" in
        flatpak) printf 'flatpak uninstall -y %s\n' "$id" ;;
        native)  printf '%s %s\n' "$rm_native" "$id" ;;
        snap)    printf 'snap remove %s\n' "$id" ;;
        wine)    printf '# wine (Windows emulator) app -- to remove, delete its prefix:  rm -rf %s\n' "$id" ;;
        file)    printf '# installed from a downloaded file (remove manually): %s\n' "$id" ;;
        *)       printf '# %s: %s\n' "$m" "$id" ;;
      esac
    done
  } > "$out" 2>/dev/null && { chmod +x "$out" 2>/dev/null || true; chown "$TARGET_USER":"$TARGET_USER" "$out" 2>/dev/null || true; info "Uninstall script written: $out"; }
}

print_summary() {
  # When orchestrated by execute_all, it prints ONE combined, classified summary at
  # the very end; suppress the per-stage summary here to avoid mid-run clutter.
  [ -n "${MIGRATE_KEEP_RESULTS:-}" ] && return 0
  log "Summary"
  info "OK:        ${#OK_LIST[@]}"
  info "Skip:      ${#SKIP_LIST[@]}"
  info "Manual:    ${#MANUAL_LIST[@]}"
  info "Unverified:${#UNVERIFIED_LIST[@]}"
  info "Failed:    ${#FAIL_LIST[@]}"
  [ "${#PLAN_LIST[@]}" -gt 0 ] && info "Planned (dry-run): ${#PLAN_LIST[@]}"
  if [ "${#UNVERIFIED_LIST[@]}" -gt 0 ]; then
    warn "Installed but UNVERIFIED (could not confirm present):"; for i in "${UNVERIFIED_LIST[@]}"; do info "  - $i"; done
  fi
  if [ "${#FAIL_LIST[@]}" -gt 0 ]; then
    warn "Failures (1-line reason each):"
    for i in "${!FAIL_LIST[@]}"; do err "  - ${FAIL_LIST[$i]}: ${FAIL_REASON[$i]}"; done
  fi
  if [ "${#MANUAL_LIST[@]}" -gt 0 ]; then
    warn "Need a manual step:"; for i in "${MANUAL_LIST[@]}"; do info "  - $i"; done
  fi
  # Apps that now exist on the machine (installed this run or already present), each
  # with a one-line how-to-open note (field 6 of the results log).
  if awk -F'\t' '$6!=""{f=1} END{exit !f}' "$RESULTS" 2>/dev/null; then
    log "Applications on this machine - how to open each"
    awk -F'\t' '$6!=""{n=($7!="" && $7!=$4 ? $7" ("$4")" : $4); printf "  %s: %s\n",n,$6}' "$RESULTS" | sort -u | while IFS= read -r l; do info "$l"; done
  fi
  print_launched_containers
  write_uninstall_script
  info "Full log: $RESULTS"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    err "This script must be run as root.  Try:  sudo $0"
    exit 1
  fi
}

# ----------------------------- optional additions ----------------------------
# Some migrated settings (e.g. firewall rules, display resolution, NTP) need a
# package that may not be installed. ask_install_addition explains WHAT the
# package is for and offers yes / skip / skip all, mirroring the skip-all model
# used by manual_fallback. Returns 0 if the package(s) are now present (user said
# yes and the install succeeded), 1 otherwise (skipped, no tty, or install failed).
#   ask_install_addition "Display resolution" "x11-xserver-utils" "set the screen resolution"
ADDITIONS_SKIP_ALL=0
ask_install_addition() {  # ask_install_addition PURPOSE_LABEL "PKG [PKG...]" WHAT_FOR
  local label="$1" pkgs="$2" whatfor="$3" ans
  [ "${ADDITIONS_SKIP_ALL:-0}" = "1" ] && { mark_skip "$label" "addition skipped (skip all)"; return 1; }
  if is_dry_run; then info "[dry-run] would offer to install: $pkgs (for $label)"; return 1; fi
  printf '\n\033[1;34m==> %s needs an extra package\033[0m\n' "$label" >&3
  info "The package(s) \"$pkgs\" are required to ${whatfor}."
  info "They come from your distribution's own repositories ($PM)."
  if [ ! -r /dev/tty ]; then mark_skip "$label" "addition needs \"$pkgs\" (no tty to ask)"; return 1; fi
  while :; do
    printf '  Install %s now? (y=yes / s=skip / a=skip all): ' "$pkgs" > /dev/tty
    read -r ans < /dev/tty || ans="s"
    case "$ans" in
      [Yy]|[Yy][Ee][Ss])
        pm_refresh
        # shellcheck disable=SC2086
        if capture pm_install $pkgs; then ok "installed: $pkgs"; return 0
        else mark_fail "$label" "${LAST_ERR:-could not install $pkgs}"; return 1; fi ;;
      [Aa]|[Aa][Ll][Ll]|'skip all'|'Skip all'|'Skip All'|'SKIP ALL')
        ADDITIONS_SKIP_ALL=1; mark_skip "$label" "addition skipped (skip all)"; return 1 ;;
      [Ss]|[Ss][Kk][Ii][Pp]) mark_skip "$label" "addition skipped (needs $pkgs)"; return 1 ;;
      *) printf '\033[1;31m  Please answer y (yes), s (skip), or a (skip all).\033[0m\n' > /dev/tty ;;
    esac
  done
}

# =============================================================================
#  DISTRO + ARCHITECTURE DETECTION
# =============================================================================
FAMILY=""      # debian | rhel | suse | arch
PM=""          # apt | dnf | zypper | pacman
DISTRO_ID=""
DISTRO_NAME=""

detect_distro() {
  if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    DISTRO_ID="${ID:-}"
    DISTRO_NAME="${PRETTY_NAME:-${NAME:-$ID}}"
  fi
  local hay=" ${DISTRO_ID} ${ID_LIKE:-} "
  case "$hay" in
    *" debian "*|*" ubuntu "*|*" linuxmint "*|*" pop "*|*" zorin "*|*" elementary "*) FAMILY="debian"; PM="apt" ;;
    *" rhel "*|*" fedora "*|*" centos "*|*" rocky "*|*" almalinux "*|*" ol "*) FAMILY="rhel"; PM="dnf" ;;
    *" suse "*|*" opensuse "*|*" sles "*|*" sled "*) FAMILY="suse"; PM="zypper" ;;
    *" arch "*|*" archlinux "*|*" manjaro "*|*" endeavouros "*) FAMILY="arch"; PM="pacman" ;;
    *)
      # Fall back to whichever package manager actually exists.
      if   have_cmd apt-get; then FAMILY="debian"; PM="apt"
      elif have_cmd dnf;     then FAMILY="rhel";   PM="dnf"
      elif have_cmd zypper;  then FAMILY="suse";   PM="zypper"
      elif have_cmd pacman;  then FAMILY="arch";   PM="pacman"
      else err "Unsupported distribution: could not find apt/dnf/zypper/pacman."; exit 1
      fi ;;
  esac
}

ARCH=""        # x86_64 | aarch64 | armhf | other
detect_arch() {
  local m; m="$(uname -m)"
  case "$m" in
    x86_64|amd64)        ARCH="x86_64" ;;
    aarch64|arm64)       ARCH="aarch64" ;;
    armv7l|armhf|armv6l) ARCH="armhf" ;;
    *)                   ARCH="$m" ;;
  esac
}

# arch_supported "x86_64 aarch64"  ->  true if $ARCH is listed (empty list = all)
arch_supported() {
  local list="$1"
  [ -z "$list" ] && return 0
  case " $list " in *" $ARCH "*) return 0 ;; *) return 1 ;; esac
}

# =============================================================================
#  PACKAGE-MANAGER ABSTRACTION
# =============================================================================
# Quarantine malformed apt source files so a single bad entry can't wedge the
# whole package manager. apt aborts every update/install if any file in
# sources.list.d has a bare "deb"/"deb-src" line with no URI -- which is exactly
# what a third-party installer (e.g. NordVPN) leaves behind when interrupted
# mid-write (Ctrl+C). We only touch clearly-broken files, and we rename rather
# than delete (.broken) so the change is reversible.
apt_repair_sources() {
  [ -d /etc/apt/sources.list.d ] || return 0
  for f in /etc/apt/sources.list.d/*.list; do
    [ -f "$f" ] || continue   # no matches -> literal glob, skip
    # A line that is just "deb"/"deb-src" (optionally with [opts]) and nothing
    # after it -- no URI, no suite -- is malformed and fatal to apt.
    if grep -qE '^[[:space:]]*deb(-src)?([[:space:]]+\[[^]]*\])?[[:space:]]*$' "$f"; then
      warn "Malformed apt source quarantined: $f -> $f.broken"
      is_dry_run || mv -f "$f" "$f.broken"
    fi
  done
}

_PM_REFRESHED=0
pm_refresh() {
  [ "$_PM_REFRESHED" = "1" ] && return 0
  case "$PM" in
    apt)    apt_repair_sources; DEBIAN_FRONTEND=noninteractive apt-get update -y ;;
    dnf)    dnf -y makecache ;;
    zypper) zypper --non-interactive refresh ;;
    pacman) pacman -Sy --noconfirm ;;
  esac
  _PM_REFRESHED=1
}

pm_install() {
  [ "$#" -eq 0 ] && return 0
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "$@" ;;
    dnf)    dnf install -y "$@" ;;
    zypper) zypper --non-interactive install -y --no-recommends "$@" ;;
    pacman) pacman -S --noconfirm --needed "$@" ;;
  esac
}

pm_installed() {
  case "$PM" in
    apt)    dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q "install ok installed" ;;
    dnf)    rpm -q "$1" >/dev/null 2>&1 ;;
    zypper) rpm -q "$1" >/dev/null 2>&1 ;;
    pacman) pacman -Q "$1" >/dev/null 2>&1 ;;
  esac
}

# =============================================================================
#  FLATPAK (universal app layer)
# =============================================================================
ensure_flatpak() {
  if ! have_cmd flatpak; then
    log "Installing Flatpak (required for the universal app layer)"
    pm_refresh
    pm_install flatpak || { mark_fail "flatpak" "could not install flatpak via $PM"; return 1; }
  fi
  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo >/dev/null 2>&1 || true
  return 0
}

flatpak_installed() { flatpak info "$1" >/dev/null 2>&1; }

install_flatpak() {  # install_flatpak APPID
  local id="$1"
  if flatpak_installed "$id"; then
    # Already present: update it if the user asked to update existing apps.
    [ "${MIGRATE_UPDATE_EXISTING:-no}" = "yes" ] && flatpak update -y --noninteractive "$id"
    return 0
  fi
  flatpak install -y --noninteractive flathub "$id"
}

# =============================================================================
#  SNAP (optional fallback)
# =============================================================================
ensure_snap() {
  have_cmd snap && return 0
  case "$PM" in
    apt)    pm_install snapd ;;
    dnf)    pm_install snapd && systemctl enable --now snapd.socket 2>/dev/null && ln -sf /var/lib/snapd/snap /snap 2>/dev/null ;;
    zypper) warn "snap on openSUSE needs the snappy repo; skipping snap fallback"; return 1 ;;
    pacman) warn "snap on Arch is via AUR; skipping snap fallback"; return 1 ;;
  esac
  have_cmd snap
}

# =============================================================================
#  DESKTOP / WEB-APP SHORTCUTS
# =============================================================================
detect_browser() {
  local b
  for b in google-chrome google-chrome-stable chromium chromium-browser microsoft-edge brave-browser firefox; do
    have_cmd "$b" && { printf '%s' "$b"; return 0; }
  done
  # Flatpak browsers
  if flatpak_installed com.google.Chrome; then printf 'flatpak run com.google.Chrome'; return 0; fi
  if flatpak_installed org.chromium.Chromium; then printf 'flatpak run org.chromium.Chromium'; return 0; fi
  if flatpak_installed com.microsoft.Edge; then printf 'flatpak run com.microsoft.Edge'; return 0; fi
  return 1
}

# Open a URL in the desktop user's default browser (best-effort, non-blocking). Used by
# every manual / download-by-user prompt so the download page opens automatically.
open_url() {  # open_url URL
  local u="$1"; [ -n "$u" ] || return 0
  is_dry_run && return 0
  local uid; uid="$(id -u "$TARGET_USER" 2>/dev/null)"
  if have_cmd xdg-open; then
    sudo -u "$TARGET_USER" DISPLAY="${DISPLAY:-:0}" \
      DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${uid}/bus" \
      xdg-open "$u" >/dev/null 2>&1 &
  elif have_cmd gio; then
    sudo -u "$TARGET_USER" DISPLAY="${DISPLAY:-:0}" gio open "$u" >/dev/null 2>&1 &
  fi
}

# Run a command as the logged-in desktop user with their D-Bus session / runtime dir wired
# up (per-user things like gsettings/dconf need this). Mirrors apply_settings.sh's helper
# so install_app's post-install commands can touch the user's desktop. No-op of escalation
# when already running as that user.
run_as_user() {  # run_as_user CMD [ARGS...]
  local uid; uid="$(id -u "$TARGET_USER" 2>/dev/null)"
  if [ "$(id -u)" -eq 0 ] && [ "$TARGET_USER" != "root" ]; then
    sudo -u "$TARGET_USER" \
      DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${uid}/bus" \
      XDG_RUNTIME_DIR="/run/user/${uid}" DISPLAY="${DISPLAY:-:0}" "$@"
  else
    DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/${uid}/bus}" \
      XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/${uid}}" DISPLAY="${DISPLAY:-:0}" "$@"
  fi
}

# Run an app's custom post-install commands (from the manifest's install.postInstall),
# best-effort, as the logged-in user, right after the app was successfully installed.
# Each command is a self-contained shell snippet; a failing one is reported but never
# fails the install. No-op in dry-run / with no commands.
run_post_install() {  # run_post_install NAME CMD [CMD...]
  local name="$1"; shift
  is_dry_run && return 0
  [ "$#" -gt 0 ] || return 0
  local cmd rc=0
  info "applying custom post-install setup for $name ..."
  for cmd in "$@"; do
    [ -n "$cmd" ] || continue
    run_as_user bash -lc "$cmd" >/dev/null 2>&1 || { rc=1; warn "a post-install command for $name did not complete (continuing): $cmd"; }
  done
  [ "$rc" -eq 0 ] && ok "custom post-install setup applied for $name"
  return 0
}

webapp_desktop() {  # webapp_desktop "Name" "URL" [ALT] [LAUNCH]
  local name="$1" url="$2" alt="${3:-}" launch="${4:-}" browser appdir desktop slug
  browser="$(detect_browser)" || { mark_manual "${alt:-$name}" "no browser found for web-app shortcut ($url)"; return 1; }
  slug="$(printf '%s' "$name" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-')"
  appdir="$TARGET_HOME/.local/share/applications"
  mkdir -p "$appdir"
  desktop="$appdir/webapp-$slug.desktop"
  {
    printf '[Desktop Entry]\n'
    printf 'Version=1.0\nType=Application\n'
    printf 'Name=%s\n' "$name"
    printf 'Exec=%s --app=%s\n' "$browser" "$url"
    printf 'Terminal=false\nCategories=Network;WebBrowser;\n'
  } > "$desktop"
  chown "$TARGET_USER":"$TARGET_USER" "$desktop" 2>/dev/null || true
  chmod +x "$desktop" 2>/dev/null || true
  mark_ok "$name" "web-app shortcut -> $url" "$alt" "$launch"
}

# =============================================================================
#  DIRECT DOWNLOADS (.deb / .rpm / AppImage)
# =============================================================================
DOWNLOAD_DIR="${DOWNLOAD_DIR:-/tmp/migrate_to_linux_downloads}"
mkdir -p "$DOWNLOAD_DIR" 2>/dev/null || true

download_file() {  # download_file URL OUTPATH
  local url="$1" out="$2"
  if have_cmd curl; then curl -fL --retry 3 -o "$out" "$url"
  elif have_cmd wget; then wget -O "$out" "$url"
  else err "neither curl nor wget available"; return 1; fi
}

install_local_package() {  # install_local_package FILE
  local f="$1"
  case "$PM" in
    apt)    DEBIAN_FRONTEND=noninteractive apt-get install -y "$f" || { dpkg -i "$f"; apt-get -f install -y; } ;;
    dnf)    dnf install -y "$f" ;;
    zypper) zypper --non-interactive install -y --allow-unsigned-rpm "$f" ;;
    pacman) pacman -U --noconfirm "$f" ;;
  esac
}

# Best-effort install of a package matching a specific (Windows) version. Tries the
# major-version package name and an exact version pin. Returns 0 on success, 1 if no
# matching version could be installed (caller then falls back to latest). pacman is
# rolling-release, so version pinning is not supported there.
install_native_version() {  # install_native_version PKG WINVER
  local pkg="$1" ver="$2" major
  major="$(printf '%s' "$ver" | grep -oE '[0-9]+' | head -n1)"
  [ -z "$major" ] && return 1
  case "$PM" in
    apt)    capture pm_install "${pkg}-${major}" || capture pm_install "${pkg}=${ver}" ;;
    dnf)    capture pm_install "${pkg}${major}" || capture pm_install "${pkg}-${major}" || capture pm_install "${pkg}-${ver}" ;;
    zypper) capture pm_install "${pkg}${major}" || capture pm_install "${pkg}-${ver}" ;;
    pacman) return 1 ;;
  esac
}

# =============================================================================
#  install_app  --  the multi-strategy, Flatpak-first dispatcher
# -----------------------------------------------------------------------------
#  Usage (emitted by the generator):
#    install_app --name "VLC" --method flatpak --flatpak org.videolan.VLC \
#                --apt vlc --dnf vlc --zypper vlc --pacman vlc \
#                --arch "x86_64 aarch64"
#  Methods: flatpak | native | snap | webapp | docker | wine-bottles |
#           deb-url | github-deb | manual
#  Custom post-install commands (manifest install.postInstall) are passed as repeated
#  --post 'CMD' flags; the public install_app wrapper below runs them after a success.
# =============================================================================
_install_app_core() {
  local name="" alt="" method="" flatpak="" snap_pkg="" arch_list="" winver="" is_security=0 is_paid=0
  local apt="" dnf="" zypper="" pacman="" launch=""
  local url_x86="" url_arm="" url_deb="" url_rpm="" webapp_url="" docker_image="" github_repo="" note=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --name)    name="$2"; shift 2 ;;
      --alt)     alt="$2"; shift 2 ;;
      --launch)  launch="$2"; shift 2 ;;
      --method)  method="$2"; shift 2 ;;
      --flatpak) flatpak="$2"; shift 2 ;;
      --snap)    snap_pkg="$2"; shift 2 ;;
      --apt)     apt="$2"; shift 2 ;;
      --dnf)     dnf="$2"; shift 2 ;;
      --zypper)  zypper="$2"; shift 2 ;;
      --pacman)  pacman="$2"; shift 2 ;;
      --arch)    arch_list="$2"; shift 2 ;;
      --winver)  winver="$2"; shift 2 ;;
      --url-x86) url_x86="$2"; shift 2 ;;
      --url-arm) url_arm="$2"; shift 2 ;;
      --url-deb) url_deb="$2"; shift 2 ;;
      --url-rpm) url_rpm="$2"; shift 2 ;;
      --webapp)  webapp_url="$2"; shift 2 ;;
      --docker)  docker_image="$2"; shift 2 ;;
      --github)  github_repo="$2"; shift 2 ;;
      --note)     note="$2"; shift 2 ;;
      --security) is_security=1; shift ;;
      --paid)     is_paid=1; shift ;;
      *) shift ;;
    esac
  done
  [ -z "$name" ] && return 0

  # Security-suite equivalents (antivirus/firewall, etc.) are only installed when the
  # user opted in; many skip them because Linux is hardened by default.
  if [ "$is_security" -eq 1 ] && [ "${MIGRATE_INSTALL_SECURITY:-no}" != "yes" ]; then
    mark_skip "${alt:-$name}" "security suite - not installed (opted out)"
    return 0
  fi

  # Dry-run (report only): print the plan for this app and make no changes.
  if is_dry_run; then
    if ! arch_supported "$arch_list"; then mark_skip "${alt:-$name}" "not available for $ARCH"; return 0; fi
    local dpkg="" plan=""
    case "$PM" in apt) dpkg="$apt" ;; dnf) dpkg="$dnf" ;; zypper) dpkg="$zypper" ;; pacman) dpkg="$pacman" ;; esac
    case "$method" in
      webapp)       plan="web-app shortcut -> $webapp_url" ;;
      docker)       plan="docker container: $docker_image" ;;
      wine-bottles) plan="Bottles (flatpak) for a Windows app" ;;
      manual)       plan="manual download-by-user" ;;
      *)
        if   [ -n "$flatpak" ];                          then plan="flatpak $flatpak"
        elif [ -n "$dpkg" ];                             then plan="native ($PM) $dpkg"
        elif [ -n "$snap_pkg" ];                         then plan="snap $snap_pkg"
        elif [ -n "$url_x86$url_arm$url_deb$url_rpm" ];   then plan="direct download"
        else plan="no automatic route -> manual"; fi ;;
    esac
    [ "$is_paid" -eq 1 ] && plan="$plan (paid)"
    mark_plan "${alt:-$name}" "$plan"
    return 0
  fi

  # Free-only mode: this app's only alternative is paid. Ask whether to proceed.
  if [ "${MIGRATE_FREE_ONLY:-no}" = "yes" ] && [ "$is_paid" -eq 1 ]; then
    local _fans=""
    if [ -r /dev/tty ]; then
      printf '\n\n\033[1;33m==> %s%s has no free alternative.\033[0m\n' "$name" "${alt:+ ---> $alt}" >&3
      printf '  No free alternative exists for this application. Do you want to continue with the installation of the paid one? Answering with No means skipping this application (y/n): ' > /dev/tty
      read -r _fans < /dev/tty || _fans="n"
      case "$_fans" in [Yy]*) ;; *) mark_skip "${alt:-$name}" "paid - skipped (free-only mode)"; return 0 ;; esac
    else
      mark_skip "${alt:-$name}" "paid - skipped (free-only mode)"; return 0
    fi
  fi

  if ! arch_supported "$arch_list"; then
    mark_skip "${alt:-$name}" "not available for $ARCH"
    return 0
  fi

  if [ -n "$alt" ]; then
    printf '\n\n\033[1;34m==> Installing: %s   --->   %s\033[0m\n' "$name" "$alt" >&3
  else
    printf '\n\n\033[1;34m==> Installing: %s\033[0m\n' "$name" >&3
  fi
  [ -n "$note" ] && info "$note"

  # native package name for the running family
  local native_pkg=""
  case "$PM" in
    apt) native_pkg="$apt" ;; dnf) native_pkg="$dnf" ;;
    zypper) native_pkg="$zypper" ;; pacman) native_pkg="$pacman" ;;
  esac
  local slug; slug="$(slugify "$name")"

  # ---- single-path methods ----
  case "$method" in
    webapp)
      webapp_desktop "$name" "$webapp_url" "$alt" "$launch"; return 0 ;;
    docker)
      docker_launch_app "$name" "$docker_image" "$note"; return 0 ;;
    wine-bottles)
      if ensure_flatpak && capture install_flatpak com.usebottles.bottles; then
        mark_ok "$name" "via Bottles (flatpak) - configure the Windows app inside Bottles"
      else mark_fail "$name" "${LAST_ERR:-could not install Bottles (flatpak)}"; fi
      return 0 ;;
    manual)
      local mdir="${MIGRATE_MANUAL_DIR:-$DOWNLOAD_DIR/manual}/$slug" mf got=0
      if [ -d "$mdir" ] && [ -n "$(ls -A "$mdir" 2>/dev/null)" ]; then
        for mf in "$mdir"/*; do [ -f "$mf" ] && install_by_ext "$mf" && got=1; done
        if [ "$got" -eq 1 ]; then ledger_add file "$mdir"; mark_ok "$name" "installed from staged file" "$alt" "$launch"
        else mark_fail "${alt:-$name}" "${LAST_ERR:-staged file could not be installed}"; fi
      else
        mark_manual "${alt:-$name}" "${note:-manual install}"
      fi
      return 0 ;;
  esac

  # Universal "already installed" short-circuit. Unless the user asked to update
  # existing apps to the LATEST version, an app that is already present is skipped
  # entirely here -- BEFORE any vendor repo setup or download happens. This applies
  # when "same version" was chosen OR when existing apps are not being updated.
  if [ "${MIGRATE_VERSION_MODE:-latest}" = "same" ] || [ "${MIGRATE_UPDATE_EXISTING:-no}" != "yes" ]; then
    if { [ -n "$native_pkg" ] && pm_installed "${native_pkg%% *}"; } \
       || { [ -n "$flatpak" ] && have_cmd flatpak && flatpak_installed "$flatpak"; } \
       || { [ -n "$snap_pkg" ] && have_cmd snap && snap list "${snap_pkg%% *}" >/dev/null 2>&1; }; then
      local _d=""
      if   [ -n "$flatpak" ] && have_cmd flatpak && flatpak_installed "$flatpak"; then _d="flatpak $flatpak"
      elif [ -n "$native_pkg" ] && pm_installed "${native_pkg%% *}"; then _d="native $native_pkg"
      elif [ -n "$snap_pkg" ]; then _d="snap $snap_pkg"; fi
      # Show the Linux alternative (what is actually installed), not the Windows name.
      mark_skip "${alt:-$name}" "already installed" "${launch:-$(launch_hint_from_detail "${alt:-$name}" "$_d")}" "$alt"
      return 0
    fi
  fi

  # ---- multi-backend methods (req: try every available pm until one works) ----
  # The declared method goes first; then EVERY other available backend is tried as a
  # fallback (native / flatpak / snap / direct-download) before the app is failed.
  local order
  case "$method" in
    flatpak)            order="flatpak native snap deburl" ;;
    native)             order="native flatpak snap deburl" ;;
    snap)               order="snap flatpak native deburl" ;;
    deb-url|github-deb) order="deburl native flatpak snap" ;;
    *)                  order="flatpak native snap deburl" ;;
  esac

  local b url f rfn
  LAST_ERR=""   # so an empty value after the loop means "nothing was even attempted"
  for b in $order; do
    case "$b" in
      flatpak)
        [ -n "$flatpak" ] || continue
        ensure_flatpak || continue
        if capture install_flatpak "$flatpak"; then finish_install "$name" "$alt" flatpak "$flatpak" "flatpak $flatpak" "$launch"; return 0; fi ;;
      native)
        [ -n "$native_pkg" ] || continue
        # vendor's own repo first, for the latest upstream build (if defined).
        rfn="repo_setup_$(printf '%s' "$slug" | tr '-' '_')"
        if declare -F "$rfn" >/dev/null 2>&1; then
          info "configuring vendor repository for $name ..."
          "$rfn" || warn "vendor repo setup failed; falling back to the distro repo"
        fi
        pm_refresh
        # Skip if present, UNLESS the user asked to update existing apps (then
        # pm_install upgrades it to the latest available).
        if pm_installed "${native_pkg%% *}" && [ "${MIGRATE_UPDATE_EXISTING:-no}" != "yes" ]; then
          mark_skip "${alt:-$name}" "already installed" "${launch:-$(launch_hint_from_detail "${alt:-$name}" "native $native_pkg")}" "$alt"; return 0
        fi
        # match the Windows version when the user chose "same version".
        if [ "${MIGRATE_VERSION_MODE:-latest}" = "same" ] && [ -n "$winver" ]; then
          if install_native_version "$native_pkg" "$winver"; then finish_install "$name" "$alt" native "$native_pkg" "native $native_pkg (matched Windows $winver)" "$launch"; return 0; fi
          warn "could not match Windows version $winver; installing latest"
        fi
        if capture pm_install $native_pkg; then finish_install "$name" "$alt" native "$native_pkg" "native $native_pkg" "$launch"; return 0; fi ;;
      snap)
        [ -n "$snap_pkg" ] || continue
        ensure_snap || continue
        if capture snap install $snap_pkg; then finish_install "$name" "$alt" snap "$snap_pkg" "snap $snap_pkg" "$launch"; return 0; fi ;;
      deburl)
        [ -n "$url_x86$url_arm$url_deb$url_rpm" ] || continue
        # Prefer the package format matching the distro family (.deb on apt, .rpm on
        # dnf/zypper); fall back to the arch-keyed URLs when no format-specific one fits.
        url=""
        case "$PM" in apt) url="$url_deb" ;; dnf|zypper) url="$url_rpm" ;; esac
        [ -n "$url" ] || { url="$url_x86"; [ "$ARCH" = "aarch64" ] && [ -n "$url_arm" ] && url="$url_arm"; }
        [ -n "$url" ] || continue
        f="$DOWNLOAD_DIR/${name// /_}.pkg"
        if capture download_file "$url" "$f" && capture install_local_package "$f"; then finish_install "$name" "$alt" file "$f" "downloaded package" "$launch"; return 0; fi ;;
    esac
  done

  # A real install error -> report failure. But if nothing was even attempted (no
  # package-manager route on this distro), show that and fall back to the manual
  # download-by-user scheme (place the file, then done/skip, handled by extension).
  if [ -n "$LAST_ERR" ]; then
    mark_fail "${alt:-$name}" "$LAST_ERR"
  else
    err "no available package manager could install it"
    manual_fallback "$name" "$alt" "$note" "$webapp_url$url_x86$github_repo" "$launch"
  fi
}

# Public entry point. Pulls out any --post 'CMD' flags (custom commands to run right after
# this app installs), delegates the install to _install_app_core, then -- ONLY if the app
# was freshly installed this run (a new OK was recorded) -- runs those commands as the
# logged-in user. Everything else is unchanged, so apps without postInstall behave exactly
# as before.
install_app() {
  local -a _post=() _args=()
  local _name=""
  while [ "$#" -gt 0 ]; do
    if [ "$1" = "--post" ]; then _post+=("$2"); shift 2; continue; fi
    [ "$1" = "--name" ] && _name="$2"
    _args+=("$1"); shift
  done
  local _ok_before=${#OK_LIST[@]}
  _install_app_core "${_args[@]}"
  if [ "${#_post[@]}" -gt 0 ] && [ "${#OK_LIST[@]}" -gt "$_ok_before" ]; then
    run_post_install "$_name" "${_post[@]}"
  fi
}

# Resolve a user-typed installer path: strip surrounding single/double quotes and
# outer whitespace; absolute paths and ~/... are used as-is; a bare/relative path is
# taken relative to the logged-in user's Downloads folder. Echoes the resolved path.
resolve_user_path() {  # resolve_user_path RAW
  local p="$1"
  p="${p#"${p%%[![:space:]]*}"}"; p="${p%"${p##*[![:space:]]}"}"   # trim outer whitespace
  case "$p" in
    \'*\') p="${p#\'}"; p="${p%\'}" ;;
    \"*\") p="${p#\"}"; p="${p%\"}" ;;
  esac
  case "$p" in
    '')    : ;;
    /*)    : ;;
    '~')   p="$TARGET_HOME" ;;
    '~/'*) p="$TARGET_HOME/${p#\~/}" ;;
    *)     p="$TARGET_HOME/Downloads/$p" ;;
  esac
  printf '%s' "$p"
}

# Run a wine (Windows emulator) command as the logged-in user, in the prefix named by
# $WINE_PREFIX_DIR (a per-app prefix; defaults to the shared ~/.wine). The installer
# itself usually runs as root under sudo.
run_wine() {  # run_wine CMD [ARGS...]
  local prefix="${WINE_PREFIX_DIR:-$TARGET_HOME/.wine}"
  if [ "$(id -u)" -eq 0 ] && [ "$TARGET_USER" != "root" ]; then
    sudo -u "$TARGET_USER" env HOME="$TARGET_HOME" WINEARCH=win64 WINEPREFIX="$prefix" WINEDEBUG=-all "$@"
  else
    env HOME="$TARGET_HOME" WINEARCH=win64 WINEPREFIX="$prefix" WINEDEBUG=-all "$@"
  fi
}

# Like run_wine, but also forwards the desktop session (DISPLAY / WAYLAND_DISPLAY /
# XAUTHORITY) so a wine GUI window actually shows up on screen -- used to LAUNCH an app
# for the interactive first-launch appearance test. Registry/wineserver work that needs
# no display keeps using plain run_wine.
run_wine_gui() {  # run_wine_gui CMD [ARGS...]
  local prefix="${WINE_PREFIX_DIR:-$TARGET_HOME/.wine}"
  local disp="${DISPLAY:-:0}" xauth="${XAUTHORITY:-$TARGET_HOME/.Xauthority}" wld="${WAYLAND_DISPLAY:-}"
  if [ "$(id -u)" -eq 0 ] && [ "$TARGET_USER" != "root" ]; then
    sudo -u "$TARGET_USER" env HOME="$TARGET_HOME" WINEARCH=win64 WINEPREFIX="$prefix" WINEDEBUG=-all \
      DISPLAY="$disp" XAUTHORITY="$xauth" ${wld:+WAYLAND_DISPLAY="$wld"} "$@"
  else
    env HOME="$TARGET_HOME" WINEARCH=win64 WINEPREFIX="$prefix" WINEDEBUG=-all \
      DISPLAY="$disp" XAUTHORITY="$xauth" ${wld:+WAYLAND_DISPLAY="$wld"} "$@"
  fi
}

# Ensure wine (the Windows emulator) is installed -- and, if the user opted to update
# existing apps, up to date. Only ever called when a wine install is actually needed
# (from wine_app), and it does its package work at most once per run.
ensure_wine() {
  [ "${_WINE_READY:-0}" = "1" ] && return 0
  if have_cmd wine; then
    if [ "${MIGRATE_UPDATE_EXISTING:-no}" = "yes" ]; then
      info "updating wine (Windows emulator) ..."
      case "$PM" in
        apt) capture pm_install wine64 wine32 || capture pm_install wine || true ;;
        *)   capture pm_install wine || true ;;
      esac
    fi
    _WINE_READY=1; return 0
  fi
  info "installing wine (Windows emulator) ..."
  case "$PM" in
    apt)    dpkg --add-architecture i386 2>/dev/null || true; pm_refresh; capture pm_install wine64 wine32 || capture pm_install wine ;;
    dnf)    capture pm_install wine ;;
    zypper) capture pm_install wine ;;
    pacman) capture pm_install wine ;;
  esac
  if have_cmd wine; then _WINE_READY=1; return 0; else return 1; fi
}

# Ensure 32-bit (i386 / WoW64) wine support, required to run 32-bit Windows installers.
# A 64-bit-only wine cannot load syswow64\ntdll.dll (error c0000135). Done at most once.
ensure_wine_i386() {
  [ "${_WINE_I386_READY:-0}" = "1" ] && return 0
  info "ensuring 32-bit (i386) wine (Windows emulator) support ..."
  case "$PM" in
    apt)    dpkg --add-architecture i386 2>/dev/null || true; pm_refresh
            capture pm_install wine32:i386 || capture pm_install wine32 || capture pm_install libwine:i386 || true ;;
    dnf)    capture pm_install wine.i686 || capture pm_install wine || true ;;
    zypper) capture pm_install wine-32bit || capture pm_install wine || true ;;
    pacman) capture pm_install lib32-wine || warn "enable the [multilib] repo for 32-bit wine on Arch" ;;
  esac
  _WINE_I386_READY=1
}

# True if the installer FILE targets 32-bit x86 and therefore needs WoW64 / wine32 (a
# 64-bit-only wine fails with c0000135 -- "could not load kernel32.dll" -- on it).
# Handles BOTH PE executables (.exe) and Windows Installer (.msi) packages. An MSI is an
# OLE compound document, not a PE file, so its target CPU is read from the "Template"
# summary field: Intel -> 32-bit; x64/Intel64/Arm/Arm64 -> not 32-bit x86. MSIs with no
# recognisable arch default to "needs wine32" (the safe choice: wine32 never hurts 64-bit
# apps, but its absence breaks 32-bit ones).
is_32bit_pe() {  # is_32bit_pe FILE
  have_cmd file || return 1
  local t; t="$(file -bL "$1" 2>/dev/null)"
  case "$t" in
    *MSI\ Installer*)
      case "$t" in
        *Template:\ x64*|*Template:\ Intel64*|*Template:\ Arm*) return 1 ;;
        *)                                                      return 0 ;;
      esac ;;
    *x86-64*|*x86_64*|*PE32+*|*aarch64*|*ARM*) return 1 ;;
    *80386*|*"Intel i386"*)                    return 0 ;;
    *)                                         return 1 ;;
  esac
}

# Best-effort install of winetricks (helper for wine fonts/runtime verbs).
ensure_winetricks() {
  have_cmd winetricks && return 0
  case "$PM" in
    apt)    capture pm_install winetricks ;;
    dnf)    capture pm_install winetricks ;;
    zypper) capture pm_install winetricks ;;
    pacman) capture pm_install winetricks ;;
  esac
  have_cmd winetricks
}

# Run the Windows installer at PATH under wine, best-effort silent for the common
# installer types, teeing wine's output both to LOG (for failure analysis) and to the
# console. Returns wine's own exit status. Factored out so the install can be retried
# after enabling 32-bit (WoW64) wine support.
wine_run_installer() {  # wine_run_installer PATH LOG
  local p="$1" log="$2"
  case "$p" in
    *.msi|*.MSI)             run_wine wine msiexec /i "$p" /qn 2>&1 | tee "$log" >&3 ;;
    *.bat|*.BAT|*.cmd|*.CMD) run_wine wine cmd /c "$p" 2>&1 | tee "$log" >&3 ;;
    *)                       run_wine wine "$p" /S 2>&1 | tee "$log" >&3 ;;
  esac
  return "${PIPESTATUS[0]}"
}

# After a wine install, scan the per-app prefix for Start Menu .lnk shortcuts and emit
# .desktop launchers (run via "wine start") into the user's applications directory.
wine_make_launchers() {  # wine_make_launchers NAME PREFIX SLUG
  local name="$1" prefix="$2" slug="$3" appdir="$TARGET_HOME/.local/share/applications" lnk base dn n=0
  [ -d "$prefix/drive_c" ] || return 0
  mkdir -p "$appdir"
  while IFS= read -r lnk; do
    [ -f "$lnk" ] || continue
    base="$(basename "$lnk" .lnk)"
    dn="$appdir/wine-${slug}-$(printf '%s' "$base" | tr '[:upper:] ' '[:lower:]-' | tr -cd 'a-z0-9-_').desktop"
    {
      printf '[Desktop Entry]\n'
      printf 'Type=Application\n'
      printf 'Name=%s (wine - Windows emulator)\n' "$base"
      printf 'Exec=env WINEPREFIX="%s" wine start /unix "%s"\n' "$prefix" "$lnk"
      printf 'Terminal=false\nCategories=Wine;\n'
    } > "$dn" 2>/dev/null || continue
    chown "$TARGET_USER":"$TARGET_USER" "$dn" 2>/dev/null || true
    chmod +x "$dn" 2>/dev/null || true
    n=$((n+1))
  done <<EOF
$(find "$prefix/drive_c" -iname '*.lnk' -ipath '*Start Menu*' 2>/dev/null)
EOF
  [ "$n" -gt 0 ] && info "created $n wine (Windows emulator) launcher(s) for $name"
  return 0
}

# Manual download-by-user fallback for an app no package manager could install.
# Asks the user to download the installer and type its path (full, or relative to the
# logged-in user's Downloads folder) in single quotes; installs it by extension; loops
# until a valid path is given or the user skips. Marks the result.
manual_fallback() {  # manual_fallback NAME [ALT] [NOTE] [URL] [LAUNCH]
  local name="$1" alt="$2" mnote="$3" murl="$4" mlaunch="${5:-}"
  # "skip all" chosen earlier: skip this and every remaining manual app without prompting.
  if [ "${MANUAL_FALLBACK_SKIP_ALL:-0}" = "1" ]; then mark_skip "${alt:-$name}" "user skipped (skip all)"; return 0; fi
  if is_dry_run; then mark_plan "${alt:-$name}" "manual installer (you would provide its path)"; return 0; fi
  local ans f disp="${alt:-$name}"
  [ -n "$mnote" ] && info "$mnote"
  if [ -n "$murl" ]; then info "Download page: $murl"; info "(opening it in your default browser ...)"; open_url "$murl"; fi
  info "Download the installer yourself (unzip it first if it is zipped)."
  info "Then type its path in single quotes -- either a full path, or one relative to ${TARGET_HOME}/Downloads."
  info "Any valid installer extension works (.deb/.rpm/.sh/.run/.bin/.bundle/.AppImage/.tar.gz/.zip/...); 'skip' to skip this app, or 'skip all' to skip this and every remaining manual app."
  if [ ! -r /dev/tty ]; then mark_manual "${alt:-$name}" "no package manager route - needs manual download"; return 0; fi
  while :; do
    printf "  %s ('installer path'/s=skip/a=skip all): " "$disp" > /dev/tty
    read -r ans < /dev/tty || ans="skip"
    case "$ans" in
      [Aa]|[Aa][Ll][Ll]|[Ss][Kk][Ii][Pp][Aa][Ll][Ll]|'skip all'|'Skip all'|'Skip All'|'SKIP ALL')
        MANUAL_FALLBACK_SKIP_ALL=1; mark_skip "${alt:-$name}" "user skipped (skip all)"; return 0 ;;
      [Ss]|[Ss][Kk][Ii][Pp]) mark_skip "${alt:-$name}" "user skipped"; return 0 ;;
      *)
        f="$(resolve_user_path "$ans")"
        if [ -z "$f" ] || [ ! -f "$f" ] || [ ! -r "$f" ]; then
          printf "\033[1;31m  No readable file at that path -- type the path in single quotes (e.g. '%s/Downloads/app.deb'), or skip.\033[0m\n" "$TARGET_HOME" > /dev/tty; continue
        fi
        LAST_ERR=""
        if install_by_ext "$f"; then ledger_add file "$f"; mark_ok "$name" "installed from $f" "$alt" "$mlaunch"; return 0
        else printf "\033[1;31m  %s -- fix the file and re-enter its path, or skip.\033[0m\n" "${LAST_ERR:-could not handle the file}" > /dev/tty; fi
        ;;
    esac
  done
}

# --------------------- wine first-launch appearance tuning -------------------
# The adjustable visual factors and the "current" value that reproduces the
# appearance the freshly-installed app already has (font/DPI starts at 2.5x = 240,
# no virtual desktop). Once the user picks "yes all" these remembered values are
# applied silently to every later wine install. Defaults are seeded lazily.
: "${WINE_CFG_DPI:=240}"          # font scaling (DPI); 96 = 1x, 240 = 2.5x
: "${WINE_CFG_DESKTOP:=off}"      # virtual desktop size "WxH", or "off" for native windows
: "${WINE_APPEARANCE_ALL:=0}"     # 1 once the user answered "a" (apply to all upcoming)

# Pick the most likely "main program" Start Menu .lnk to launch for the test run
# (skip uninstallers / readmes / help / website links).
wine_primary_lnk() {  # wine_primary_lnk PREFIX
  local prefix="$1"
  [ -d "$prefix/drive_c" ] || return 1
  find "$prefix/drive_c" -iname '*.lnk' -ipath '*Start Menu*' 2>/dev/null \
    | grep -viE 'uninstall|readme|help|website|home page|homepage|on the web|manual' \
    | head -n1
}

# Launch the app (non-blocking) so its window appears on the user's desktop.
wine_launch() {  # wine_launch PREFIX LNK
  local prefix="$1" lnk="$2"
  WINE_PREFIX_DIR="$prefix"
  [ -n "$lnk" ] || { warn "no Start Menu shortcut found to launch for the test -- skipping the live preview"; return 1; }
  ( run_wine_gui wine start /unix "$lnk" >/dev/null 2>&1 & ) >/dev/null 2>&1
  sleep 3   # give the window a moment to draw before we ask about its appearance
  return 0
}

# Close every wine process in the prefix (used between/after appearance changes).
wine_close() {  # wine_close PREFIX
  local prefix="$1"; WINE_PREFIX_DIR="$prefix"
  run_wine wineserver -k >/dev/null 2>&1 || true
  sleep 1
}

# Validate the adjustable factors the user types.
valid_wine_dpi() {  # whole number 96..480
  case "$1" in ''|*[!0-9]*) return 1 ;; esac
  [ "$1" -ge 96 ] && [ "$1" -le 480 ]
}
# Accepts (W,H) / W,H / WxH (W,H positive), or off/native/none/no -> echoes WxH or "off".
normalize_wine_desktop() {  # normalize_wine_desktop INPUT  (echoes normalized, or nothing if invalid)
  local v="$1" w h
  v="$(printf '%s' "$v" | tr -d '[:space:]()')"
  case "$v" in
    [Oo][Ff][Ff]|[Nn][Oo]|[Nn][Oo][Nn][Ee]|[Nn][Aa][Tt][Ii][Vv][Ee]) printf 'off'; return 0 ;;
  esac
  v="$(printf '%s' "$v" | tr 'X' 'x')"
  case "$v" in
    *,*) w="${v%%,*}"; h="${v##*,}" ;;
    *x*) w="${v%%x*}"; h="${v##*x}" ;;
    *)   return 1 ;;
  esac
  case "$w" in ''|*[!0-9]*) return 1 ;; esac
  case "$h" in ''|*[!0-9]*) return 1 ;; esac
  [ "$w" -ge 320 ] && [ "$h" -ge 240 ] || return 1
  printf '%sx%s' "$w" "$h"
}

# Apply the current WINE_CFG_* factors to a prefix (font DPI + virtual desktop).
wine_apply_appearance() {  # wine_apply_appearance PREFIX
  local prefix="$1" hex; WINE_PREFIX_DIR="$prefix"
  hex="$(printf '0x%08X' "${WINE_CFG_DPI:-240}")"
  run_wine wine reg add 'HKEY_CURRENT_USER\Control Panel\Desktop' /v LogPixels /t REG_DWORD /d "$hex" /f >/dev/null 2>&1 || true
  if [ -n "${WINE_CFG_DESKTOP:-}" ] && [ "${WINE_CFG_DESKTOP}" != "off" ]; then
    run_wine wine reg add 'HKEY_CURRENT_USER\Software\Wine\Explorer\Desktops' /v Default /t REG_SZ /d "${WINE_CFG_DESKTOP}" /f >/dev/null 2>&1 || true
    run_wine wine reg add 'HKEY_CURRENT_USER\Software\Wine\Explorer'          /v Desktop /t REG_SZ /d Default            /f >/dev/null 2>&1 || true
  else
    run_wine wine reg delete 'HKEY_CURRENT_USER\Software\Wine\Explorer' /v Desktop /f >/dev/null 2>&1 || true
  fi
}

# Collect new values for every adjustable factor (each its own validate-or-retry loop).
# Updates WINE_CFG_DPI / WINE_CFG_DESKTOP. Empty input leaves a factor unchanged.
wine_collect_factors() {
  local ans norm
  # --- font scaling (DPI) ---
  while :; do
    printf '  enter new value for font scaling (DPI) in the format <a whole number 96-480, e.g. 96/120/144/192/240> (Current:%s) or enter to leave it unchanged: ' "${WINE_CFG_DPI:-240}" > /dev/tty
    read -r ans < /dev/tty || ans=""
    [ -z "$ans" ] && break
    if valid_wine_dpi "$ans"; then WINE_CFG_DPI="$ans"; break
    else printf '\033[1;31m  Invalid font scaling -- enter a whole number between 96 and 480 (96 = normal, 240 = 2.5x).\033[0m\n' > /dev/tty; fi
  done
  # --- window size (virtual desktop) ---
  while :; do
    printf '  enter new value for window size in the format <(width,height), e.g. (1024,768), or "off" for the app to use its own windows> (Current:%s) or enter to leave it unchanged: ' "${WINE_CFG_DESKTOP:-off}" > /dev/tty
    read -r ans < /dev/tty || ans=""
    [ -z "$ans" ] && break
    norm="$(normalize_wine_desktop "$ans")"
    if [ -n "$norm" ]; then WINE_CFG_DESKTOP="$norm"; break
    else printf '\033[1;31m  Invalid window size -- use (width,height) with width>=320 and height>=240 (e.g. (1280,720)), or "off".\033[0m\n' > /dev/tty; fi
  done
}

# Interactive first-launch appearance tuning for a freshly-installed wine app. Launches
# the app so the user can see it, collects/validates new visual-factor values, applies
# them, relaunches, and confirms -- with "start over" (r), "yes" (y) and "yes all" (a,
# remembered for every later wine install). No tty -> leave the defaults already applied.
wine_tune_appearance() {  # wine_tune_appearance NAME PREFIX
  local name="$1" prefix="$2" lnk ans
  WINE_PREFIX_DIR="$prefix"
  [ -r /dev/tty ] || return 0
  lnk="$(wine_primary_lnk "$prefix")"
  # "yes all" chosen earlier: apply the remembered look silently, no launch/prompting.
  if [ "${WINE_APPEARANCE_ALL:-0}" = "1" ]; then
    wine_apply_appearance "$prefix"
    info "applied your saved wine appearance (font DPI ${WINE_CFG_DPI:-240}, window ${WINE_CFG_DESKTOP:-off}) to $name"
    return 0
  fi
  # This app was just installed with the baseline look (DPI 240, native windows), so the
  # "Current:" shown for each factor must reflect that baseline.
  WINE_CFG_DPI=240; WINE_CFG_DESKTOP=off
  # one empty line after the last install line, then the purple launch notice.
  printf '\n' >&3
  purple "Now we launch the installed $name for the first time for testing"
  wine_launch "$prefix" "$lnk"
  while :; do   # start-over loop: broken only by "yes" (y) or "yes all" (a)
    purple "According to what you see for the appearance of the app, adjust the following visual settings or press enter to leave the default values:"
    wine_collect_factors
    # close, apply the chosen factors, then relaunch so the user sees the result.
    wine_close "$prefix"
    wine_apply_appearance "$prefix"
    wine_launch "$prefix" "$lnk"
    while :; do
      purple 'Is the current appearance what you would expect? "a" applies same configurations to all upcoming wine installations. (y=yes / a=yes all / r=start over)'
      printf '  (y/a/r): ' > /dev/tty
      read -r ans < /dev/tty || ans="y"
      case "$ans" in
        [Yy]|[Yy][Ee][Ss]) wine_close "$prefix"; return 0 ;;
        [Aa]|[Aa][Ll][Ll]) WINE_APPEARANCE_ALL=1; wine_close "$prefix"; info "these appearance settings will be applied to all upcoming wine installations"; return 0 ;;
        [Rr]|[Rr][Ee][Ss][Tt][Aa][Rr][Tt]) break ;;   # start over -> re-collect (app stays open)
        *) printf '\033[1;31m  Please answer y (yes), a (yes all), or r (start over).\033[0m\n' > /dev/tty ;;
      esac
    done
  done
}

# Install a non-cross-platform Windows app under wine (the Windows emulator), when the
# user opted in (MIGRATE_WINE_NONCROSS=yes). Tries the manifest-provided Windows
# installer URL first; on failure (or none) asks for the installer path in single
# quotes. After installing, scales the wine font/DPI to 2.5x (LogPixels 240) so the
# app is readable. Marks the result.
wine_app() {  # wine_app NAME [WINDOWS_INSTALLER_URL] [NOT_RECOMMENDED_REASON] [RECOMMENDED_ACTION]
  [ "${MIGRATE_WINE_NONCROSS:-no}" = "yes" ] || return 0
  local name="$1" winurl="${2:-}" nrreason="${3:-}" nraction="${4:-}" ans f winpath="" slug dir rc prefix
  if [ "${WINE_SKIP_ALL:-0}" = "1" ]; then mark_skip "$name (wine - Windows emulator)" "user skipped (skip all)"; return 0; fi
  if is_dry_run; then mark_plan "$name (wine - Windows emulator)" "${nrreason:+NOT RECOMMENDED; }${winurl:+auto-download + }run under wine in a per-app prefix; font 2.5x"; return 0; fi
  printf '\n\n\033[1;34m==> Install under wine (Windows emulator): %s\033[0m\n' "$name" >&3
  if ! ensure_wine; then mark_fail "$name (wine - Windows emulator)" "${LAST_ERR:-could not install wine}"; return 0; fi
  slug="$(slugify "$name")"
  # Per-app wine prefix (isolated, so one Windows app cannot break another).
  prefix="$TARGET_HOME/.local/share/wineprefixes/$slug"; WINE_PREFIX_DIR="$prefix"
  mkdir -p "$prefix" && chown -R "$TARGET_USER":"$TARGET_USER" "$TARGET_HOME/.local/share/wineprefixes" 2>/dev/null || true
  dir="${MIGRATE_MANUAL_DIR:-$DOWNLOAD_DIR/manual}/wine-$slug"; mkdir -p "$dir"
  # 1) auto-download the Windows installer if the manifest provided a URL (recommended
  #    apps only -- "not recommended" apps always go to the prompt so the warning shows).
  if [ -n "$winurl" ] && [ -z "$nrreason" ]; then
    f="$dir/${slug}-setup.exe"
    info "Downloading the Windows installer for $name (to run under wine - Windows emulator) ..."
    if capture download_file "$winurl" "$f"; then winpath="$f"
    else warn "automatic download failed -- you can provide the installer yourself."; fi
  fi
  # 2) manual fallback: ask for the installer path in single quotes.
  if [ -z "$winpath" ]; then
    if [ ! -r /dev/tty ]; then mark_manual "$name (wine - Windows emulator)" "provide a Windows installer to run under wine"; return 0; fi
    if [ -n "$winurl" ]; then info "Download page: $winurl"; info "(opening it in your default browser ...)"; open_url "$winurl"; fi
    info "Download the Windows installer for $name (unzip it first if it is zipped)."
    info "Then type its path in single quotes -- either a full path, or one relative to ${TARGET_HOME}/Downloads."
    info "Any valid installer extension works (.exe, .msi, .bat, etc.); 'skip' to skip this app, or 'skip all' to skip every remaining wine (Windows emulator) install."
    [ -n "$nrreason" ] && warn "Not recommended: ${nrreason}${nraction:+  Recommended: ${nraction}}"
    while :; do
      printf "  %s ('installer path'/s=skip/a=skip all): " "$name" > /dev/tty
      read -r ans < /dev/tty || ans="skip"
      case "$ans" in
        [Aa]|[Aa][Ll][Ll]|[Ss][Kk][Ii][Pp][Aa][Ll][Ll]|'skip all'|'Skip all'|'Skip All'|'SKIP ALL')
          WINE_SKIP_ALL=1; mark_skip "$name (wine - Windows emulator)" "user skipped (skip all)"; return 0 ;;
        [Ss]|[Ss][Kk][Ii][Pp]) mark_skip "$name (wine - Windows emulator)" "user skipped"; return 0 ;;
        *)
          winpath="$(resolve_user_path "$ans")"
          if [ -n "$winpath" ] && [ -f "$winpath" ] && [ -r "$winpath" ]; then break
          else printf "\033[1;31m  No readable file at that path -- type the path in single quotes (e.g. '%s/Downloads/setup.exe'), or skip.\033[0m\n" "$TARGET_HOME" > /dev/tty; winpath=""; fi ;;
      esac
    done
  fi
  # 2b) if the installer targets 32-bit x86 (PE .exe OR .msi), make sure wine has WoW64
  #     support BEFORE the prefix is initialised -- a 64-bit-only wine fails with c0000135
  #     ("could not load kernel32.dll") on 32-bit apps.
  is_32bit_pe "$winpath" && { info "installer is 32-bit (i386) -- enabling 32-bit wine (Windows emulator) support ..."; ensure_wine_i386; }
  run_wine wineboot -u >/dev/null 2>&1 || true
  # winetricks font baseline for better rendering/compatibility (best-effort).
  if ensure_winetricks; then run_wine winetricks -q corefonts >/dev/null 2>&1 || true; fi
  # 3) run the installer under wine (best-effort silent), then scale the font/DPI 2.5x.
  #    Capture wine's full output so a meaningful failure reason can be reported.
  info "installing $name under wine (Windows emulator) ..."
  local wlog; wlog="$(mktemp 2>/dev/null || echo /tmp/mtl_wine.$$)"
  wine_run_installer "$winpath" "$wlog"; rc=$?
  # Self-heal the classic 32-bit bootstrap failure: if wine could not load kernel32.dll
  # (c0000135) -- e.g. an installer whose 32-bit-ness we could not detect up front -- and
  # WoW64 support is not in yet, install 32-bit wine, rebuild the (worthless, half-booted)
  # prefix from scratch so syswow64 is populated, and retry the install once.
  if [ "$rc" -ne 0 ] && [ "${_WINE_I386_READY:-0}" != "1" ] \
     && grep -qiE 'c0000135|could not load (kernel32|ntdll)' "$wlog" 2>/dev/null; then
    warn "wine is missing 32-bit (i386) support -- enabling it and retrying the install ..."
    ensure_wine_i386
    rm -rf "$prefix" 2>/dev/null || true; mkdir -p "$prefix"
    chown -R "$TARGET_USER":"$TARGET_USER" "$TARGET_HOME/.local/share/wineprefixes" 2>/dev/null || true
    run_wine wineboot -u >/dev/null 2>&1 || true
    wine_run_installer "$winpath" "$wlog"; rc=$?
  fi
  # font size 2.5x: default wine DPI 96 -> 240 (LogPixels 0xF0), applied right after install.
  run_wine wine reg add 'HKEY_CURRENT_USER\Control Panel\Desktop' /v LogPixels /t REG_DWORD /d 0x000000F0 /f >/dev/null 2>&1 || true
  if [ "$rc" -eq 0 ]; then
    ledger_add wine "$prefix"
    wine_make_launchers "$name" "$prefix" "$slug"
    mark_ok "$name (wine - Windows emulator)" "installed under wine (per-app prefix); font/DPI 2.5x (240)"
    # First-launch appearance tuning: launch the app, let the user adjust the visual
    # factors, apply + confirm (or reuse the "yes all" settings). No-op without a tty.
    wine_tune_appearance "$name" "$prefix"
  else
    # Surface the most informative line from wine's output (skip fixme/diag noise),
    # then explain likely causes and the exact command to reproduce it interactively.
    local wreason ftype=""
    # Prefer a specific, human-meaningful cause (missing DLL/dependency/file, exception)...
    wreason="$(grep -iE 'import_dll|Library .* not found|cannot (find|open|execute)|No such file|Unhandled exception|needs.*(mono|gecko)|vcrun|msvc|\.NET' "$wlog" 2>/dev/null | grep -viE 'fixme:' | tail -n1 | sed 's/^[[:space:]]*//')"
    # ...otherwise any other err:/wine: line, ...
    [ -z "$wreason" ] && wreason="$(grep -iE 'err:|wine:|0x[0-9A-Fa-f]{6,}' "$wlog" 2>/dev/null | grep -viE 'fixme:|err:winediag' | tail -n1 | sed 's/^[[:space:]]*//')"
    # ...otherwise the last non-empty line.
    [ -z "$wreason" ] && wreason="$(grep -v '^[[:space:]]*$' "$wlog" 2>/dev/null | tail -n1 | sed 's/^[[:space:]]*//')"
    [ -z "$wreason" ] && wreason="exit code $rc"
    have_cmd file && ftype="$(file -bL "$winpath" 2>/dev/null)"
    mark_fail "$name (wine - Windows emulator)" "$wreason${ftype:+ | file is: $ftype} | likely a missing dependency, a wrong/partial download, or no silent-install support -- reproduce + see the full error with:  WINEPREFIX='$prefix' wine '$winpath'"
  fi
  rm -f "$wlog" 2>/dev/null || true
}

# Install the Nth-best alternative of an app only if the user asked for at least
# N alternatives (MIGRATE_ALT_LIMIT, default 1). Usage:  app_alt RANK install_app ...
app_alt() {
  local rank="$1"; shift
  local limit="${MIGRATE_ALT_LIMIT:-1}"
  case "$limit" in ''|*[!0-9]*) limit=1 ;; esac
  if [ "$rank" -le "$limit" ]; then "$@"; fi
  return 0
}

# Handle a user-downloaded installer FILE according to its extension. Returns 0 on
# success, 1 on failure (LAST_ERR holds a 1-line reason). Used by the manual phase.
install_by_ext() {  # install_by_ext FILE
  local f="$1"
  case "$f" in
    *.deb|*.rpm|*.pkg.tar.zst|*.pkg.tar.xz|*.pkg.tar)
      capture install_local_package "$f" ;;
    *.sh)
      chmod +x "$f" 2>/dev/null; capture bash "$f" ;;
    *.run|*.bin|*.bundle)
      chmod +x "$f" 2>/dev/null; capture "$f" ;;
    *.appimage|*.AppImage)
      chmod +x "$f" 2>/dev/null
      mkdir -p /opt/migrate_appimages
      if cp -f "$f" /opt/migrate_appimages/ 2>/dev/null; then return 0
      else LAST_ERR="could not place AppImage in /opt/migrate_appimages"; return 1; fi ;;
    *.tar.gz|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar)
      mkdir -p "${f%/*}/extracted"
      capture tar -xf "$f" -C "${f%/*}/extracted" ;;
    *.zip)
      if ! have_cmd unzip; then LAST_ERR="unzip is not installed"; return 1; fi
      mkdir -p "${f%/*}/extracted"
      capture unzip -o "$f" -d "${f%/*}/extracted" ;;
    *)
      LAST_ERR="unsupported file type: .${f##*.}"; return 1 ;;
  esac
}

ensure_docker() {
  have_cmd docker && return 0
  pm_refresh
  case "$PM" in
    apt)    pm_install docker.io ;;
    dnf)    pm_install moby-engine || pm_install docker ;;
    zypper) pm_install docker ;;
    pacman) pm_install docker ;;
  esac
  have_cmd docker && systemctl enable --now docker 2>/dev/null
  have_cmd docker
}

# =============================================================================
#  DOCKER CONTAINER LAUNCHING  (apps whose Linux equivalent IS a container)
# -----------------------------------------------------------------------------
#  For each app with install.method=docker we pull the image, attach it to ONE
#  shared bridge network, and start a container with sensible defaults. Host
#  ports are taken from the image's EXPOSED ports and bumped by 1 on conflict.
#  If a container for the same image already exists, we just (re)start it instead
#  of creating a duplicate. These are NOT the images migrated from Windows Docker
#  (those are handled separately by docker_rebuild.sh).
# =============================================================================
DOCKER_NET="${DOCKER_NET:-migrate-bridge}"

ensure_docker_net() {
  docker network inspect "$DOCKER_NET" >/dev/null 2>&1 && return 0
  capture docker network create --driver bridge "$DOCKER_NET" >/dev/null 2>&1 || \
    docker network create --driver bridge "$DOCKER_NET" >/dev/null 2>&1
}

# Track host ports assigned during this run; combined with live listener checks.
_MIGRATE_PORTS_TAKEN=""
_port_in_use() {  # _port_in_use PORT
  local p="$1"
  case " $_MIGRATE_PORTS_TAKEN " in *" $p "*) return 0 ;; esac
  if have_cmd ss; then
    ss -ltnH 2>/dev/null | awk '{print $4}' | sed 's/.*[:.]//' | grep -qx "$p" && return 0
  elif have_cmd netstat; then
    netstat -ltn 2>/dev/null | awk 'NR>2{print $4}' | sed 's/.*[:.]//' | grep -qx "$p" && return 0
  fi
  return 1
}
_pick_port() {  # _pick_port DESIRED -> free host port (incrementing on conflict)
  local p="$1"
  [ -z "$p" ] && { printf ''; return 0; }
  while _port_in_use "$p"; do p=$((p + 1)); done
  _MIGRATE_PORTS_TAKEN="$_MIGRATE_PORTS_TAKEN $p"
  printf '%s' "$p"
}

# Human-readable "how to use" line derived from the container's published ports.
_docker_howto() {  # _docker_howto CONTAINER NOTE
  local c="$1" note="$2" hp howto
  hp="$(docker port "$c" 2>/dev/null | sed -n 's/.*:\([0-9]\{1,\}\)$/\1/p' | head -n1)"
  if [ -n "$hp" ]; then howto="open http://localhost:${hp} in your browser"
  else howto="attach with: docker exec -it ${c} sh"; fi
  howto="${howto}; start/stop with: docker start ${c} / docker stop ${c}"
  [ -n "$note" ] && howto="${howto} (${note})"
  printf '%s' "$howto"
}

# Record a launched container ONCE (one line per container, deduped by name).
_record_launched() {  # _record_launched WINAPP IMAGE CONTAINER NOTE
  local winapp="$1" image="$2" c="$3" note="$4"
  if [ -f "$DOCKER_LAUNCHED" ] && cut -f3 "$DOCKER_LAUNCHED" 2>/dev/null | grep -qx "$c"; then return 0; fi
  printf '%s\t%s\t%s\t%s\n' "$winapp" "$image" "$c" "$(_docker_howto "$c" "$note")" >> "$DOCKER_LAUNCHED"
}

docker_launch_app() {  # docker_launch_app WINAPP IMAGE NOTE
  local winapp="$1" image="$2" note="$3"
  [ -z "$image" ] && { mark_fail "$winapp" "no docker image specified"; return 0; }
  if ! ensure_docker; then mark_fail "$winapp" "docker is not available"; return 0; fi
  docker info >/dev/null 2>&1 || systemctl start docker 2>/dev/null || true

  # Stable container name derived from the image (so the SAME image always maps to
  # the SAME container -> reuse instead of duplicate).
  local base cname
  base="${image##*/}"; base="${base%%:*}"
  cname="migrate-$(slugify "$base")"

  # Already created (this run or a previous one)? Just start it if stopped; never
  # create a second container for the same image.
  if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "$cname"; then
    if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "$cname"; then
      info "container already running: $cname"
    else
      capture docker start "$cname" >/dev/null 2>&1 || docker start "$cname" >/dev/null 2>&1 || true
    fi
    _record_launched "$winapp" "$image" "$cname" "$note"
    mark_ok "$winapp" "using existing container: $cname"
    return 0
  fi

  if ! capture docker pull "$image"; then mark_fail "$winapp" "${LAST_ERR:-could not pull docker image $image}"; return 0; fi
  ensure_docker_net

  # Map each EXPOSED container port to a free host port (incrementing on conflict).
  local pflags="" ep cport hport
  for ep in $(docker image inspect --format '{{range $p,$_ := .Config.ExposedPorts}}{{$p}} {{end}}' "$image" 2>/dev/null); do
    cport="${ep%%/*}"
    [ -z "$cport" ] && continue
    hport="$(_pick_port "$cport")"
    [ -n "$hport" ] && pflags="$pflags -p ${hport}:${cport}"
  done

  # shellcheck disable=SC2086
  if capture docker run -d --name "$cname" --network "$DOCKER_NET" --restart unless-stopped $pflags "$image"; then
    _record_launched "$winapp" "$image" "$cname" "$note"
    mark_ok "$winapp" "container launched: $cname"
  else
    mark_fail "$winapp" "${LAST_ERR:-could not start container for $image}"
  fi
}

# Purple "Launched containers" section (one line per container). Printed at the end
# of a run by execute_all (orchestrated) or print_summary (standalone stage).
print_launched_containers() {
  local f="${DOCKER_LAUNCHED:-/tmp/migrate_to_linux_launched.tsv}"
  [ -s "$f" ] || return 0
  printf '\n' >&3
  printf '        \033[1;35m===== Launched containers =====\033[0m\n' >&3
  local winapp image cname howto
  while IFS="$(printf '\t')" read -r winapp image cname howto; do
    [ -z "$cname" ] && continue
    info "          ${winapp}  --> image:'${image}' | container: '${cname}' | How to use: ${howto}"
  done < "$f"
}


main() {
  is_dry_run || require_root
  detect_distro
  detect_arch
  MODULE="Applications"
  log "Migrate to Linux  --  Must-Have Software"
  is_dry_run && log "DRY-RUN (report only): no changes will be made."
  info "Distribution : ${DISTRO_NAME}"
  info "Family / pm  : ${FAMILY} / ${PM}"
  info "Architecture : ${ARCH}"
  if ! is_dry_run; then
    pm_refresh
    ensure_flatpak || warn "Flatpak unavailable -- Flatpak-only apps will be skipped."
  fi

  # ---------------------------------------------------------------------------
  # Application install list (generated from B_applications.json + the
  # Additional_Manual_Linux_Software_Requirments.csv).
  # ---------------------------------------------------------------------------
  repo_setup_docker_desktop() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      . /etc/os-release
      docker_base=debian
      case " ${ID:-} ${ID_LIKE:-} " in *ubuntu*) docker_base=ubuntu ;; esac
      docker_suite="${UBUNTU_CODENAME:-${VERSION_CODENAME:-stable}}"
      curl -fsSL "https://download.docker.com/linux/${docker_base}/gpg" | gpg --batch --yes --dearmor -o /etc/apt/keyrings/docker.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${docker_base} ${docker_suite} stable" > /etc/apt/sources.list.d/docker.list
      ;;
    dnf)
      dnf -y install dnf-plugins-core
      dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      ;;
  esac
}
repo_setup_google_chrome() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --batch --yes --dearmor -o /etc/apt/keyrings/google-chrome.gpg
      echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      ;;
    dnf)
      printf '%s\n' '[google-chrome]' 'name=google-chrome' 'baseurl=https://dl.google.com/linux/chrome/rpm/stable/x86_64' 'enabled=1' 'gpgcheck=1' 'gpgkey=https://dl.google.com/linux/linux_signing_key.pub' > /etc/yum.repos.d/google-chrome.repo
      ;;
  esac
}
repo_setup_microsoft_edge() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --batch --yes --dearmor -o /etc/apt/keyrings/microsoft.gpg
      echo "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list
      ;;
    dnf)
      rpm --import https://packages.microsoft.com/keys/microsoft.asc
      printf '%s\n' '[microsoft-edge]' 'name=microsoft-edge' 'baseurl=https://packages.microsoft.com/yumrepos/edge' 'enabled=1' 'gpgcheck=1' 'gpgkey=https://packages.microsoft.com/keys/microsoft.asc' > /etc/yum.repos.d/microsoft-edge.repo
      ;;
  esac
}
repo_setup_visual_studio_code() {
  case "$PM" in
    apt)
      install -d -m 0755 /etc/apt/keyrings
      curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --batch --yes --dearmor -o /etc/apt/keyrings/microsoft.gpg
      echo "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list
      ;;
    dnf)
      rpm --import https://packages.microsoft.com/keys/microsoft.asc
      printf '%s\n' '[code]' 'name=Visual Studio Code' 'baseurl=https://packages.microsoft.com/yumrepos/vscode' 'enabled=1' 'gpgcheck=1' 'gpgkey=https://packages.microsoft.com/keys/microsoft.asc' > /etc/yum.repos.d/vscode.repo
      ;;
  esac
}
repo_setup_nodejs() {
  case "$PM" in
    apt)
      curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      ;;
    dnf)
      curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
      ;;
  esac
}
  app_alt 1 install_app --name "µTorrent" --alt "qBittorrent" --method flatpak --flatpak "org.qbittorrent.qBittorrent" --apt "qbittorrent" --dnf "qbittorrent" --zypper "qbittorrent" --pacman "qbittorrent"
  wine_app "µTorrent" "" "uTorrent-under-Wine is fragile and its Windows installer bundles adware." "Install the native qBittorrent alternative instead."
  app_alt 1 install_app --name "Adobe Digital Editions 4.5" --alt "calibre" --method flatpak --flatpak "com.calibre_ebook.calibre" --apt "calibre" --dnf "calibre" --zypper "calibre" --pacman "calibre"
  app_alt 2 install_app --name "Adobe Digital Editions 4.5" --alt "Thorium Reader" --method flatpak --note "needs manifest enrichment - see https://www.edrlab.org/software/thorium-reader/"
  wine_app "Adobe Digital Editions 4.5" "" "" ""
  app_alt 1 install_app --name "Anki Launcher" --alt "Anki (Linux)" --winver "25.09" --method flatpak --flatpak "net.ankiweb.Anki"
  app_alt 1 install_app --name "AnyDesk" --alt "AnyDesk (Linux)" --method flatpak --flatpak "com.anydesk.Anydesk"
  app_alt 1 install_app --name "Babylon" --alt "GoldenDict" --method native --apt "goldendict" --dnf "goldendict" --zypper "goldendict" --pacman "goldendict"
  wine_app "Babylon" "" "" ""
  app_alt 1 install_app --name "Bitvise SSH Client" --alt "OpenSSH" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  wine_app "Bitvise SSH Client" "" "" ""
  app_alt 1 install_app --name "calibre" --alt "calibre (Linux)" --winver "9.5.0" --method flatpak --flatpak "com.calibre_ebook.calibre" --apt "calibre" --dnf "calibre" --zypper "calibre" --pacman "calibre"
  app_alt 1 install_app --name "CMake" --alt "CMake (Linux)" --winver "4.3.0" --method native --apt "cmake" --dnf "cmake" --zypper "cmake" --pacman "cmake"
  app_alt 1 install_app --name "Discord" --alt "Discord (Linux)" --method flatpak --flatpak "com.discordapp.Discord"
  app_alt 1 install_app --name "Docker Desktop" --alt "Docker Engine (native)" --winver "4.70.0" --method native --apt "docker-ce docker-ce-cli containerd.io docker-compose-plugin" --dnf "docker-ce docker-ce-cli containerd.io docker-compose-plugin" --zypper "docker" --pacman "docker" --note "systemctl enable --now docker; add your user to the docker group"
  app_alt 1 install_app --name "Dropbox" --alt "Dropbox (Linux)" --method flatpak --flatpak "com.dropbox.Client"
  app_alt 1 install_app --name "Git" --alt "Git (Linux)" --winver "2.54.0" --method native --apt "git" --dnf "git" --zypper "git" --pacman "git"
  app_alt 1 install_app --name "GitHub Desktop" --alt "GitKraken" --method flatpak --flatpak "com.axosoft.GitKraken"
  wine_app "GitHub Desktop" "" "" ""
  app_alt 1 install_app --name "GnuWin32: Grep" --alt "GNU grep (native)" --method native --apt "grep" --dnf "grep" --zypper "grep" --pacman "grep"
  app_alt 1 install_app --name "Google Chrome" --alt "Google Chrome (Linux)" --method native --flatpak "com.google.Chrome" --apt "google-chrome-stable" --dnf "google-chrome-stable"
  app_alt 1 install_app --name "Google Drive" --alt "Insync" --method manual --url-x86 "https://www.insynchq.com/downloads" --note "Insync (.deb/.rpm) from insynchq.com; FOSS alt: rclone / google-drive-ocamlfuse" --paid
  wine_app "Google Drive" "" "" ""
  app_alt 1 install_app --name "Grammarly for Windows" --alt "LanguageTool" --method manual --note "LanguageTool: run via Docker (erikvl87/languagetool) or use the browser extension"
  wine_app "Grammarly for Windows" "" "" ""
  app_alt 1 install_app --name "Hotspot Shield" --alt "Hotspot Shield (Linux)" --method manual --note "No official Linux client; use Proton VPN or OpenVPN instead"
  app_alt 1 install_app --name "Internet Download Manager (IDM)" --alt "uGet" --launch "Search 'uGet' in the start menu (or run 'uget-gtk' in a terminal)." --method native --apt "uget" --dnf "uget" --pacman "uget" --note "also install aria2 for multi-connection downloads"
  wine_app "Internet Download Manager (IDM)" "" "" ""
  app_alt 1 install_app --name "Java 8" --alt "OpenJDK (Eclipse Temurin)" --winver "8.0.4910.10" --method native --apt "default-jdk" --dnf "java-latest-openjdk" --zypper "java-openjdk" --pacman "jdk-openjdk"
  app_alt 1 install_app --name "KMPlayer" --alt "VLC Media Player" --method flatpak --flatpak "org.videolan.VLC" --apt "vlc" --dnf "vlc" --zypper "vlc" --pacman "vlc"
  wine_app "KMPlayer" "" "" ""
  app_alt 1 install_app --name "Lenovo Professional Wireless Rechargeable Combo" --alt "Solaar" --method flatpak --flatpak "io.github.pwr_solaar.solaar" --apt "solaar" --dnf "solaar" --pacman "solaar"
  wine_app "Lenovo Professional Wireless Rechargeable Combo" "" "" ""
  app_alt 1 install_app --name "Lightshot" --alt "Flameshot" --method flatpak --flatpak "org.flameshot.Flameshot" --apt "flameshot" --dnf "flameshot" --zypper "flameshot" --pacman "flameshot"
  wine_app "Lightshot" "" "" ""
  app_alt 1 install_app --name "Longman Dictionary of Contemporary English 5th Edition" --alt "GoldenDict / GoldenDict-ng" --method native --apt "goldendict" --dnf "goldendict" --zypper "goldendict" --pacman "goldendict"
  wine_app "Longman Dictionary of Contemporary English 5th Edition" "" "" ""
  app_alt 1 install_app --name "Microsoft .NET SDK" --alt ".NET SDK (Linux)" --winver "40.11.22621" --method snap --snap "dotnet-sdk --classic" --note "or use your distro's dotnet-sdk / Microsoft repo"
  app_alt 1 install_app --name "Microsoft 365 / Office" --alt "LibreOffice" --method flatpak --flatpak "org.libreoffice.LibreOffice" --apt "libreoffice" --dnf "libreoffice" --zypper "libreoffice" --pacman "libreoffice"
  wine_app "Microsoft 365 / Office" "" "" ""
  app_alt 1 install_app --name "Microsoft Edge" --alt "Microsoft Edge (Linux)" --method native --flatpak "com.microsoft.Edge" --apt "microsoft-edge-stable" --dnf "microsoft-edge-stable"
  app_alt 1 install_app --name "Microsoft OneDrive" --alt "onedrive (abraunegg)" --method native --apt "onedrive" --dnf "onedrive" --pacman "onedrive"
  wine_app "Microsoft OneDrive" "" "" ""
  app_alt 1 install_app --name "Visual Studio Code" --alt "Visual Studio Code (Linux)" --winver "1.126.0" --method native --flatpak "com.visualstudio.code" --apt "code" --dnf "code"
  app_alt 1 install_app --name "MiKTeX" --alt "TeX Live" --method native --apt "texlive" --dnf "texlive-scheme-basic" --zypper "texlive" --pacman "texlive-core" --note "install the -full variants for everything"
  app_alt 1 install_app --name "Miniconda3" --alt "Miniconda (Linux)" --method manual --url-x86 "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" --url-arm "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh" --note "Download the Miniconda installer for your architecture and run: bash Miniconda3-latest-Linux-*.sh"
  wine_app "Miniconda3" "" "" ""
  app_alt 1 install_app --name "MobaXterm" --alt "Built-in terminal + OpenSSH" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  wine_app "MobaXterm" "" "" ""
  app_alt 1 install_app --name "Mozilla Firefox" --alt "Firefox (Linux)" --winver "152.0.3" --method flatpak --flatpak "org.mozilla.firefox" --apt "firefox" --dnf "firefox" --zypper "MozillaFirefox" --pacman "firefox"
  app_alt 1 install_app --name "ninja" --alt "ninja-build (Linux)" --winver "1.13.2" --method native --apt "ninja-build" --dnf "ninja-build" --zypper "ninja" --pacman "ninja"
  app_alt 1 install_app --name "Node.js" --alt "Node.js (Linux)" --winver "24.15.0" --method native --apt "nodejs" --dnf "nodejs" --zypper "nodejs npm" --pacman "nodejs npm"
  app_alt 1 install_app --name "NordVPN" --alt "NordVPN for Linux" --method manual --note "Install via NordVPN's official script: sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)  -- or add their apt/dnf repo. Requires a NordVPN subscription to log in." --paid
  wine_app "NordVPN" "" "" ""
  app_alt 1 install_app --name "Notepad++" --alt "Notepadqq" --method native --apt "notepadqq" --note "alt: install 'code' or a GNOME/KDE editor"
  wine_app "Notepad++" "https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.9.6.4/npp.8.9.6.4.Installer.x64.exe" "" ""
  app_alt 1 install_app --name "oCam version 550.0" --alt "OBS Studio" --method flatpak --flatpak "com.obsproject.Studio" --apt "obs-studio"
  wine_app "oCam version 550.0" "" "" ""
  app_alt 1 install_app --name "OpenSSH" --alt "OpenSSH (native)" --winver "8.9.1.0" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  app_alt 1 install_app --name "OpenSSL" --alt "OpenSSL (native)" --winver "3.3.0" --method native --apt "openssl" --dnf "openssl" --zypper "openssl" --pacman "openssl"
  app_alt 1 install_app --name "Pandoc" --alt "Pandoc (Linux)" --winver "3.9" --method native --apt "pandoc" --dnf "pandoc" --zypper "pandoc" --pacman "pandoc"
  app_alt 1 install_app --name "pgAdmin 4" --alt "pgAdmin 4 (Linux)" --method manual --url-x86 "https://www.pgadmin.org/download/" --note "pgAdmin 4 from the official apt/dnf repo"
  app_alt 1 install_app --name "PowerShell" --alt "PowerShell (Linux)" --winver "7.6.3.0" --method snap --snap "powershell --classic" --note "or use the Microsoft package repo"
  app_alt 1 install_app --name "PowerToys" --alt "Frog (Text Extractor replacement)" --method flatpak --flatpak "com.github.tenderowl.frog"
  wine_app "PowerToys" "" "" ""
  app_alt 1 install_app --name "Proxifier" --alt "proxychains-ng" --launch "Command-line tool (no menu entry): run 'proxychains4 <program>' in a terminal." --method native --apt "proxychains4" --dnf "proxychains-ng" --zypper "proxychains-ng" --pacman "proxychains-ng"
  wine_app "Proxifier" "" "" ""
  app_alt 1 install_app --name "PuTTY" --alt "OpenSSH (native)" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh" --note "GUI alt: install 'putty'"
  app_alt 1 install_app --name "Python" --alt "python3 (system)" --winver "3.14.5150.0" --method native --apt "python3 python3-pip" --dnf "python3 python3-pip" --zypper "python3 python3-pip" --pacman "python python-pip"
  app_alt 1 install_app --name "Nearby Share / Quick Share" --alt "LocalSend" --method flatpak --flatpak "org.localsend.localsend_app"
  wine_app "Nearby Share / Quick Share" "" "" ""
  app_alt 1 install_app --name "R for Windows" --alt "R (Linux)" --winver "4.5.2" --method native --apt "r-base" --dnf "R" --zypper "R-base" --pacman "r"
  app_alt 1 install_app --name "Snoopy" --alt "OpenSSH + terminal" --method native --apt "openssh-client" --dnf "openssh-clients" --zypper "openssh" --pacman "openssh"
  wine_app "Snoopy" "" "" ""
  app_alt 1 install_app --name "SQL Server Management Studio (SSMS)" --alt "DBeaver" --method flatpak --flatpak "io.dbeaver.DBeaverCommunity"
  wine_app "SQL Server Management Studio (SSMS)" "" "" ""
  app_alt 1 install_app --name "Strawberry Perl" --alt "Perl (native)" --winver "5.42.1" --method native --apt "perl" --dnf "perl" --zypper "perl" --pacman "perl"
  app_alt 1 install_app --name "Visual Studio Build Tools / Community" --alt ".NET SDK + VS Code" --method flatpak --flatpak "com.visualstudio.code" --note "also install the build toolchain (build-essential / @development-tools) and dotnet-sdk"
  wine_app "Visual Studio Build Tools / Community" "" "" ""
  app_alt 1 install_app --name "WinRAR" --alt "p7zip / 7-Zip" --method native --apt "p7zip-full" --dnf "p7zip p7zip-plugins" --zypper "p7zip" --pacman "p7zip" --note "also install 'unrar' for RAR archives"
  wine_app "WinRAR" "https://www.rarlab.com/rar/winrar-x64-722.exe" "" ""
  app_alt 1 install_app --name "wkhtmltox" --alt "wkhtmltopdf (Linux)" --method native --apt "wkhtmltopdf" --dnf "wkhtmltopdf" --pacman "wkhtmltopdf"
  app_alt 1 install_app --name "Alarms & Clock" --alt "GNOME Clocks" --method flatpak --flatpak "org.gnome.clocks" --apt "gnome-clocks" --dnf "gnome-clocks" --pacman "gnome-clocks"
  app_alt 1 install_app --name "MS Teams" --alt "Teams PWA (Edge/Chrome)" --method webapp --webapp "https://teams.microsoft.com"
  app_alt 1 install_app --name "Outlook For Windows" --alt "Thunderbird" --method flatpak --flatpak "org.mozilla.Thunderbird" --apt "thunderbird" --dnf "thunderbird" --zypper "MozillaThunderbird" --pacman "thunderbird"
  app_alt 1 install_app --name "Paint" --alt "Pinta" --method flatpak --flatpak "com.github.PintaProject.Pinta" --apt "pinta" --dnf "pinta"
  app_alt 1 install_app --name "Photos" --alt "Shotwell" --method flatpak --flatpak "org.gnome.Shotwell" --apt "shotwell" --dnf "shotwell" --pacman "shotwell"
  app_alt 1 install_app --name "Psiphon Conduit" --alt "Proton VPN" --method manual --url-x86 "https://protonvpn.com/support/official-linux-client/" --note "Proton VPN app via the official apt/dnf repo"
  app_alt 1 install_app --name "Sound Recorder" --alt "GNOME Sound Recorder" --method flatpak --flatpak "org.gnome.SoundRecorder" --apt "gnome-sound-recorder"
  app_alt 1 install_app --name "Sticky Notes" --alt "GNOME Sticky Notes (sticky)" --method flatpak --flatpak "com.vixalien.sticky" --apt "gnote"
  app_alt 1 install_app --name "Ubuntu (WSL)" --alt "Native Linux" --method manual --note "Not applicable - you are already running Linux"
  app_alt 1 install_app --name "Weather" --alt "GNOME Weather" --method flatpak --flatpak "org.gnome.Weather" --apt "gnome-weather" --dnf "gnome-weather" --pacman "gnome-weather"
  app_alt 1 install_app --name "WhatsApp Desktop" --alt "WhatsApp Web (PWA)" --method webapp --webapp "https://web.whatsapp.com"
  app_alt 1 install_app --name "Windows Calculator" --alt "GNOME Calculator" --method flatpak --flatpak "org.gnome.Calculator" --apt "gnome-calculator" --dnf "gnome-calculator" --pacman "gnome-calculator"
  app_alt 1 install_app --name "Windows Camera" --alt "Cheese" --method flatpak --flatpak "org.gnome.Cheese" --apt "cheese" --dnf "cheese" --pacman "cheese"
  app_alt 1 install_app --name "Windows Notepad" --alt "GNOME Text Editor / gedit" --method flatpak --flatpak "org.gnome.TextEditor" --apt "gnome-text-editor" --dnf "gnome-text-editor"
  app_alt 1 install_app --name "Windows Store" --alt "GNOME Software / KDE Discover" --method native --apt "gnome-software" --dnf "gnome-software" --pacman "gnome-software" --note "KDE: plasma-discover"
  app_alt 1 install_app --name "Windows Terminal" --alt "GNOME Console / GNOME Terminal" --method native --apt "gnome-terminal" --dnf "gnome-terminal" --pacman "gnome-terminal" --note "or 'kgx' (GNOME Console)"
  app_alt 1 install_app --name "Zune Music / Windows Media Player" --alt "Rhythmbox" --method flatpak --flatpak "org.gnome.Rhythmbox" --apt "rhythmbox" --dnf "rhythmbox" --pacman "rhythmbox"
  app_alt 1 install_app --name "CopyQ" --alt "CopyQ" --method native --flatpak "com.github.hluk.copyq" --apt "copyq" --dnf "copyq" --zypper "copyq" --pacman "copyq" --arch "x86_64 aarch64" --note "Binds Win+V (Super+V) as the shortcut to open CopyQ's clipboard history viewer (GNOME / GNOME-based desktops via gsettings)." --post "b=/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/copyq/; base=org.gnome.settings-daemon.plugins.media-keys; list=\$(gsettings get \$base custom-keybindings 2>/dev/null); case \"\$list\" in *copyq*) : ;; *) if [ -z \"\$list\" ] || [ \"\$list\" = \"@as []\" ] || [ \"\$list\" = \"[]\" ]; then list=\"['\$b']\"; else list=\"\${list%]}, '\$b']\"; fi; gsettings set \$base custom-keybindings \"\$list\" ;; esac; k=\"\$base.custom-keybinding:\$b\"; gsettings set \"\$k\" name 'CopyQ Clipboard History'; gsettings set \"\$k\" command 'copyq toggle'; gsettings set \"\$k\" binding '<Super>v'"
  install_app --name "Adobe Acrobat Pro" --alt "Stirling PDF (Docker) + PDF Arranger (APT)" --method manual --url-x86 "https://github.com/Stirling-Tools/Stirling-PDF" --note "Stirling PDF (Docker) + PDF Arranger (APT) | stirlingtools.com (Docker Hub); pdfarranger (APT)"
  install_app --name "Advanced IP Scanner" --alt "Angry IP Scanner (.deb)" --method manual --url-x86 "https://angryip.org/download/" --note "Angry IP Scanner (.deb) | angryip.org"
  install_app --name "Advanced Port Scanner" --alt "RustScan + nmap + Zenmap" --method manual --url-x86 "https://github.com/RustScan/RustScan" --note "RustScan + nmap + Zenmap | github.com/RustScan/RustScan; nmap.org"
  install_app --name "Telegram" --alt "telegram-desktop (APT/Flatpak)" --method manual --url-x86 "https://telegram.org/dl/desktop/linux" --note "telegram-desktop (APT/Flatpak) | telegram.org"
  install_app --name "Terminator" --alt "terminator (APT)" --method manual --url-x86 "https://github.com/gnome-terminator/terminator" --note "terminator (APT) | gnometerminator.blogspot.com"
  install_app --name "WindTerm" --alt "WindTerm .deb from GitHub" --method manual --url-x86 "https://github.com/kingToolfish/WindTerm/releases" --note "WindTerm .deb from GitHub | github.com/kingToolfish/WindTerm"
  install_app --name "WinDirStat" --alt "QDirStat + baobab (APT)" --method manual --url-x86 "https://github.com/shundhammer/qdirstat" --note "QDirStat + baobab (APT) | github.com/shundhammer/qdirstat; GNOME baobab"
  install_app --name "PaperCut" --alt "PaperCut Print Deploy Native Linux client" --method manual --url-x86 "https://<server>:9174" --note "PaperCut Print Deploy Native Linux client | Your PaperCut server (https://<server>:9174)"
  install_app --name "Visual Studio Community 2026" --alt "VS Code (APT repo) + JetBrains Rider (optional)" --method manual --url-x86 "https://code.visualstudio.com/download" --note "VS Code (APT repo) + JetBrains Rider (optional) | code.visualstudio.com; jetbrains.com/rider"
  install_app --name "Visual Studio Build Tools 2026" --alt "dotnet-sdk (APT repo) + MSBuild via Mono + gcc/clang + make/CMake" --method manual --url-x86 "https://packages.microsoft.com/" --note "dotnet-sdk (APT repo) + MSBuild via Mono + gcc/clang + make/CMake | packages.microsoft.com"
  install_app --name "Adobe Digital Editions" --alt "Thorium Reader (Flatpak) + calibre (APT) + Foliate (APT)" --method manual --url-x86 "https://www.edrlab.org/software/thorium-reader/" --note "Thorium Reader (Flatpak) + calibre (APT) + Foliate (APT) | edrlab.org; calibre-ebook.com; johnfactotum.github.io/foliate"
  install_app --name "Pinta" --alt "Pinta (Flatpak)" --method manual --url-x86 "https://flathub.org/apps/com.github.PintaProject.Pinta" --note "Pinta (Flatpak) | flathub.org: com.github.PintaProject.Pinta"
  install_app --name "LanguageTool" --alt "LanguageTool .zip from languagetool.org" --method manual --url-x86 "https://languagetool.org/download/" --note "LanguageTool .zip from languagetool.org | languagetool.org"
  install_app --name "Proton VPN" --alt "proton-vpn-gnome-desktop (APT repo)" --method manual --url-x86 "https://protonvpn.com/support/official-linux-vpn/" --note "proton-vpn-gnome-desktop (APT repo) | repo.protonvpn.com"
  install_app --name "Wine" --alt "winehq-stable (APT repo) + wine32 + i386 architecture" --method manual --url-x86 "https://wiki.winehq.org/Download" --note "winehq-stable (APT repo) + wine32 + i386 architecture | dl.winehq.org"
  install_app --name "VirtualBox" --alt "virtualbox-7.1 (APT repo)" --method manual --url-x86 "https://www.virtualbox.org/wiki/Linux_Downloads" --note "virtualbox-7.1 (APT repo) | download.virtualbox.org"
  install_app --name "PostgreSQL" --alt "postgresql + postgresql-client (PGDG APT repo)" --method manual --url-x86 "https://www.postgresql.org/download/linux/" --note "postgresql + postgresql-client (PGDG APT repo) | apt.postgresql.org"
  install_app --name "Docker Engine" --alt "docker-ce + docker-ce-cli + containerd.io + docker-buildx-plugin + docker-compose-plugin (APT repo)" --method manual --url-x86 "https://docs.docker.com/engine/install/" --note "docker-ce + docker-ce-cli + containerd.io + docker-buildx-plugin + docker-compose-plugin (APT repo) | download.docker.com"
  install_app --name "Multipass" --alt "multipass (APT SnapStore replacement)" --method manual --url-x86 "https://canonical.com/multipass/install" --note "multipass (APT SnapStore replacement) | canonical.com/multipass"
  install_app --name "Microsoft OneNote" --alt "Obsidian (Flatpak/.deb) + Joplin (Flatpak) + Xournal++ (APT) + OneNote WebApp .desktop shortcut" --method manual --url-x86 "https://obsidian.md/download" --note "Obsidian (Flatpak/.deb) + Joplin (Flatpak) + Xournal++ (APT) + OneNote WebApp .desktop shortcut | obsidian.md; joplinapp.org; xournalpp.github.io; onenote.com"

  print_summary
}

main "$@"
